### ISSUE TITLE
Refining a search

### ISSUE THREAD

**Issue by monicacecilia** [geneontology/helpdesk#1]
### From the now-archived JIRA GO help desk. 

From : Lovisa Åkesson
> Hi,
I'm in the need of estimating the number of human genes localizing to multiple cellular compartments (or organelles) based on the gene ontology cellular compartment terms. However, when I download the terms for each gene, most of the GO-terms are redundant. Is there a way to group all the terms for one gene into one major organelle or cellular compartment? I have tried to group them to their parent term before, but most of the parent terms are not on the same hierarchy level for all organelles which makes it hard.
Thanks in advance!
Kind regards,
Lovisa

**Comment by kltm** [comment]
Assigning @cmungall from original ticket. We believe this may concern the creation of a new slim.

**Comment by cmungall** [comment]
goslim_generic is probably fine. Here is the cc subset:

```
GO:0000228 ! nuclear chromosome
GO:0000229 ! cytoplasmic chromosome
GO:0005575 ! cellular_component
GO:0005576 ! extracellular region
GO:0005578 ! proteinaceous extracellular matrix
GO:0005615 ! extracellular space
GO:0005618 ! cell wall
GO:0005622 ! intracellular
GO:0005623 ! cell
GO:0005634 ! nucleus
GO:0005635 ! nuclear envelope
GO:0005654 ! nucleoplasm
GO:0005694 ! chromosome
GO:0005730 ! nucleolus
GO:0005737 ! cytoplasm
GO:0005739 ! mitochondrion
GO:0005764 ! lysosome
GO:0005768 ! endosome
GO:0005773 ! vacuole
GO:0005777 ! peroxisome
GO:0005783 ! endoplasmic reticulum
GO:0005794 ! Golgi apparatus
GO:0005811 ! lipid particle
GO:0005815 ! microtubule organizing center
GO:0005829 ! cytosol
GO:0005840 ! ribosome
GO:0005856 ! cytoskeleton
GO:0005886 ! plasma membrane
GO:0005929 ! cilium
GO:0009536 ! plastid
GO:0009579 ! thylakoid
GO:0030312 ! external encapsulating structure
GO:0031410 ! cytoplasmic vesicle
GO:0043226 ! organelle
GO:0043234 ! protein complex
```

**Comment by monicacecilia** [comment]
Thanks @cmungall  I'll update the user and let her know of that the conversation has moved here.

**Comment by kltm** [comment]
If there is no further contact with the user, we may as well close this for now.
