### ISSUE TITLE
Can filenames use the same pattern?

### ISSUE THREAD

**Issue by julie-sullivan** [geneontology/helpdesk#10]
All (gene association) filenames have the same pattern for their name:

```gene_association.[SPECIES|ORG].gz```

Except for the ones from the EBI. Can they all use the same pattern instead? Or is there a specific reason for the difference? It would make my life a lot easier! :)

Thanks!

**Comment by cmungall** [comment]
Hi @julie-sullivan - sorry about this. We may move to the EBI pattern in the future, but we want to avoid people hardcoding assumptions about naming conventions.

Would it make your life easier if the GO released something like a download script, or a TSV or JSON file with an entry for each file, plus metadata?

**Comment by julie-sullivan** [comment]
Yes, that would be great! :)

**Comment by kltm** [comment]
@cmungall I was wondering if there was an external ticket or further action on this item?

**Comment by kltm** [comment]
Closing from inactivity.

**Comment by cmungall** [comment]
Our new pipeline will be finished soon, filenames will be consistent, we'll have json soon
