### ISSUE TITLE
List of children of 'primary metabolic process' (GO:0044238)

### ISSUE THREAD

**Issue by Isagbrls** [geneontology/helpdesk#101]
Hi, 

I was wondering if it is possible to retrieve a complete list of all GO-terms associated with the parent GO-term 'primary metabolic process' (GO:0044238). 

Thank you in advance!

**Comment by kltm** [comment]
@Isagbrls 

Our apologies for the slow reply.

To clarify, you're looking for *all* children of a particular term?

**Comment by suzialeksander** [comment]
@Isagbrls Hi, did you still need this information? If you do, please let us know. Thanks.

**Comment by suzialeksander** [comment]
Closing due to lack of info
