### ISSUE TITLE
Nocuta new user permissions

### ISSUE THREAD

**Issue by suzialeksander** [geneontology/helpdesk#104]
Hi,

We'd like to add Patrick Ng and Barbara Dunn to the Noctua curation team at SGD.  They'll update this when they have joined GitHub and filled out the new user form.  

@srengel

**Comment by kltm** [comment]
Ideally, they could just be added with a PR to the users file:
https://github.com/geneontology/go-site/blob/master/metadata/users.yaml
Any mistakes will be caught when the PR is tested and reviewed.

**Comment by suzialeksander** [comment]
Should I just add the fields I know (name, orchid, etc.)  and omit adding an email? Neither of them are in the file already.

**Comment by kltm** [comment]
Email is not needed. Paul Sternberg at the bottom there is a good example.

**Comment by suzialeksander** [comment]
OK perfect. I'll add them.  Thanks!

**Comment by cmungall** [comment]
is the SOP still as in http://wiki.geneontology.org/index.php/Noctua#Setup

or should we change so people just go straight for the PR?

**Comment by kltm** [comment]
The PRs are/were considered too "technical" for most people, hence the form, which was put into place when tons of people were trying to join and giving wrong or partial information. The direct PRs have always been encouraged (and appreciated).

**Comment by kltm** [comment]
Note: https://github.com/geneontology/go-site/blob/master/documentation/application-logins.md

**Comment by cmungall** [comment]
Thanks! Added to the noctua tech stack docs
