### ISSUE TITLE
SGD annotated genes mis-represented in AmiGO (GO term merge issue)

### ISSUE THREAD

**Issue by ValWood** [geneontology/helpdesk#105]
~When I use GO term mapper (Princeton)  I get:
These 4 identifiers were found to be unannotated: YGR106C YMR100W YOL054W YOR137C
however these are all annotated in SGD
YMR100W  ubiquitin-dependent protein catabolic process
YGR106C cellular protein-containing complex assembly
YOL054W ubiquitin-dependent protein catabolic process
YOR137C   proton transmembrane transport~
(irrelevent to this ticket)

YGR106C (VOA1) has this in AmiGO:

![voa1](https://user-images.githubusercontent.com/7359272/37246930-662acbb8-24aa-11e8-87d3-4fe5c4c12127.jpg)

GO:0043623 is a secondary ID, so this should have merged into the new term?

**Comment by ValWood** [comment]
similar situation with MUG1

![mug1](https://user-images.githubusercontent.com/7359272/37246935-ae745df8-24aa-11e8-8c99-1ac300eaa923.jpg)

**Comment by Antonialock** [comment]
I have 4 human genes (Q9Y485, Q8TDJ6, Q8N5M1, Q3ZAQ7) that don't slim to 
GO:0006461 (secondary ID for GO:0065003) protein-containing complex assembly

they are annotated to proton-transporting two-sector ATPase complex assembly

**Comment by ValWood** [comment]
this may be a different issue
as they aren't directly annotated to protein-containing complex assembly
https://www.ebi.ac.uk/QuickGO/term/GO:0070071
and the parentage is correct...

**Comment by kltm** [comment]
@ValWood I'm unclear on the origin of the issue at hand (e.g. pipeline filtering or upstream sources).

**Comment by cmungall** [comment]
We flagged the annotation to the alt_id in the report for the release that you were looking at on Mar 10 when you made the screenshot:

http://release.geneontology.org/2018-03-06/reports/sgd.report.md 

@dougli1sqrd is looking at why the switch from GO:0043623->GO:0034622 didn't happen.

I think the 4 gene products were always in amigo, so I think the remained for of the ticket pertains to the princeton tool?

**Comment by ValWood** [comment]
Yes I thought there was a connection, but  they were 2 independent issues. So this ticket is only about  the primary/secondary ID.

**Comment by ValWood** [comment]
Actually, this IS the cause of the Princeton issue.
These 4 genes are only annotated to  a process via an "alternative ID" which should be remapped to the main ID.  I think this is why the Princeton GO term Mapper tool is not recognising them as being annotated. Its a good example of the knock on effect on external tools....

**Comment by suzialeksander** [comment]
Asking @srengel if this has anything to do with SGD

**Comment by ValWood** [comment]
It's now fixed in AmiGO
http://amigo.geneontology.org/amigo/gene_product/SGD:S000004706
It wasn't an SGD problem
it was because the GO secondary IDs were still being used...
Now its
http://amigo.geneontology.org/amigo/term/GO:0006511
