### ISSUE TITLE
GO download filtered for human only

### ISSUE THREAD

**Issue by rhaesler** [geneontology/helpdesk#108]
Dear helpdesk,
for a local enrichment analysis, I need to download a full list of GO-Terms and associated genes, LIMITED to human biological processes. Is there an easy way of how to achieve this?
cheers,

Rob

**Comment by kltm** [comment]
@rhaesler 

Thank you for contacting the GO Helpdesk.

Depending on what you want to do, a simple approach might be to download the GAFs for the organisms/resources that you're interested in (e.g.http://geneontology.org/gene-associations/goa_human.gaf.gz) and filter on the "aspect" field.

For example:
```
zcat goa_human.gaf.gz | grep -P "\tF\t"
```
To get a uniq list of terms then:
```
zcat goa_human.gaf.gz | grep -P "\tF\t" | cut -f 5 | sort | uniq
```
An explanation of the GAF 2.1 fields can be found here: http://geneontology.org/page/go-annotation-file-gaf-format-21

I'm also going to tag @cmungall to see if there might be another easy approach for your use case. If something doesn't work with the above, let me know.

**Comment by rhaesler** [comment]
Thank you very much for your response.
Maybe I need to rephrase the isse. When using the human GO biological process, I still can get hits for "Chloroplast" which shouldnt be there in humans - how can I avoid that?

cheers,
Rob

**Comment by kltm** [comment]
Hm. Can you give the example where you are running into this and the steps to reproduce?
For example, if I'm in AmiGO, I can filter annotations for biological_process and human:
http://amigo.geneontology.org/amigo/search/annotation?q=*:*&fq=taxon_subset_closure_label:%22Homo%20sapiens%22&fq=aspect:%22P%22&sfq=document_category:%22annotation%22
http://amigo.geneontology.org/amigo/search/annotation?q=*:*&fq=taxon_subset_closure_label:%22Homo%20sapiens%22&fq=aspect:%22P%22&sfq=document_category:%22annotation%22
and I'm unable to find annotations to chloroplast (although I may be missing them).

**Comment by rhaesler** [comment]
Thank you very much for looking into this issue.
My problem still remains, seems I wasn't able to phrase it properly:
is there a way to identify "biological processes" that are unique to plants (or others) in the field "subset"? So I can eliminate those.

Our problem is, when zooming in on a gene, we want to see its entire ontology path, including the parental terms, however, moving up the path can result in finding non-human (e.g. plant) terms.

**Comment by suzialeksander** [comment]
Hi @rhaesler, did you find a solution to this issue?  If not, can you list the steps you took so I can recreate the results list you have, and let me know what result(s) you are questioning?  I think this will be the easiest way to see what the problem is. 

Thanks!

**Comment by rhaesler** [comment]
Dear GO-Helpdesk,

 

unfortunately, I didnt find a solution yet. I keep getting non-human hits within the human gene ontology.

 

Kind regards,

 

Robert

 

____________________________________________

 

Dr. Robert Haesler

Institute of Clinical Molecular Biology

Christian-Albrechts-University Kiel

University Hospital Schleswig Holstein, Campus Kiel Rosalind-Franklin-Straße 12 · 24105 Kiel, Germany Delivery address: Am Botanischen Garten 11, 24118 Kiel

Fon: +49 (0) 431 500 15139  ·  Fax: +49 (0) 431 500 15178

www.ikmb.uni-kiel.de

**Comment by suzialeksander** [comment]
@rhaesler, Can you please: 

- [ ]  detail the exact steps you took so I can recreate the results list you have

- [ ]  list SPECIFICALLY what result(s) you are questioning

Without this information I can't resolve this issue.  Thanks.

**Comment by rhaesler** [comment]
Hi,

we associate gene symbols with GO-terms (goa_human.gaf), then we take those GO-terms and look at all ancestor terms in the ontology tree, up to level one. When we do this we also reach GO-terms which are associated with “Chloroplast” (as example).

For example:

If you look in AmiGO for GO:1990904 it is associated with Organism: Homo sapiens.

If you don’t filter for Homo sapiens, but filter for GO class (use the “more” button), you can find chloroplast terms.

Those terms will be included in our results, because we are not excluding terms without direct gene association, we are looking at all GO terms associated with GO terms with a human gene association.

 

Is there a way to identifiy GO-terms that are (not) related to human without gene-associations? So we can exclude certain branches or single terms from the ontology tree for our analysis.

 

Kind regards,

Lars Kraemer

**Comment by kltm** [comment]
@rhaesler 

GO:1990904 ("ribonucleoprotein complex" in cellular_component) is a fairly "high-level" term, with a lot of transitive annotations to it from a large number of species, including humans and green plants. For example, an annotation to RPS8 with term "chloroplast ribosome" would transitively include the term "ribonucleoprotein complex", which is to be expected.

Within the ontology itself, while not widely referenced in our public interfaces, we have things like `only_in_taxon` and `never_in_taxon` that could be used as input into what you're doing to help in the filtering of terms that truly should (not) have annotations to them from gene products in the given taxon.
For example, see: https://github.com/geneontology/go-ontology/blob/master/src/ontology/go-edit.obo

tagging @cmungall

**Comment by cmungall** [comment]
To get the taxon links use go-plus, for download URLs see http://geneontology.org/page/download-ontology

However, in general this should not be required. We should not have annotations of vertebrate genes to chloroplast! @rhaesler has found a hopefully rare problem in the annotations. I have reported this (https://github.com/geneontology/go-site/issues/660) and this should be fixed in the next release

I am very sorry about this. @rhaesler I would still recommend you write your tool without doing any additional processing, and assume annotation correctness, treating this as a one-off issue (I am curious: is there a reason for writing your own tool vs using an existing library or web interface).

**Comment by suzialeksander** [comment]
@rhaesler, has this been resolved?

**Comment by kltm** [comment]
Note to @suzialeksander and @cmungall that this issue is still open:
https://github.com/geneontology/go-site/issues/660
Let's go ahead and just track the issue there.
