### ISSUE TITLE
GO enrichment analysis for non-model species: how do you proceed without selecting a species on the list?

### ISSUE THREAD

**Issue by lsirot** [geneontology/helpdesk#109]
Hi,
I have been trying to follow the instructions on [this site](http://www.geneontology.org/faq/how-can-i-do-term-enrichment-analysis-species-not-present-list-amigo) for how to use PANTHER to conduct GO enrichment analysis for a non-model species. I am uploading my own lists of regulated and reference genes. These lists contain ids for the best BLAST hits from a number of different species. The ids are all ones supported by PANTHER. But, I cannot figure out how to proceed from the [initial page ](http://pantherdb.org/)without selecting one of the species in the select organism list. The problem is that if I select a species, then the analysis only works for ids that are from that selected species.  Is there a way to proceed without selecting a species for the enriched and the reference lists?
Thank you.

**Comment by kltm** [comment]
@huaiyumi @mugitty 
Would you have any advice for this user?

**Comment by suzialeksander** [comment]
@huaiyumi, trying to assign only you to see if you get a more direct email

**Comment by huaiyumi** [comment]
The test requires a reference list, which can be defined by selecting a species. Alternatively, you can choose to upload your own reference list, then you don't need to select a species.

**Comment by suzialeksander** [comment]
@lsirot, I hope this clears thing up.  If you still have questions please open a new ticket.  Thank you for contacting GO.
