### ISSUE TITLE
No connection to Enrichment analysis

### ISSUE THREAD

**Issue by elliefewings** [geneontology/helpdesk#11]
I have been unable to access the GO enrichment analysis tool online since mid last week. I am able to browse the site but any search for terms times out with the error that pantherdb.org has no response. It actually looks as though the whole panther site is down. I have been looking on your twitter feed for any service notifications but have seen none. On top of this I am also unable to access your status page. I wonder if this issue is being fixed and whether you know how long it will take to be back up and running?
Thanks!

**Comment by kltm** [comment]
@elliefewings 

From our logs, PANTHER started getting spotty around 5:30am. It seems to have been reset now, so please let us know if you are still having trouble.

The status page  is now also working as well, after a brief (and I believe unrelated) outage with that service provider.
