### ISSUE TITLE
GO old releases in BioPortal

### ISSUE THREAD

**Issue by cirillodavide** [geneontology/helpdesk#110]
I cannot find GO release 2013-07-01 at https://bioportal.bioontology.org/ontologies/GO

That release is instead available at ftp://ftp.geneontology.org/pub/go/ontology-archive/

Thanks in advance for clarifying.
Davide Cirillo

**Comment by kltm** [comment]
@cirillodavide 
As far as I know, we currently have no release procedure with BioPortal, so I would not consider that information canonical.
@cmungall would you know the best location to get historical ontologies? Would that be the repo, or is there another archive?

**Comment by cmungall** [comment]
You can get this release from it's PURL:

 * http://purl.obolibrary.org/obo/go/releases/2013-07-01/go.obo
 * http://purl.obolibrary.org/obo/go/releases/2013-07-01/go.owl

Every release of GO should have the version in it. This is very explicit in the OWL, it uses the standard versionIRI property like this:

```
        <owl:versionIRI rdf:resource="http://purl.obolibrary.org/obo/go/2013-06-29/go.owl"/>
```

The version should always be resolvable

with the obo it's a bit less explicit but it is still deterministic. You will see

```
data-version: 2013-06-29
```

in the header - you can make a PURL like `http://purl.obolibrary.org/obo/go/releases/` + VersionID + `/go.obo`

BioPortal is not necessarily in sync. We are working with @graybeal and others at bioportal to synchronize this across all OBO ontologies (related ticket: https://github.com/OBOFoundry/OBOFoundry.github.io/issues/80). You should follow up with bioportal with any specific question.

(go folks, we should have the version docs in the FAQ)
