### ISSUE TITLE
[Questions about the results of the enrichGo()]More genes are involved but less biological activity.

### ISSUE THREAD

**Issue by chriszhuge** [geneontology/helpdesk#111]
I downloaded the gene mutation table for breast cancer patients and ranked them according to the mutation frequency of the genes.

The first 885 genes in the database (with a mutation frequency greater than or equal to 3) were analyzed with enrichGO() to obtain 144 results for participating in biological activities.

The first 348 genes in the database (with a mutation frequency greater than or equal to 4) were analyzed with enrichGO() to obtain the results of 173 biological activities.

But the first 885 genes contained the first 348 genes. Why did they get less results than using the first 348 genes?

The following code：
```
gene <- read.table("morethan3.txt",colClasses = "character")
gene<-as.character(gene[,1])
ego <- enrichGO(gene = gene, OrgDb = org.Hs.eg.db,
                ont = "BP", pAdjustMethod = "BH",
                pvalueCutoff = 0.05, qvalueCutoff = 0.05)
ego_10<-as.data.frame(ego)
write.csv(ego_10,file = "./ego_3_0.05_0.05.csv", row.names = F)

gene <- read.table("morethan4.txt",colClasses = "character")
gene<-as.character(gene[,1])
ego <- enrichGO(gene = gene, OrgDb = org.Hs.eg.db,
                ont = "BP", pAdjustMethod = "BH",
                pvalueCutoff = 0.05, qvalueCutoff = 0.05)
ego_10<-as.data.frame(ego)
write.csv(ego_10,file = "./ego_4_0.05_0.05.csv", row.names = F)
```

in  file morethan3.txt,the data is:
[morethan3.txt](https://github.com/chriszhuge/enrich/blob/master/morethan3.txt)
and the result is ：
[ego_3_0.05_0.05.csv](https://github.com/chriszhuge/enrich/blob/master/ego_3_0.05_0.05.csv)

in  file morethan4.txt,the data is:
[morethan4.txt](https://github.com/chriszhuge/enrich/blob/master/morethan4.txt)
and the result is ：
[ego_4_0.05_0.05.csv](https://github.com/chriszhuge/enrich/blob/master/ego_4_0.05_0.05.csv)

**Comment by kltm** [comment]
@chriszhuge 

If I'm following your question correctly, this is a question concerning the `enrichGO` package. That is not a software package from the GOC, so we would be unable to offer any support and would suggest that you contact the package's maintainer.

**Comment by suzialeksander** [comment]
Hi @chriszhuge, I'm closing this ticket because `enrichGO` would best be able to help you.  If you have any more issues we can help you with, please open a new ticket.

Thank you for contacting GO.
