### ISSUE TITLE
PAINT annotations do not use the correct primary name in GAF field for DB object symbol

### ISSUE THREAD

**Issue by ValWood** [geneontology/helpdesk#112]
A message from GO term finder:

Hi Val,

With our GOTermFinder, we are getting errors like this for Pombase:

WARNING: databaseId SPAC1A6.10 maps to more than one standard name : tcd1 ; SPAC1A6.10

There are actually hundreds of these. Since they happen at the annotation parsing phase, they affect every job using the Pombase annotation, and (until today) prevented GOTermFinder from completing. I'm not sure how long it has been happening.

For the above, the annotation contains:

PomBase    SPAC1A6.10    tcd1        GO:0061504 GO_REF:0000024    ISO    SGD:S000001045    P    tRNA threonylcarbamoyladenosine dehydratase Tcd1 (predicted) SPAC30D11.15c    protein    taxon:4896    20150210Pombase

PomBase    SPAC1A6.10    SPAC1A6.10        GO:0061504 PAINT_REF:43267    IBA    PANTHER:PTN001333297    P    tRNA threonylcarbamoyladenosine dehydratase UniProtKB:O13861|PTN001333303    protein    taxon:284812 20170427    GO_Central

I've made some changes so that these warnings don't cause the jobs to abort, but I'm not sure how best to actually fix it. The GO-TermFinder module expects there to be a one-to-one mapping of common name to database ID. Although it might be possible to change the logic, there may be a reason (although I don't see anything in the GAF format documentation that requires it). As far as I know, Pombase is the only annotation that does this.

From our perspective, a good fix may be problematic. At least, a quick look over the code doesn't bring anything to mind. Also anyone else using the module from CPAN will have the same errors.

I wanted to let you know that this was happening. Also, I was wondering, what is the distinction between these annotations such that tcd1 is not the common name for both?

Thanks,

Mark

**Comment by ValWood** [comment]
This refers to filed 2, should be the gene object symbol.
3 | DB Object Symbol | required | 1 | PHO3

This issue will go away once PomBase imports the PAINT annotations, because we will output them with  the correct IDs, but this won't happen until these   pre import checks are addressed:

https://github.com/geneontology/go-annotation/issues/1873

and final checks have been made for biological consistency.

 It seems important for CPAN users that the correct primary ID is used here....

Thanks,

Val

**Comment by ValWood** [comment]
Having these annotations in GO term finder will be problematic for me for  a few projects/analyses  (1, for a paper on unknowns we will be submitting shortly, 2. For the matrix project  we hope to finalize next )...will also cause problems for our users performing enrichment  and slims with GO term mapper and slimmer.  Could also cause problems for  exercises for a WT workshop where we  are currently preparing.....

**Comment by huaiyumi** [comment]
I don't think this is an issue with PAINT annotations being outdated. I looked at the example in Val's message. The current release still uses the same id (SPAC1A6.10). The issue won't be resolved by updating the GAF file.

**Comment by huaiyumi** [comment]
Or does it mean that gene symbols should be used as the primary ID for the pombase GAF? For PAINT GAFs, MOD gene IDs are used as the primary ID by default. Is there any documentation that we can follow when we generate GAFs for the MODs?

**Comment by ValWood** [comment]
Hi @huaiyumi 
Yes that's the issue:

primary symbol is tcd1
PomBase SPAC1A6.10 tcd1 

this clashes with the PAINT export and GO term finder/mapper expect this to be unique:
PomBase SPAC1A6.10 SPAC1A6.10

Although for now, I would prefer the PomBase PAINT annotations did not go into  AmiGO, until
I have finished sanity checking.
There are quite a few annotation issues reported, and it is affecting some analyses...
https://github.com/geneontology/go-annotation/issues?q=is%3Aissue+is%3Aopen+label%3A%22PAINT+annotation%22

**Comment by ValWood** [comment]
This is what it looked like after I finished the clean up

![clean up](https://user-images.githubusercontent.com/7359272/38351330-d6f10d98-38a6-11e8-823e-5aaa8340a389.jpg)

This is what it looks like with the PAINT annotation:

![matrix](https://user-images.githubusercontent.com/7359272/38351363-ff81a772-38a6-11e8-953a-4ce226190679.jpg)

**Comment by huaiyumi** [comment]
Hi @ValWood ,
I have to relay the issue to Maria at Reference Proteome. We use their data to build PANTHER database. The symbols were not in their dataset that was used to build the current version of PANTHER. Not sure if they will update it in this year's release. Bottom line, we are not able to fix this problem until RP fixes it.

**Comment by cmungall** [comment]
Thanks for the update Huaiyu.

If this can't be fixed at PANTHER, we will fix this in GO Central when the annotations are merged in.

This ticket tracks the work to be done here: https://github.com/geneontology/go-site/issues/591

We can close this ticket when that is done

**Comment by ValWood** [comment]
I would prefer if you did not  include the pombe data in Amigo Until the issues reported here:
https://github.com/geneontology/go-annotation/issues?q=is%3Aissue+is%3Aopen+label%3A%22PAINT+annotation%22

are fixed.

This is why we did not import them into PomBase yet. When we import into PomBase, we will export with the correct identifiers for downstream softwares.

We are using GO term finder /mapper for  analyses (as do our community), and currently the 
PAINT annotations are  'contaminating' the analyses.

We would not lose very much by excluding because most of the approved annotations are redundant. See also
https://github.com/geneontology/go-annotation/issues/1879

**Comment by cmungall** [comment]
Hi Val, I opened a ticket for your request here: https://github.com/geneontology/go-site/issues/597

**Comment by dustine32** [comment]
Hi @ValWood we've uploaded the fixed paint_pombase.gaf.gz file to the panther FTP [server](ftp://ftp.pantherdb.org/downloads/paint/presubmission/). Does the pipeline need to run again for the changes to flow to where you can use them?

**Comment by kltm** [comment]
Unless something is done otherwise: `snapshot` every 24hr; `release`/`current` every month.

**Comment by ValWood** [comment]
I can't remember where I get the file from, can you remind me.
I expected it to be here but I don't see it.
http://build.berkeleybop.org/view/GAF/job/gaf-check-pombase/

We are still waiting for lots of annotation and PAINT family fixes though. @pgaudet  opened this yesterday.
https://github.com/geneontology/go-ontology/issues/15657

Will this be fixed, can you tell?

**Comment by dustine32** [comment]
@ValWood I think the most up-to-date location of gene_association.pombase.gz is here:
http://geneontology.org/gene-associations/

@kltm @selewis does this sound right?

When the monthly pipeline release runs it should pull the fixed PAINT pombase file from the Panther FTP site and update this file.

**Comment by ValWood** [comment]
Ah, OK so you put then directly into the PomBase gaf. That's  what I would prefer not to happen.
We would like to import the PAINT files, and  QC them remove redundancy, incorrect families, taxon violations, curation, annotations from indirect phenotypes...now we need to extract the PAINT annotations  out of the file we created.

This means also that PomBase and AmiGO will never show the same data.

@cmungall  does it really need to happen this way? 

Note that I am reporting all the errors, but there will always be time lags in fixing and propagation......

**Comment by pgaudet** [comment]
Hi @ValWood 

Do we always want to filter redundant data ? Isn't it nice to have confirmation from several methods ? (Maybe that's what pombase wants to do, but maybe not GOC?) I think we need to discuss this (and improve the display for redundant annotations).

**Comment by pgaudet** [comment]
@ValWood 

One the gene name issue - I have no idea whether this is related, but @huaiyumi mentioned that gene names are obtained from the UniProt reference proteomes. I don't know how this gets reprocessed in the GO database (ideally as much information as possible would be resynchronized from some central database - gene names, term labels, ...) 

Anyhow - is pombase up to date in the Reference proteomes ? 

Thanks, Pascale

**Comment by ValWood** [comment]
> One the gene name issue - I have no idea whether this is related...

I don't think it was likely to be caused by the same issue. All of the  systematic IDs were present. This was a downstream issue with the GO Term Finder because the  gene symbol field was not correctly populated. But I don't think this was preventing  the data from getting into AmiGO.
(there was a problem that the data  the the EBI were using was out of date, but  @huaiyumi 
has implemented a work around for that problem).

**Comment by ValWood** [comment]
So for example 4 annotations, which are all *ultimately * the same source:
The experiment is in S. cerevisiae, and  the pombe gene will complement the loss (IGI heterologous complementation)
The other 2 are superflouos.

https://user-images.githubusercontent.com/7359272/38295209-27f0c2dc-37e5-11e8-9b3d-25d7a7e0dd59.jpg

**Comment by ValWood** [comment]
actually that's not a great example...

**Comment by ValWood** [comment]
The recent segue was about  filtering annotation redundancy more generally. We should discuss this at the GO meeting...
This could be partially (but not entirely) addressed by different annotation display. We do both at PomBase.  There are lots of benefits  of doing this, for users, curators and especially for QC.
Go might not wish to implement everything PomBase has done here, but should definitely   look at  what the options are, and have a plan ...otherwise much annotation is unuseable.

PARK7 for example has 279 annotations  spreading over 12 pages in QuickGO. Users cannot possibly easily  find terms which might be important  of interest. GO isn't only used for enrichment type analysis, lots of people are interested in single gene products too!

@pgaudet  could this be an agenda item?

**Comment by suzialeksander** [comment]
@ValWood @pgaudet Have all the issues here been addressed in other tickets? I'd like to close the helpdesk ticket if so, but want to check first as this ticket has been pretty busy. I think all the tickets mentioned have been closed except 

Redundant annotations accumulating: geneontology/go-annotation/issues/1879

Consider not merging/injecting PAINT files from some groups: geneontology/go-site/issues/597

**Comment by ValWood** [comment]
This was primarily about PAnther not using the correct IDs, so if that is fixed, this can be closed.
v

**Comment by suzialeksander** [comment]
Great, it seems like @dustine32 solved this in April.  I'm assuming the problem has been fixed. Please re-open if you still see the wrong primary names.

Thanks!

**Comment by selewis** [comment]
@Huaiyu Mi <huaiyumi@usc.edu> or @Paul D Thomas <pdthomas@usc.edu> are the
ones who need to answer this.

**Comment by suzialeksander** [comment]
Ok, I'll wait to hear from them. Thanks!

**Comment by dustine32** [comment]
I can answer for the PAINT GAF generation pipeline that we're currently checking the PomBase gene symbols and descriptions against the lookup files provided from these URLs:

ftp://ftp.pombase.org/nightly_update/misc/allNames.tsv
ftp://ftp.pombase.org/nightly_update/misc/sysID2product.tsv

...and fixing the GAF lines if they're incorrect. So it should be fixed for now. But this is still a "semi-manual" step (we gotta remember to run the script) so let us know if you do see this issue popping up again.

**Comment by selewis** [comment]
Thanks Dustin, that's what I was guessing you'd done. More a temporary
patch than a long-term fix. That can only come when the reference proteomes
from UniProt accurately reflect what PomBase/Val specify, and then the
PANTHER trees are rebuilt from these.

Do you (or anyone) know if the latest UniProt reference proteomes are fixed
now? And when the next PANTHER build will be?

**Comment by dustine32** [comment]
@selewis I'm starting on the newest PANTHER build right now and it sounds like it'll take a few months. I believe that, even though UniProt's fixed the symbols on their end, the ref prot data (released April 2018) used for the build still has the wrong mappings.

We'll just take the same approach for fixing these symbols during the build (of course, next reference proteome release should have these fixed).

**Comment by huaiyumi** [comment]
I think this was long resolved before. I am not sure why it was reopened again.
