### ISSUE TITLE
Annotation of localization for Chlamydia proteins

### ISSUE THREAD

**Issue by andrewsu** [geneontology/helpdesk#113]
In the context of a wikidata-backed project called Chlambase, we would like to annotate the localization of a set of Chlamydia proteins to various compartments in the host and in the inclusion body (which is the nucleus-sized structure indicated by the red arrow):

![2018-04-02_15-24-13](https://user-images.githubusercontent.com/2635409/38282391-ae7c2e62-3764-11e8-959c-07b48ccf01db.png)

This table summarizes the localizations that our domain expert (@khybiske) has identified with example genes and references.  We've also listed our best guess GO term with our confidence level in that guess.

Localization | Example Chlamydia Gene ID | Supporting PMID | Best guess GO | confidence level
-- | -- | -- | -- | --
host actin cytoskeleton | CT456 | [15199184 ](https://www.ncbi.nlm.nih.gov/pubmed/15199184 )| [GO_0005884 ](https://www.ebi.ac.uk/ols/ontologies/go/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FGO_0005884 ) or [GO_0044163](https://www.ebi.ac.uk/ols/ontologies/go/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FGO_0044163)| low
inclusion lumen | CT049 | [18591235 ](https://www.ncbi.nlm.nih.gov/pubmed/18591235)| [GO_0020004 ](https://www.ebi.ac.uk/ols/ontologies/go/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FGO_0020004 ) or [GO_0043665 ](https://www.ebi.ac.uk/ols/ontologies/go/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FGO_0043665 )| low
inclusion membrane | CT005 | [26416906 ](https://www.ncbi.nlm.nih.gov/pubmed/26416906 )| [GO_0020005 ](https://www.ebi.ac.uk/ols/ontologies/go/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FGO_0020005 ) or [GO_0043664 ](https://www.ebi.ac.uk/ols/ontologies/go/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FGO_0043664 )| low
host cell nucleus | CT737 | [20657819 ](https://www.ncbi.nlm.nih.gov/pubmed/20657819 )| [GO_0042025 ](https://www.ebi.ac.uk/ols/ontologies/go/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FGO_0042025 )| high
host cell cytosol | CT858 | [20522495 ](https://www.ncbi.nlm.nih.gov/pubmed/20522495 )| [GO_0044164 ](https://www.ebi.ac.uk/ols/ontologies/go/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FGO_0044164 )| high
host lipid droplets | CT163 | [16920627 ](https://www.ncbi.nlm.nih.gov/pubmed/16920627)| [GO_0044186 ](https://www.ebi.ac.uk/ols/ontologies/go/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FGO_0044186 )| high
host cell plasma membrane | CT867 | [16824101 ](https://www.ncbi.nlm.nih.gov/pubmed/16824101 )| [GO_0020002 ](https://www.ebi.ac.uk/ols/ontologies/go/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FGO_0020002 )| high

And although we don't have any examples right at this moment, we will also be wanting to annotate Chlamydia proteins that localize to the host cell versions of peroxisome ([GO_0005777](https://www.ebi.ac.uk/ols/ontologies/go/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FGO_0005777)), ER body ([GO_0010168](https://www.ebi.ac.uk/ols/ontologies/go/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FGO_0010168)), and centrosome ([GO_0005813](https://www.ebi.ac.uk/ols/ontologies/go/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FGO_0005813)).

Does anyone have input on these mappings, particularly if there are better mappings or cases where new GO terms could/should be created?

for slightly more info/context: https://github.com/SuLab/ChlamBase.org/issues/34
cc team members: @khybiske @putmantime @djow2019

**Comment by kltm** [comment]
@vanaukenk @pgaudet @ukemi 
I'm not sure who within our group would be the best contact for this--would any of you have any ideas for the best person to loop in?

**Comment by suzialeksander** [comment]
@vanaukenk @pgaudet @ukemi 
Would any of you happen to know the right contact person for this.

**Comment by vanaukenk** [comment]
@suzialeksander @kltm 
I think some of the relevant term requests are appearing in the ontology tracker and are being dealt with there:
https://github.com/geneontology/go-ontology/issues/15548
https://github.com/geneontology/go-ontology/issues/15547
For annotation, @suzialeksander may need to follow up to see if/what additional help is needed.

**Comment by andrewsu** [comment]
Thank you all for the pointers and follow up.  As noted, @djow2019 successfully requested two term creations for `host cell centrosome` and `host cell peroxisome`.  For similar cases, we'll follow that process again.  

I was originally concerned about how to handle `inclusion membrane` and `inclusion lumen`, since those seemed different somehow.  But since writing and rewriting this comment multiple times, I think it makes sense just to follow the same pattern as above and request creation of `host inclusion body` with `has_part` children `host inclusion body membrane` and `host inclusion body lumen`.

Closing this issue then, but if anyone has more insight or guidance that might change how we are approaching this, please let us know.  Thanks!
