### ISSUE TITLE
Invitation to participate in a Genomic Terminology Standards survey

### ISSUE THREAD

**Issue by GloriaGonzalez** [geneontology/helpdesk#114]
To whom may concern, 

Request for your input into a project being undertaken for NHS Digital in England.

I am one of the consultants as Bitac [http://bitac.com/?lang=en], a terminology service company based in Barcelona.

Currently we are undertaking a consultancy project for NHS Digital in England titled “A survey of current standard vocabularies supporting genetic, genomics and research” and we would greatly value your participation in the survey we are undertaking, including a telephone interview to enable us to clarify details relating to specific vocabularies. 

We have developed a survey to evaluate the existing terminologies/controlled vocabularies to support clinical genomics, and in parallel a survey for the users of these terminologies.

We understand that you are a member of the team that develops Disease Ontology, and this is one of the products that we are particularly interested in.

If you would be interested in participating in this work, then please contact us by response to this email
ggonzalez@bitac.com

Best regards

**Comment by kltm** [comment]
@vanaukenk @pgaudet @ukemi 
If interested, could one of you please either follow up or pass this on to somebody who could follow up?

**Comment by cmungall** [comment]
Hi Gloria

You have contacted the Gene Ontology (GO) helpdesk. We can answer questions pertaining to the applicability of the GO in genomics research. I am sure you know already, but the GO is widely used in genomics for functional annotation of genes in humans and other model organisms. Although the GO is primarily used in basic research and molecular biology, it is increasingly used in clinical contexts, which is where I assume your interests lie. For example, to assist in the interpretation of the results of variant prioritization pipelines, understanding the normal function of the gene (and the function or orthologous genes) is vital. Some variant prioritization pipelines use GO in an automated fashion as part of filtering (although I am answering mostly with my GO hat I'm also involved in these other efforts). Another example of a clinical application of GO was this recent widely publicized paper describing a transgenic replacement skin for a patient with a severe rare disease https://www.nature.com/articles/nature24487 - GO was used to check the metastatic potential of off-target mutations prior to transplant. These are just some examples. As genomics becomes more central to clinical care, the more relevance and applications there will be for the GO, so I hope it features prominently in your report.

You asked about the Disease Ontology. This is a separate ontology from the GO. There are a number of different disease ontologies/vocabularies/lists, I assume you are familiar with these (Orphanet, NCIT, OMIM, DO, MESH, ICD9/10/11). I am also a developer on the MONDO disease ontology that aims to unify these: http://obofoundry.org/ontology/mondo.html - I can answer separate questions about this outside this tracker: cjmungall@lbl.gov

You may also find other open ontologies of interest here: http://obofoundry.org/ -- one of the goals of OBO is to unify multiple separate ontologies into a unified framework (GO is part of this), you may want to also ask your question on the obo-discuss mail list.

**Comment by cmungall** [comment]
Gloria answered, I am having a call with Bitac Wednesday 18th 9am pacific time (3pm Spanish time)
