### ISSUE TITLE
Page not found when trying to obtain results

### ISSUE THREAD

**Issue by contessaricci** [geneontology/helpdesk#115]
Hello,
I have been trying to collect accession numbers associated with the gene ontology terms for my sequences of interest, however, I keep receiving a page not found error. Is there an issue with your server at the moment?

**Comment by cmungall** [comment]
Thanks, we are investigating the outage and hope to have it up soon

**Comment by kltm** [comment]
If this is in reference to http://amigo.geneontology.org, the balancer seems to have recovered.
