### ISSUE TITLE
GO data anomalies: synonyms, deprecated IDs, typos

### ISSUE THREAD

**Issue by chrish00** [geneontology/helpdesk#116]
Hi - I'm reporting a few data anomalies I found in a current version of GO I downloaded. These issues were found in both obo files (full and basic) as well as OWL. 

1) Duplicate synonyms:  

[Term]
id: GO:0015194
name: L-serine transmembrane transporter activity
namespace: molecular_function
alt_id: GO:0015511
alt_id: GO:1905361
def: "Enables the transfer of L-serine from one side of a membrane to the other. L-serine is the L-enantiomer of 2-amino-3-hydroxypropanoic acid." [GOC:ai, GOC:jsg, GOC:mah, GOC:mtg_transport, ISBN:0815340729]
subset: gosubset_prok
synonym: "L-serine permease activity" RELATED []
**synonym: "L-serine transporter activity" BROAD []
synonym: "L-serine transporter activity" RELATED []**
synonym: "serine transporter activity" BROAD []
synonym: "threonine/serine:sodium symporter activity" RELATED []
is_a: GO:0015179 ! L-amino acid transmembrane transporter activity
is_a: GO:0022889 ! serine transmembrane transporter activity
relationship: part_of GO:0015825 ! L-serine transport

2) “Consider” pointers to deprecated GO IDs:    Normally the “consider” tag points to a current ID:

GO:0001071
GO:0005487
GO:0006461
GO:0015246
GO:0015542
GO:0015563
GO:0015992
GO:0030529
GO:0051183

**Comment by kltm** [comment]
@cmungall 
Would you happen to understand the source of this?

**Comment by chrish00** [comment]
Wanted to report a couple of typos as well. These are currently present in the go.obo file:

1) id: GO:0102103
name: bisdemethoxycurcumin **syntase** activity
Should this be "synthase"?

2)id: GO:0102560
name: 5-phospho-alpha-D-ribose 1,2-cyclic phosphate 1-**phsophohydrolase** activity
Should this be “phosphohydrolase”?

**Comment by suzialeksander** [comment]
Hi @chrish00,

Yes, we suspect you're correct. Thanks for letting us know.

@cmungall is this something that can be edited easily by you or @dougli1sqrd ?

**Comment by cmungall** [comment]
The ontology group can take care of changes to the ontology. @dougli1sqrd is working on the QC check to stop these leaking out.

**Comment by chrish00** [comment]
Do you have an estimate on when the corrections will be made? I checked the data this morning and the issues are still present.

**Comment by ukemi** [comment]
Fixed the duplicate synonym. 

@hdrabkin, can you look at the id: GO:0102103
name: bisdemethoxycurcumin syntase activity Should this be "synthase" issue. It looks like this might be the wrong name?

@pgaudet can you look at the consider tags? I though we had checked these.

**Comment by hdrabkin** [comment]
I am fixing GO:0102103 in a new ontology ticket.

**Comment by pgaudet** [comment]
I am fixing the obsolete consider: pull request is here: https://github.com/geneontology/go-ontology/pull/15730

Pascale

**Comment by pgaudet** [comment]
My fixes are merged. Are the other problems also fixed?

**Comment by hdrabkin** [comment]
I fixed the : GO:0102103 issue with separate ticket and closed.

**Comment by ukemi** [comment]
I fixed the synonym, which I believe was due to a merge. So I think this ticket has been addressed.

**Comment by suzialeksander** [comment]
Great, thanks everyone for your help.  @chrish00, thank you for letting us know about these issues, if you still see them persist or notice anything else, please open a new ticket.

**Comment by suzialeksander** [comment]
@dougli1sqrd, are the QC checks in place now?

**Comment by suzialeksander** [comment]
@chrish00, all of these issues have been moved to the appropriate trackers.  Thanks again for pointing these issues out, and please open new tickets for any more issues. 
https://github.com/geneontology/go-ontology/issues/15722 
https://github.com/geneontology/go-ontology/issues/13667
https://github.com/geneontology/go-ontology/issues/15735
