### ISSUE TITLE
Documented changes with each GO release?

### ISSUE THREAD

**Issue by lterhune** [geneontology/helpdesk#117]
Hello Github, we were wondering if there is documentation of the annotation changes that occur with each GO release. We've just noticed some changes in our data in PANTHER from a release last year to the current one. I've downloaded the archived GO .gz files but was wondering if the differences were clearly annotated somewhere. thanks!

**Comment by kltm** [comment]
@lterhune 
Would it be possible to get a link for where you got the data that you're working with?
For differences between versions, especially at a year level, the changes in what you're looking at may be large and structural. Historically, annotation versions have been kept in an SVN repo (http://geneontology.org/page/svn-help) and ontology versions are kept in GitHub (https://github.com/geneontology/go-ontology). Depending on your use case, we may be able to recommend different ideas about how to see the difference information that you're interested in. In general though, there is not a centralized summary store of changes throughout the project.

**Comment by suzialeksander** [comment]
Hello @lterhune,

Did you still have this question? We would be happy to look at your data if you let us know where it came from and see if we can give you a more detailed answer.  If this answered your question, did you need any more help?

Thank you!

**Comment by suzialeksander** [comment]
Closing, assume the above reply resolved the issue.  If you still have this question, @lterhune, can you open a new ticket? Thanks!
