### ISSUE TITLE
why go_associations.gene_product.full_name is not a key

### ISSUE THREAD

**Issue by michelegentili93** [geneontology/helpdesk#118]
I've downloaded the homo sapiens annotation file.

Why I have proteins with more ids (go_associations.gene_product.id) and thus a protein with many sets of annotations.

**Example**:
_protein_ :  A1CF
_go_associations.gene_product.id_ : [305058, 324614, 333209]
then for each of the three gene id (that are of the same protein) I have a set of annotations. So which of the three set should I use? The union?

The union give me different results from : (http://amigo.geneontology.org/amigo/search/annotation)?q=A1CF where the go_graph.term.id 8981 is not present

**Comment by suzialeksander** [comment]
Hello, 

Can you provide the locations of the files you're using, and if possible some of the lines of annotations in question? Also, if any of these identifiers have prefixes can you include those.  

Thank you!

**Comment by suzialeksander** [comment]
Hi @michelegentili93, I'm closing this stale issue due to lack of information.  If you still have questions, please open a new ticket with the information requested. Thanks!
