### ISSUE TITLE
Invalid PMIDs in go-basic.obo

### ISSUE THREAD

**Issue by need47** [geneontology/helpdesk#120]
I downloaded the file from [http://purl.obolibrary.org/obo/go/go-basic.obo](http://purl.obolibrary.org/obo/go/go-basic.obo), which contains some invalid PMIDs (NCBI's PubMed identifier). Below is just one example, where the PMIDs look like something prefixed with year (YYYY).

[Term]
id: GO:0099009
name: viral genome circularization
namespace: biological_process
def: "The circularization of a viral genome following infection of a host cell. This is common amongst bacterial viruses to protect the viral genome ends from nucleases, to convert the linear genome to an integrative precursor or to give rise to the replicative form of the genome. It can be mediated by covalent closure of the DNA sticky ends, recombinaison between redundant terminal sequences or via th e binding of a protein at the viral DNA extremities" [PMID:**2011894948**, PMID:**2015489417**, PMID:**2019523475**, PMID:20319596, VZ:3968] xref: VZ:3968
is_a: GO:0016032 ! viral process

**Comment by kltm** [comment]
@vanaukenk @ukemi 
You one of you possibly know where to look for the origin of these PMIDs, or know who might?

**Comment by ukemi** [comment]
https://github.com/geneontology/go-ontology/issues/15561

**Comment by kltm** [comment]
This change should soon propagate out to the public server.

**Comment by need47** [comment]
Thanks for the quick fix. How soon?

**Comment by kltm** [comment]
It should be about 30hrs from now--the pipeline is currently mid-run, the new run will start at midnight.

**Comment by need47** [comment]
Thanks a lot :-)
