### ISSUE TITLE
GO cellular component term for Lymoptoxin LTA LTB LTB Heterotrimer missing

### ISSUE THREAD

**Issue by elmbeech** [geneontology/helpdesk#124]
Dear GeneOntology helpdesk, 

I was searching AmiGO for a cellular component GO Term for Lymphotoxin-alpha Lymphotoxin-beta Lymphotoxin-beta heterotrimer, because our wetlab will perform experiments with this heterotrimer and I would like to annotate the experiment properly.

This is the reagent used in our lab:
+ https://www.rndsystems.com/products/recombinant-human-lymphotoxin-alpha1-beta2-protein_8884-ly
+ https://resources.rndsystems.com/pdfs/datasheets/8884-ly.pdf

This is what is written about the heterotrimer:
"The Lymphotoxin alpha 1/ beta 2 heterotrimer binds and activates the Lymphotoxin beta R/TNFRSF3 (LT beta R) which is expressed on macrophages, dendritic cells, hepatocytes, intestinal epithelial cells (IEC), follicular dendritic cells (FDC), and high endothelial venules (HEV)"

This are the related uniprot protein identifiers:
+ LTA P01374: http://www.uniprot.org/uniprot/P01374
+ LTB Q06643: http://www.uniprot.org/uniprot/Q06643

Could this term be generated?
Best, Elmar Bucher

**Comment by suzialeksander** [comment]
Hello @elmbeech,

Do you have some peer-reviewed literature that shows this complex is biologically significant or performs some function as a complex (it doesn't have to be written by you)?  And where, ideally, would you expect to find this term if it existed?  If you could elaborate on the location in the ontology and provide a PMID, we will definitely look into this. 

We're moving things around on the GO website so this information is currently a little hidden, but if you could look over the page at http://geneontology.org/contributing-go-term, I think we'll have enough information to determine if you need a new GO term

Thank you for contacting GO and we look forward to helping you.

**Comment by elmbeech** [comment]
Dear Gene Ontology Helpdesk, 

This are the publications listed by the vendor that hetero timers are formed:
+ https://www.ncbi.nlm.nih.gov/pubmed/7916655 (Browning 1993: Lymphotoxin beta, a novel member of the TNF family that forms a heteromeric complex with lymphotoxin on the cell surface.)
+ https://www.ncbi.nlm.nih.gov/pubmed/1733951 (Androlewicz MJ 1999: Lymphotoxin is expressed as a heteromeric complex with a distinct 33-kDa glycoprotein on the surface of an activated human T cell hybridoma. )
+ https://www.ncbi.nlm.nih.gov/pubmed/23524463 (Upadhya 2013: Lymphotoxin signalling in immune homeostasis and the control of microorganisms.)

Was I was looking for is something like :
+ http://amigo.geneontology.org/amigo/term/GO:0043256   for the Laminin Complex
+ http://amigo.geneontology.org/amigo/term/GO:0005587 for Collagen 4 
+ http://amigo.geneontology.org/amigo/term/GO:0005584 for Collagen 1
+ http://amigo.geneontology.org/amigo/term/GO:0034666 for Integrin alpha2-beta1 Complex

This is maybe a bit a miss use from GeneOntology. But I am not aware of an other controlled vocabulary identifier for protein complexes then GO terms. 
UniProt specifies only on protein level.  I use this identifiers to label my data. 
For example: 
+ Laminin_Complex_go0043256 for a data point that was caused by Laminin treatment
+ COL1A1_P02453 for a data point  caused by Collagen alpha-1(I) chain treatment
+ CDH8_P55286 for Cadherin-8 treatment 
... and so on. 
 
I think this makes data integration afterwords easier. And it makes much more clear which protein treatment really was done. 
Till now I always fond a GO term for the protein complexes I was looking for but not this time, when I was searching for a term for a Lymphotoxin Complex.

Please let me know if you think I should not use go terms as I do.
I don't know if I can contribute much from the biological side, as I am just a simple bioinformatician.
 
Best, Elmar Bucher


 ---- On Tue, 01 May 2018 17:01:49 -0700 suzialeksander <notifications@github.com> wrote ----

**Comment by suzialeksander** [comment]
Moved to https://github.com/geneontology/go-ontology/issues/15736
