### ISSUE TITLE
 archive/lite/latest/go_weekly-assocdb.rdf-xml.gz empty or missing.

### ISSUE THREAD

**Issue by martinhilbers** [geneontology/helpdesk#127]
Hi,

The last working version of lite/go_weekly-assocdb.rdf-xml.gz seems to be 
ftp://ftp.geneontology.org/go/godatabase/archive/lite/2018-02-24/go_weekly-assocdb.rdf-xml.gz

The file seems to be missing for March/April. It has returned for the may 5 release: 
ftp://ftp.geneontology.org/go/godatabase/archive/lite/2018-05-05/go_weekly-assocdb.rdf-xml.gz
but that file does not contain any data.

**Comment by kltm** [comment]
@martinhilbers 
Our apologies for the disruption. We are currently undergoing a transition to an RDF triplestore in preference to a relational database. As an inevitable part of this process, we are not being able to spend as much bandwidth in the support of the legacy SQL dumps, and will eventually stop supporting/supplying them at all.
The following helpdesk tickets may help give some context: https://github.com/geneontology/helpdesk/issues/4 https://github.com/geneontology/helpdesk/issues/126 .

**Comment by martinhilbers** [comment]
Is there any timeframe for when support for these will be dropped ?

**Comment by suzialeksander** [comment]
I don't know if there's a specific timeframe yet.  @kltm @dougli1sqrd is there anything you can add to this?

**Comment by kltm** [comment]
At this point, continued support for the full databases ended in about January (I believe referenced in one of the tickets); the lite databases will continue to be minimally support until either the new system provides sufficient coverage and examples (or the very old hardware/pipeline fails).
