### ISSUE TITLE
panther analysis using generic mapping file not working

### ISSUE THREAD

**Issue by yqy151** [geneontology/helpdesk#130]
I want to do panther analysis on panther website (http://www.pantherdb.org/geneListAnalysis.do). I work on non model species, so I uploaded my own gene list and reference list. The list looks like this: 

Gene.1G010200	PTHR33374,PTHR33374:SF1
Gene.1G022100	PTHR37391,PTHR37391:SF1
Gene.1G023400	PTHR27007,PTHR27007:SF12
Gene.1G028900	PTHR23500,PTHR23500:SF96
Gene.1G029300	PTHR31734,PTHR31734:SF31
...
The full lists are uploaded as attached files. My test list is my differentially expressed gene list and the reference list has the same format but include all the genes in the genome. 

However, when I click "launch analysis", I got "system error occurred. Please try again". I don't know what cause the error, my file format or the system? 

Thanks.

[test list.txt](https://github.com/geneontology/helpdesk/files/2018265/test.list.txt)
[reference list.txt](https://github.com/geneontology/helpdesk/files/2018266/reference.list.txt)

**Comment by kltm** [comment]
@mugitty @huaiyumi 
Would either of you have information about this for @yqy151 ?

**Comment by mugitty** [comment]
The lists should be formatted as follows: 
- The first column should contain your id

- The second column should contain either a PANTHER family id or PANTHER Subfamily id.  In your case you have the family id a comma followed by subfamily id.

**Comment by mugitty** [comment]
-
