### ISSUE TITLE
Best way to automatically resolve goc:something xrefs

### ISSUE THREAD

**Issue by jonquet** [geneontology/helpdesk#134]
Hi, 
We are parsing the content of several ontologies in AgroPortal to extract "mappings" using XREFS. 
We want to store the XREFS has RDF.

We have founded 184K occurences of goc:something in EFO,PR,TO,ENVO,CL,PATO,FLOPO,PCO,SO,GO

My questions are: 
1. What is the meaning of these xrefs exactly? Which semantic web property (better than oboinowl:hasDbXref) can represent that information? What about http://purl.org/pav/curatedBy ?
(see: https://pav-ontology.github.io/pav/#d4e300)
FYI: pav:curatedBy<pav:contributedBy<dcterms:contributor
                                                             <prov:wasAttributedTo

2. What are the best URIs for those xrefs ? I have founded a file online (http://www.geneontology.org/doc/GO.curator_dbxrefs) but it does not provide URIs. 
I can generate some "fake" URIs to transform for instance
GOC:lc
into
http://www.geneontology.org/doc/GO.curator_dbxrefs/lc
But the ideal case would be to have URIs directly proposed by you (in FOAF possibly)

See also https://github.com/pato-ontology/pato/issues/168 for similar issue on PATO.
See also https://github.com/Planteome/plant-ontology/issues/684 for similar issue on PO.

Thanks for your guidance.
/CC @elcioabrahao

**Comment by suzialeksander** [comment]
@cmungall is this something you can answer?

**Comment by balhoff** [comment]
For references like these for Noctua users, we expand `GOC:` to `http://purl.obolibrary.org/obo/go/users/` using [this JSON-LD context](https://github.com/geneontology/go-site/blob/master/metadata/users-groups-context.yaml). However that mapping isn't in [db-xrefs.yaml](https://github.com/geneontology/go-site/blob/master/metadata/db-xrefs.yaml)—maybe @cmungall can comment whether it should be. In general going forward in Noctua we are using ORCIDs instead.

**Comment by suzialeksander** [comment]
@cmungall do you have anything to add about the [db-xrefs.yaml](https://github.com/geneontology/go-site/blob/master/metadata/db-xrefs.yaml) mapping?

**Comment by cmungall** [comment]
we switch to orcids in the ontology

**Comment by suzialeksander** [comment]
@elcioabrahao @jonquet does this answer the original question?

**Comment by suzialeksander** [comment]
@elcioabrahao @jonquet Closing, assumed resolved.  Please open a new ticket if you have further questions!
