### ISSUE TITLE
Dereference GO_REF PURL to proper URL

### ISSUE THREAD

**Issue by jonquet** [geneontology/helpdesk#135]
Can we have the URL:
http://purl.obolibrary.org/obo/go/references/

Found in : 
http://www.geneontology.org/doc/GO.xrf_abbs

Be dereferenced to something like: 
https://github.com/geneontology/go-site/tree/master/metadata/gorefs
Or please advice another permanent URL to use to identify the GO_REF resource. 

To access a specific GO_REF: 
e.g., go_ref:0000008
I have found no better than:
https://github.com/geneontology/go-site/blob/master/metadata/gorefs/goref-0000008.md

Is it ok to use this or do you have something better.

\CC @elcioabrahaho

**Comment by suzialeksander** [comment]
@vanaukenk @ukemi are you able to answer this?

**Comment by cmungall** [comment]
The expansion is correct, the URL http://purl.obolibrary.org/obo/go/references/0000008 is currently resolved to a github page because we have limited resources and making a web page for each of the references hasn't been a high priority, but we will hopefully start working on this soon
