### ISSUE TITLE
Nicotiana benthamiana GOs

### ISSUE THREAD

**Issue by jtmatus** [geneontology/helpdesk#136]
Hi there! Considering that the Nb genome sequence (version1) and its annotation have been released (see https://solgenomics.net/tools/bulk?mode=ftp), would it be possible to have the GO classifications from this species in gene ontology.org so we can perform GOEA? Thanks!

**Comment by suzialeksander** [comment]
@vanaukenk or @ukemi, do you know who could address this? I would ask @kltm but I'm not sure when he's back.

**Comment by suzialeksander** [comment]
Hi @jtmatus, just to clarify: Are you trying to find existing GO annotations in Amigo, or are you looking to add your own set? 

Thanks!

**Comment by kltm** [comment]
My take on it was that it was a request to have ftp://ftp.solgenomics.net/manual_annotations added as an external resource.
If so, the file available there seems like it would take a lot of work to get it up to the level of a GAF.

**Comment by jtmatus** [comment]
Hi guys. thanks for taking interest in my query. So, I was hoping that in the list of species found in the left side of the main page of Gene Ontology Consortium (http://geneontology.org) if it could be possible for you to include Nicotiana benthamiana so to make easier my GOEAs. So far, I've done customised GOEA in AgriGO but having Nicotiana already incorporated in this list would fasten things up a lot. I have this file of GO annotations for each one of the Nicotiana genes that maybe can help?. 
[Niben101_GO_Agrigo.txt](https://github.com/geneontology/helpdesk/files/2112047/Niben101_GO_Agrigo.txt)

**Comment by kltm** [comment]
@jtmatus 
As it stands now, Nicotiana benthamiana does have some annotation already, mostly from UniProt:
http://amigo.geneontology.org/amigo/search/annotation?q=*:*&fq=taxon_subset_closure_label:%22Nicotiana%20benthamiana%22&sfq=document_category:%22annotation%22
You'd have to open up the search to get down to it, as it does not have a high count in the facets.

**Comment by kltm** [comment]
@jtmatus My apologies--I see now that this is a question about the enrichment tool, not the annotation browser.

**Comment by huaiyumi** [comment]
PANTHER, which supports the backend of the GO enrichment, provides the list of the species found in the left side of GO website. Besides the 112 genomes listed there, PANTHER supports another 800+ genomes from the reference proteome project for users to generate GO annotations (ftp://ftp.pantherdb.org/generic_mapping/).  I just checked. Unfortunately, Nb is not one of the nearly 1000 genomes supported in PANTHER. There are two options. The first option is to contact the reference proteome project (https://www.ebi.ac.uk/reference_proteomes) and work with them to incorporate the genome in their project. Once that is done, you can use the process mentioned above to generate the GO annotation file. The second option is to score your genomes against the PANTHER HMM library. Read our Nature protocol paper (https://www.nature.com/articles/nprot.2013.092), and find the details in Box 2 of the paper.

**Comment by suzialeksander** [comment]
Hi @jtmatus, does this answer your question for now?

**Comment by jtmatus** [comment]
thanks @suzialeksander and @huaiyumi . I did reply before thanking you for the support. Don't know why it didn't appear. Anyways, thanks again!

**Comment by suzialeksander** [comment]
@jtmatus, no worries! Thanks again for contacting GO Helpdesk!
