### ISSUE TITLE
Reasoning over is_a and part_of

### ISSUE THREAD

**Issue by mikpom** [geneontology/helpdesk#137]
According to relationship reasoning in the [docs](http://geneontology.org/page/ontology-relations) if A **part_of** B **is_a** C then A **part_of** C. But this does not seem to hold in the following example. GO:0000902 (cell morphogenesis)  **part_of** GO:0048856 (anatomical structure development). GO:0048856 (anatomical structure development) **is_a** GO:0008150  (biological_process). **BUT** GO:0000902 (cell morphogenesis) **is_a** GO:0008150  (biological_process). 

As I understand Biological process category is so broad that **is_a** assignment to it will be very liberal and those statements about reasoning won't hold for such relationships. 

Can anyone give me more inference?

**Comment by kltm** [comment]
@cmungall You might be able to speak to this?

**Comment by cmungall** [comment]
On 26 Jun 2018, at 18:55, Mikhail Pomaznoy wrote:

> As I understand Biological process category is so broad that  
> **is_a**  assignment to it will be very liberal and those statements 
> about reasoning won't hold for such relationships.

Can you give a counter-example where you feel it wouldn't hold? The 
semantics of the relationship hold regardless of how broad or narrow the 
class is.

**Comment by mikpom** [comment]
There are two points here:

1. Main point is that in this particular example (I can provide more
   of this kind) reasoning `if (A is_a B part_of C) then (A part_of C)`
   doesn't hold. So I find that part in the GO documentation
   misleading. You didn't comment on that yet.
   
2. Another point is to distinguish in which kind of relationships this
   reasoning doesn't hold. As I guess here this might happen in case
   of a category for which **is_a** relationships  assignment is
   loose. "Biological process" I think is such example and not
   because it is very general (top level) but because pretty much
   anything can be assigned to it. Counter-example would be a chain
   GO:0008135 (translation factor activity, RNA binding) **part_of**
   GO:0006412 (translation) **is_a** GO:0034641 (cellular nitrogen
   compound metabolic process). Here indeed `translation factor
   activity, RNA binding` **is_not_a** `cellular nitrogen compound
   metabolic proccess` but a **part_of** it and above mentioned
   reasoning holds.

**Comment by mikpom** [comment]
There is still misunderstanding on my question. I edited the initial comment. Hope it is now more clear what I am asking about.

**Comment by ukemi** [comment]
Morphogenesis and maturation are both part of the development of an anatomical structure. Morphogenesis, maturation and the development of the anatomical structure are all types of developmental processes. This is valid.

**Comment by mikpom** [comment]
If I know understood correctly two terms can be simultaneously connected with is_a and part_of relationships. If these relationships are not mutually exclusive then issue is resolved.

**Comment by cmungall** [comment]
Correct. We typically do not assert X is_a Y, X part_of Y, but inferences of this form are perfectly valid.
