### ISSUE TITLE
number of session

### ISSUE THREAD

**Issue by basha-kfshrc** [geneontology/helpdesk#138]
The GO Enrichment analysis doesn't allow me to do the analysis for more than one gene list (n=72) at a time,  even during the analysis of a single gene list, when I try to perform the analysis for different GO annotations (biological processes, cellular components, etc...) it stops responding and gives me a message that says "Maximum number of sessions is exceeded please try again later", and then I can't run any analysis until at least 10 mins have passed from my first attempt?
Can you fix this problem?
or is it an intentional restriction applied on the users?
Thanks

**Comment by mugitty** [comment]
The session count issue can be avoided by performing the analysis directly from pantherdb.org.   Do as follows:

1. Open browser to http://pantherdb.org/
2. Enter ids into text box under step 1. or use the browse button to select input file with gene ids
3. Select organism under step 2.
3.  Select Statistical overrepresentation test and deselect use default settings
4. Click on the submit button
5.  The system will prompt with the "Selection summary" page
6. Select annotation data set for analysis under Annotation Data Set selection.  This has option to select Full GO annotations types.
7.  Click on Launch analysis

Note, you can analyze up to 4 input lists by clicking on the "Change" button in the "Analyzed List" section and selecting multiple lists on the "select lists to analyze" section"
