### ISSUE TITLE
plasmodium gaf files

### ISSUE THREAD

**Issue by ctoen** [geneontology/helpdesk#143]
Hi GO,
The PlasmoDB team has a much more up to date .gaf file for Plasmodium falciparum (and likely also for other Plasmodium species) and is also updating these regularly. See http://plasmodb.org/common/downloads/ .  Could you use these files as well? 
Best,
Christa

**Comment by selewis** [comment]
Hi Christa,
Much appreciate your letting us know. Yes, of course, we really want to use the regularly updated GAFs from the site you mention. This is something we do need your help with though. For everything that is brought the information about how to grab it is maintained in the .yaml (yet another markup language) located here on github: https://github.com/geneontology/go-site/tree/master/metadata/datasets Take a look at these and then 1. run this command "git clone https://github.com/geneontology/go-site.git"; then 2. add a plasmo.yaml file in the go-site/metadata/datasets/ directory; 3. add an entry for plasmodb to the db-xrefs.yaml file (so we can link back to your gene pages); 4. add an entry for plasmodb to the groups.yaml file (so we can list your site); 5. add info on people to the users.yaml file; then finally 6. all the git commands for a pull request. If you're unfamiliar with git there's documentation here: https://help.github.com/ but likely you've got plenty of folk there who could help. Plus we can too. Hope to hear back from you soon.

**Comment by suzialeksander** [comment]
Hi @ctoen, 
After looking into this a little more, it seems we misunderstood that you're a different group than the one we've been getting the Pf GAF from.  We're going to discuss this internally and get back to you soon, no action needed from you yet.  Thanks for contacting us!

**Comment by suzialeksander** [comment]
Hi @uliboehme,
GeneDB is the current source of our Pf annotations. PlasmoDB seems to be interested in taking over with a more current GAF.  Could you discuss a possible change in ownership with @ctoen? 
Thank you!

**Comment by ctoen** [comment]
Dear Suzan, 

I think this message was not meant for me, was it? 

And, for your information, I'm only a user of the data and of your
tools. I don't see why this needs to be discussed with me. I mainly
wanted to make you aware of the much more updated files that could be
obtained via PlasmoDB. 

Best wishes, 

Christa

---
Christa Toenhake, MSc (PhD student)
Dept. Molecular Biology (route 274), Radboud Institute for Molecular
Life Sciences
Faculty of Science, Radboud University 
Geert Grooteplein 26-28, 6525GA Nijmegen, The Netherlands
c.toenhake@science.ru.nl, T +31(0)24 3610529
http://molbio.science.ru.nl/about/molecular-biology/richard-bartfai/ 

suzialeksander schreef op 2018-08-01 23:57:

> Hi @uliboehme [1],
> GeneDB is the current source of our Pf annotations. PlasmoDB seems to be interested in taking over with a more current GAF. Could you discuss a possible change in ownership with @ctoen [2]?
> Thank you! 
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [3], or mute the thread [4].
 

Links:
------
[1] https://github.com/uliboehme
[2] https://github.com/ctoen
[3]
https://github.com/geneontology/helpdesk/issues/143#issuecomment-409737720
[4]

**Comment by suzialeksander** [comment]
Hi @ctoen, I was reading this that you were a representative of PlasmoDB.  Apologies, but we will contact PlasmoDB to see if we can clear this up.  Thanks for the information and apologies again for the misunderstandings!
