### ISSUE TITLE
GOA/GO alignment

### ISSUE THREAD

**Issue by ValWood** [geneontology/helpdesk#144]
Remind me, how often, and how does GO exchange data with GOA

this human GP is unannotated in AmiGO
http://amigo.geneontology.org/amigo/gene_product/UniProtKB:P0CG12

but annotated in Uniprot and QuickGO.

Odd thing about this is that   it's a IBA PAINT annotation. These come *from* GO , and the annotation looks OK.....

**Comment by ValWood** [comment]
@pgaudet

**Comment by pgaudet** [comment]
I see 2 annotations in AmiGO 
<img width="952" alt="image" src="https://user-images.githubusercontent.com/4782928/42690010-fb4832d0-86a2-11e8-8e11-0bb1556f3dda.png">


and a different annotation in Uniprot: 
<img width="599" alt="image" src="https://user-images.githubusercontent.com/4782928/42690035-1d46072c-86a3-11e8-885a-a6217d1175c6.png">


Do you see the same ?

**Comment by ValWood** [comment]
Thanks for looking into this Suzi, I still think there is a fundamental  problem that a human entry is duplicated in the reference proteome.....

I'm trying to establish unknowns for human (no process broke down into unknown (ND) and unannotated).....but I want to ensure that I have no *annotatable*  genes in this list.

This duplicate was spotted when evaluating the unknowns for "annotatable". There may be others. I have not had a chance to look exhaustively yet. 

v

**Comment by ValWood** [comment]
CHTF8 is clearly  UniPrott issue. There are 2 sequences for CHTF8. At first glance they don't appear to be related. I'm trying to figure this out now as an example. I think I already mailed UniProt about it (will check). Basically  CHTF8 is a really conserved protein yeast->human with ~145 amino acids, so I can't work out what the longer ~500 aa version refers to. Oddly it doesn't t  his the  Pfam for CHTF8  http://pfam.xfam.org/family/PF09696#tabview=tab0 so something odd going on here. In GO we pick up the longer version rather than the correct shorter version because of the  hiuristic used for reference proteomes. I think this one is an edge case though. ANyway I'm closing this as it isn't a GO issue its a consequence of the pipeline and I'll follow up elsewhere.

**Comment by ValWood** [comment]
it isn't a GO issue, traced back to preparation of the reference genome Qfor O dataset so closing. I'm summarizing  in a word doc which I will circulate to interested persons and attach to the minutes.
