### ISSUE TITLE
Broken links from Rfam Wikipedia pages

### ISSUE THREAD

**Issue by AntonPetrov** [geneontology/helpdesk#146]
Dear GO team,

I noticed that there are **many broken GO links** on Wikipedia, especially on pages with Rfam infoboxes. 

For example, the following page:
https://en.wikipedia.org/wiki/Ms1_small_RNA

links to:
http://amigo.geneontology.org/cgi-bin/amigo/go.cgi?query=0070063&view=details

<img width="225" alt="screen shot 2018-07-18 at 17 44 58" src="https://user-images.githubusercontent.com/432675/42892532-53f9ded4-8ab2-11e8-9377-58aa2509a49c.png">

but the URL gives a "Not Found" error.

The old URL stopped working relatively (this year?) recently although I don't know exactly when.

There are hundreds of Wikipedia pages with links like this and there may be other resources that use this URL format so updating them all might be difficult. Is it possible to restore the URL or create an alias that will map it to the new format?

Your help will be greatly appreciated! Please let me know if you need more information.

**Comment by kltm** [comment]
@AntonPetrov 
Thank you for bringing this to our attention. The link you have above is a very old form; the correct form for the past several years would be (http://wiki.geneontology.org/index.php/AmiGO_2_Manual:_Linking):

http://amigo.geneontology.org/amigo/term/GO:0070063

The redirects probably went off after an update to the production server location, which likely dropped many legacy paths.
The best thing would be to update the template in Wikipedia, but I'm not really sure where that edit would be. Lemme see if I can find anything obvious...

**Comment by kltm** [comment]
Hm...this all looks fine in wikidata:
https://www.wikidata.org/wiki/Property:P686
https://www.wikidata.org/wiki/Q21100329
I'm not quite sure where the bad data is coming from.

**Comment by kltm** [comment]
Cheers!
We actually have been looking at the logs since the transfer, but we have not had the bandwidth to follow-up on most (our volume is quite high). That said, we have a lot of traffic from Wikipedia with the correct links (e.g. Gene Ontology section in https://en.wikipedia.org/wiki/Dopamine_transporter ), so I'm wondering if there is a pool of old data kicking around somehow.

**Comment by AntonPetrov** [comment]
I fixed the obsolete URL in the following template:
https://en.wikipedia.org/wiki/Template:GO

Thanks!

**Comment by kltm** [comment]
Ah--thank's where it is. Cheers!
