### ISSUE TITLE
discovery dates PPI

### ISSUE THREAD

**Issue by urielsinger** [geneontology/helpdesk#15]
Hello,

I'm interested in protein-protein interactions. Furthermore, I'm interested in the discovery date of each interaction between each protein couple.

Can I, and how can I extract this data?
 

Thank you,
Uriel
Technion

**Comment by kltm** [comment]
@cmungall 
I don't suppose you might have any ideas for this?

**Comment by ValWood** [comment]
The GO annotation file displays only the data the annotation was made (col 14). If you require the date that the interaction was dicovered you could need to  extract the PubMed ID (col 6), and then retreive the publication date from PubMed.

I hope this helps.

**Comment by cmungall** [comment]
@urielsinger I assume the context of your question is PPIs in GO, i.e protein binding annotations where the binding partner is in the with field? Of course, for general PPIs there are other database like IntAct

For GO PPIs, I think @ValWood's advice is good

**Comment by urielsinger** [comment]
Thank you all very much! It helped me a lot!

בתאריך 31 במאי 2017 8:05 לפנה״צ,‏ "Chris Mungall" <notifications@github.com>
כתב:
