### ISSUE TITLE
Paramormyrops kingsleyae GO annotations based on a list of entrez Gene IDs

### ISSUE THREAD

**Issue by mlosilla** [geneontology/helpdesk#150]
Hi,
I am interested in the GO annotations for a non-model organism whose genome has been annotated by NCBI. Is this something you could help me with?

Thank you
Mau

**Comment by kltm** [comment]
@mlosilla Would you be able to tell us the species you are concerned with?

**Comment by mlosilla** [comment]
Hi,

The species is Paramormyrops kingsleyae, NCBI species ID 1676925

Thanks!

**Comment by suzialeksander** [comment]
Hi @mlosilla,
Without anyone to do manual annotations, we recommend the InterPro2GO tool to produce GO annotations.  This is automatically run on all proteins submitted to UniProt and will produce IEAs (electronic annotations), but it looks like Paramormyrops kingsleyae isn't in there yet.  Have you contacted UniProt to submit your transcriptome yet?  
If you're interested in manual annotations, we can definitely work with you/your group on training as well.

**Comment by suzialeksander** [comment]
Hi @mlosilla, 
Were you able to resolve this question somewhere else, or is there still something we can help you with? I don't see a lot of proteins for Paramormyrops kingsleyae in UniProt yet, but if you already contacted them it can take a little while for the data to show up.

**Comment by mlosilla** [comment]
Hi,

Yes, it looks like all roads lead to UniProt. Someone in my team is reaching out to them. 

Thank you!
Mau

**Comment by suzialeksander** [comment]
Great! Let us know if there's anything in the future we can help you with. Thank you for contacting GO.
