### ISSUE TITLE
reactome Xref with old Ids.

### ISSUE THREAD

**Issue by Ayllonbe** [geneontology/helpdesk#151]
Hi,

I tried linking the GO with Reactome thanks to DBXref properties in go.owl and I observed that the ids of Reactome are the old versions and some of them don't exist.

Regards

**Comment by suzialeksander** [comment]
@Ayllonbe,
Thanks for contacting us. Can you provide a little more information? 
- [ ] What URL did you use to get these files, and 
Do you have any examples
- [ ]  of old IDs
- [ ] some IDs are missing?

Thanks!

**Comment by Ayllonbe** [comment]
@suzialeksander 
 Thanks for your answer. I  use http://www.geneontology.org/page/download-ontology and ftp://ftp.geneontology.org/go/ontology/ to download the go.owl or go.obo. Also, http://www.geneontology.org/page/download-mappings and ftp://ftp.geneontology.org/go/external2go/ to download the mapping between Reactome and GO having the same problem. 

For example in blood coagulation (GO:0007596) there are many Xref with Reactome (extract taken of go.obo):

xref: Reactome:REACT_101311 "Hemostasis, Plasmodium falciparum"
xref: Reactome:REACT_101372 "Common Pathway, Danio rerio"
xref: Reactome:REACT_102544 "Common Pathway, Rattus norvegicus"
xref: Reactome:REACT_102650 "Common Pathway, Mus musculus"
xref: Reactome:REACT_105166 "Common Pathway, Taeniopygia guttata"
xref: Reactome:REACT_105212 "Common Pathway, Sus scrofa"
xref: Reactome:REACT_107268 "Hemostasis, Saccharomyces cerevisiae"
xref: Reactome:REACT_108583 "Hemostasis, Danio rerio"
xref: Reactome:REACT_113650 "Common Pathway, Drosophila melanogaster"
xref: Reactome:REACT_114152 "Formation of Fibrin Clot (Clotting Cascade), Drosophila melanogaster"
xref: Reactome:REACT_118351 "Hemostasis, Escherichia coli"
xref: Reactome:REACT_1439 "Common Pathway, Homo sapiens"
xref: Reactome:REACT_2051 "Formation of Fibrin Clot (Clotting Cascade), Homo sapiens"
xref: Reactome:REACT_32530 "Hemostasis, Xenopus tropicalis"
xref: Reactome:REACT_32765 "Hemostasis, Mycobacterium tuberculosis"
xref: Reactome:REACT_33270 "Hemostasis, Canis familiaris"
xref: Reactome:REACT_34525 "Hemostasis, Arabidopsis thaliana"
xref: Reactome:REACT_604 "Hemostasis, Homo sapiens"
xref: Reactome:REACT_76944 "Common Pathway, Canis familiaris"
xref: Reactome:REACT_78290 "Hemostasis, Staphylococcus aureus N315"
xref: Reactome:REACT_81054 "Formation of Fibrin Clot (Clotting Cascade), Canis familiaris"
xref: Reactome:REACT_81972 "Formation of Fibrin Clot (Clotting Cascade), Taeniopygia guttata"
xref: Reactome:REACT_82283 "Formation of Fibrin Clot (Clotting Cascade), Mus musculus"
xref: Reactome:REACT_82383 "Hemostasis, Oryza sativa"
xref: Reactome:REACT_82403 "Hemostasis, Rattus norvegicus"
xref: Reactome:REACT_82445 "Formation of Fibrin Clot (Clotting Cascade), Sus scrofa"
xref: Reactome:REACT_82812 "Hemostasis, Bos taurus"
xref: Reactome:REACT_82940 "Common Pathway, Xenopus tropicalis"
xref: Reactome:REACT_83271 "Hemostasis, Dictyostelium discoideum"
xref: Reactome:REACT_84055 "Formation of Fibrin Clot (Clotting Cascade), Danio rerio"
xref: Reactome:REACT_84833 "Formation of Fibrin Clot (Clotting Cascade), Rattus norvegicus"
xref: Reactome:REACT_85674 "Hemostasis, Sus scrofa"
xref: Reactome:REACT_86354 "Common Pathway, Gallus gallus"
xref: Reactome:REACT_89750 "Hemostasis, Mus musculus"
xref: Reactome:REACT_89805 "Formation of Fibrin Clot (Clotting Cascade), Xenopus tropicalis"
xref: Reactome:REACT_90236 "Hemostasis, Taeniopygia guttata"
xref: Reactome:REACT_90805 "Hemostasis, Caenorhabditis elegans"
xref: Reactome:REACT_92318 "Hemostasis, Drosophila melanogaster"
xref: Reactome:REACT_94085 "Hemostasis, Schizosaccharomyces pombe"
xref: Reactome:REACT_94213 "Common Pathway, Bos taurus"
xref: Reactome:REACT_94315 "Formation of Fibrin Clot (Clotting Cascade), Bos taurus"
xref: Reactome:REACT_94798 "Formation of Fibrin Clot (Clotting Cascade), Gallus gallus"
xref: Reactome:REACT_96458 "Hemostasis, Gallus gallus"

REACT_XXXXXX is the old id in Reactome, now they use a stable id with the following structure R-ORG-XXXXX. ORG represent the organism of this pathway. For example, the REACT_604 is the pathway Hemostasis, Homo sapiens and its new stable id is R-HSA-109582. 


An example of an ID that is missing is REACT_33270 (Hemostasis, Canis familiaris) where it doesn't exist in the Reactome Data Base. 

Actually, Reactome has a mapping file between old ids and stable ids but I thought it would be more interesting if the stable ids were used in Xref for GO.

Thanks!!

**Comment by ukemi** [comment]
Hi,

We are in the process of updating all of these. It should happen fairly soon once all of our QC is completed.

See this ticket to monitor progress:
https://github.com/geneontology/go-ontology/issues/12518

**Comment by suzialeksander** [comment]
I'm closing this ticket because the actual problem will be worked out on the ticket mentioned earlier, geneontology/go-ontology/issues/12518. @Ayllonbe, you can see the progress on this fix on that ticket.

Again, thank you for contacting GO.
