### ISSUE TITLE
human entries missing from AmiGO e.g. Q6P6B7/ANKRD16 [BLOCKER]

### ISSUE THREAD

**Issue by ValWood** [geneontology/helpdesk#152]
The canonical (UniProt) entry for Q6P6B7/ANKRD16** doesn't appear to be in AmiGO.
Can we find out why? It's quite inportant that we have all human gene products.

@Antonialock  please tag the Nature paper on this ticket:

**Comment by ValWood** [comment]
AmiGO only has mouse and D. rerio
http://amigo.geneontology.org/amigo/search/bioentity?q=ANKRD16

Seems very odd?

**Comment by Antonialock** [comment]
https://www.nature.com/articles/s41586-018-0137-8.pdf

**Comment by Antonialock** [comment]
https://www.ebi.ac.uk/QuickGO/annotations?geneProductId=Q6P6B7

**Comment by ValWood** [comment]
Is annotated in QuickGO by ISS.

**Comment by ValWood** [comment]
Another Q5VXU9 c9orf84/SHOC1 is also not in AMiGO

**Comment by ValWood** [comment]
I really think we should have a sanity check that all of the human proteins are in  the GO database (once only!).  We have been trying to do this work since February ......

**Comment by ValWood** [comment]
CUSTOS UniProtKB:Q96C57

![custos](https://user-images.githubusercontent.com/7359272/43639361-ed44d04a-9713-11e8-81f3-e6a165c15b48.jpg)

**Comment by suzialeksander** [comment]
This issue was moved to geneontology/amigo#526
