### ISSUE TITLE
question about legacy downloads of ontology

### ISSUE THREAD

**Issue by keseler** [geneontology/helpdesk#154]
Hi all,

At EcoCyc/BioCyc, we've been using the go_daily-termdb.obo-xml downloads to update the ontology, downloading about weekly.  For the last couple of weeks, we have been getting a version dated
<data-version>releases/2018-08-03</data-version>, i.e. rather older than the latest.  Are the legacy downloads no longer being updated, or is this just a summer/vacation-time oversight?

Thanks,
Ingrid

**Comment by cmungall** [comment]
Hi Ingrid,

Apologies that this has not been well-communicated. We're not supporting this serialization any more.

The supported downloads are always available from:
http://www.geneontology.org/page/download-ontology

I can help you get set up with the conversions if you want to do this locally.

There is a perl module here:
https://metacpan.org/release/go-perl

After installing you can run go2obo_xml on the go-basic obo file.

I appreciate this is extra work, if you let me know more of your internal constraints I can help figure out the best way forward.

Historically we have been recommending everyone migrate to consuming the OWL, as this is a W3C standard. However, we appreciate this is a difficult model for many developers to work with. We are working on standardizing a JSON format for ontologies I would really appreciate your developers' comments on it:

https://github.com/geneontology/obographs
https://douroucouli.wordpress.com/2016/10/04/a-developer-friendly-json-exchange-format-for-ontologies/

**Comment by lpalbou** [comment]
Moved to the new site, closing this ticket
