### ISSUE TITLE
Dead link on file format page

### ISSUE THREAD

**Issue by mchibucos** [geneontology/helpdesk#157]
Howdy, GO! Just noticed here: http://www.geneontology.org/page/gene-product-association-data-gpad-format the link to ECO is dead. Displayed as "Evidence Code Ontology" and URL is  
http://www.obofoundry.org/cgi-bin/detail.cgi?id=evidence_code.

_Should_ say "Evidence & Conclusion Ontology" and link would optimally be updated to: http://www.evidenceontology.org ECO'd appreciate it if someone could update that.

Thank you!
Marcus

**Comment by suzialeksander** [comment]
Hi Marcus,

Thanks for letting us know, I'll update that now.
Hope all is well!

Suzi

**Comment by mchibucos** [comment]
Thanks Suzi!
 Hope all’s well with you too! :)


On September 12, 2018 at 1:41:36 PM, suzialeksander (
notifications@github.com) wrote:

Hi Marcus,

Thanks for letting us know, I'll update that now.
Hope all is well!

Suzi

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/geneontology/helpdesk/issues/157#issuecomment-420736073>,
or mute the thread

**Comment by suzialeksander** [comment]
This has been updated on the current site and the GH doc page.
