### ISSUE TITLE
discrepancy between Ensembl and GOC files

### ISSUE THREAD

**Issue by murphyte** [geneontology/helpdesk#159]
Hi GOC,

A user has pointed out a discrepancy in GO data between Ensembl and NCBI Gene. I've traced it to a difference between the GOA files available from GOC, vs. what is shown at Ensembl. Compare the data for SLC25A23:
http://amigo.geneontology.org/amigo/search/annotation?q=SLC25A23*&fq=taxon_subset_closure_label:%22Homo%20sapiens%22&fq=type:%22protein%22&sfq=document_category:%22annotation%22
https://www.ebi.ac.uk/s4/jump?from=aHR0cDovL3d3dy5lYmkuYWMudWsvczQvc3VtbWFyeS9tb2xlY3VsYXI/dGVybT1TTEMyNUEyMyZjbGFzc2lmaWNhdGlvbj05NjA2JnRpZD1uYW1lT3JnRU5TTVVTRzAwMDAwMDQ2MzI5&hash=hash&url=https://www.ensembl.org/Homo_sapiens/Gene/Summary?db=core;g=ENSG00000125648;r=19:6436079-6465203

The data shown in AmiGO matches what I get from the GOA download file at:
http://geneontology.org/page/download-go-annotations

Ensembl is showing an additional 8 GO terms:
GO:0006839
GO:0051503
GO:0055085
GO:0015217
GO:0046872
GO:0005743
GO:0016020
GO:0016021

I checked the last several GOA file revisions from SVN, and the data for SLC25A23 hasn't changed, so I can't account for the difference as a simple timing issue.

Is this an issue at GOC, or at Ensembl?

Thanks for checking!
-Terence

**Comment by cmungall** [comment]
Thanks for pointing this out.

Looking at the list:

GO:0006839-mitochondrial transport
GO:0051503-adenine nucleotide transport
GO:0055085-transmembrane transport
GO:0015217-ADP transmembrane transporter activity
GO:0046872-metal ion binding
GO:0005743-mitochondrial inner membrane
GO:0016020-membrane
GO:0016021-integral component of membrane

Seems like a mixed bag, some are redundant, but some are not

GO:0015217-ADP transmembrane transporter activity

![image](https://user-images.githubusercontent.com/50745/45667101-9f175000-bacc-11e8-8433-e43573841cab.png)

This apparently comes from GO Central (from the PAINT pipeline). I suspect that ENSEMBL is just  out of date here w.r.t what comes from GO Central. We use to have lots of PAINT annotations to this gene product, now only one.

Others are directly sourced from ENSEMBL:

![image](https://user-images.githubusercontent.com/50745/45667312-86f40080-bacd-11e8-8517-213909a4819b.png)

Unfortunately there is a lack of metadata about what method ENSEMBL used to predict this, e.g. compara vs some other method?

@tonysawfordebi or @alexsign can you elucidate?

**Comment by tonysawfordebi** [comment]
This is what we currently have in our database for Q9BV35, and what is also in the most recent set of files that we generated for Ensembl:

GO Aspect|GO ID|Term|Source
------|-----|----|------
C|GO:0005739|mitochondrion|UniProt Keywords2GO
C|GO:0005739|mitochondrion|Human Protein Atlas
C|GO:0005739|mitochondrion|Ensembl Compara
C|GO:0005743|mitochondrial inner membrane|UniProt Keywords2GO
C|GO:0005743|mitochondrial inner membrane|UniProt Subcellular Location2GO
C|GO:0016020|membrane|UniProt Keywords2GO
C|GO:0016021|integral component of membrane|UniProt Keywords2GO
F|GO:0005347|ATP transmembrane transporter activity|PAINT
F|GO:0005509|calcium ion binding|InterPro2GO
F|GO:0005515|protein binding|IntAct
F|GO:0005515|protein binding|UniProt
F|GO:0005515|protein binding|UniProt
F|GO:0022857|transmembrane transporter activity|InterPro2GO
F|GO:0046872|metal ion binding|UniProt Keywords2GO
P|GO:0002082|regulation of oxidative phosphorylation|Ensembl Compara
P|GO:0006851|mitochondrial calcium ion transmembrane transport|UniProt
P|GO:0015867|ATP transport|GOC (Inference)
P|GO:0036444|calcium import into the mitochondrion|UniProt
P|GO:0043457|regulation of cellular respiration|Ensembl Compara
P|GO:0051282|regulation of sequestering of calcium ion|Ensembl Compara
P|GO:0051503|adenine nucleotide transport|Ensembl Compara
P|GO:0055085|transmembrane transport|InterPro2GO
P|GO:0071277|cellular response to calcium ion|Ensembl Compara
P|GO:0097274|urea homeostasis|Ensembl Compara

Ensembl are currently displaying these three annotations that are no longer in our database; they should disappear when the Ensembl web site is updated:

Aspect|GO ID|Term|Source
------|-----|----|------
F|GO:0015217|ADP transmembrane transporter activity|PAINT
P|GO:0006839|mitochondrial transport|PAINT
P|GO:0015866|ADP transport|InterPro2GO

Any annotation that has an assigned_by of Ensembl (or EnsemblFungi, EnsemblPlants, EnsemblMetazoa or EnsemblProtists) is the result of a projection based on orthologs supplied by Ensembl, as described here: https://github.com/geneontology/go-site/blob/master/metadata/gorefs/goref-0000107.md

**Comment by murphyte** [comment]
Thanks! I see going back further in the SVN revisions that this gene had 4 additional GO terms in the 5-21-2018 file (generated 2018-04-23, with paint merges from 2018-04-25):
GO:0006839-mitochondrial transport
GO:0015217-ADP transmembrane transporter activity
GO:0005743-mitochondrial inner membrane
GO:0016021-integral component of membrane

So those can be accounted for by timing differences. 

But there are still 4 that aren't in AmiGO and are shown in Ensembl:

Aspect | GO ID | Term | Source
-- | -- | -- | --
P | GO:0051503 | adenine nucleotide transport | Ensembl Compara
P | GO:0055085 | transmembrane transport | InterPro2GO
F | GO:0046872 | metal ion binding | UniProt Keywords2GO
C | GO:0016020 | membrane | UniProt Keywords2GO

Those don't seem to correlate with the source. They do seem to be less specific variations of other terms on the list. Is there some extra filtering at GOC that isn't taken into account in the dataset shown at Ensembl?

**Comment by murphyte** [comment]
ok, thanks, that's possible. The current GOA files from SVN are from 2018-07-24 (plus paint merge from 2018-08-09), so maybe the extra terms will show up in the September release files.

**Comment by tonysawfordebi** [comment]
You can always find the files from the current GOA release at ftp://ftp.ebi.ac.uk/pub/databases/GO/goa/

Files from previous releases are available at ftp://ftp.ebi.ac.uk/pub/databases/GO/goa/old/

**Comment by murphyte** [comment]
Checking the current file, generated on 2018-09-10, it does *not* have the 4 GO IDs I listed above that are in Ensembl. It does have a few changes (addition of GO:0005743 and GO:0016021 and removal of GO:0015866), which I understand, But it seems like there's still a bit of data appearing at Ensembl that isn't in the GOA files.

**Comment by tonysawfordebi** [comment]
Which file are you looking at, exactly? Can you provide a link?

**Comment by tonysawfordebi** [comment]
Also, I draw your attention to the comments I made in https://github.com/geneontology/helpdesk/issues/159#issuecomment-422296181 about the data that is displayed on the Ensembl web site probably being in need of an update.

The only thing that I can say for certain is that - as of today - the annotations that we have for Q9BV35 are those that I listed above, and those are what should be displayed in Ensembl **at some point**,

**Comment by murphyte** [comment]
> Which file are you looking at, exactly? Can you provide a link?

This file does not have the 4 GO IDs I listed [in my comment above](https://github.com/geneontology/helpdesk/issues/159#issuecomment-422357480):
ftp://ftp.ebi.ac.uk/pub/databases/GO/goa/HUMAN/goa_human.gaf.gz

Those 4 are included in the expected Ensembl list provided above, so I'm still a bit perplexed (but not going to lose sleep over it).

**Comment by tonysawfordebi** [comment]
The annotations in the species-specific files that we produce are filtered to remove some redundancy. In particular, we remove electronic annotations to less-specific terms if we also have annotations to more-specific terms. So, for example, the annotation to GO:0016020 (membrane) is filtered out because we also have annotations to GO:0005743 (mitochondrial inner membrane).

If you want to see the full, unfiltered set, then that is available in ftp://ftp.ebi.ac.uk/pub/databases/GO/goa/UNIPROT/goa_uniprot_all.gpa.gz or ftp://ftp.ebi.ac.uk/pub/databases/GO/goa/UNIPROT/goa_uniprot_all.gaf.gz

**Comment by murphyte** [comment]
> The annotations in the species-specific files that we produce are filtered to remove some redundancy.
Bingo! That would definitely explain it. Thanks for all the diagnostics!

I'm going to close this thread, since my questions are answered and I don't think there are any remaining action items.
