### ISSUE TITLE
gene_association.gramene_oryza.gz has shrunk by 65%

### ISSUE THREAD

**Issue by murphyte** [geneontology/helpdesk#162]
Hi GO -- our QA detected a large decrease in the size of the gene_association.gramene_oryza.gz file, from 124459 lines to 50038 lines (including headers) between r46866 and 46999 (2018-08-09 vs. 2018-09-06). 

It looks like all the IEA annotations were dropped. Is that expected?

-Terence

**Comment by kltm** [comment]
@dougli1sqrd Would there have been a new go-rule triggered on this?

**Comment by kltm** [comment]
Looking in to this a bit more, we can see the reason in the annotation report. Apparently, most of the dropped annotations are from violating GO Rule 29: "All GAF annotations that have IEA as an evidence code that are also more than a year old should be removed." (https://github.com/geneontology/go-site/blob/master/metadata/rules/gorule-0000029.md)
This rule was unenforced for a while and we re-activated last month.

**Comment by murphyte** [comment]
Thanks for the explanation!
