### ISSUE TITLE
New Noctua user(s?) and group for CACAO 

### ISSUE THREAD

**Issue by kltm** [geneontology/helpdesk#164]
_From @jrr-cpt on October 8, 2018 3:26_

I have filled out the new user form to request access to Noctua. I work with @jimhu-tamu doing GO annotation in the CACAO class. My interest is to expand annotation for phage.

There is not a user group that we fit into in the [metadata](https://github.com/geneontology/go-site/blob/master/metadata/groups.yaml) referred to in the new user form. Can we have EcoliWiki/CACAO added?

_Copied from original issue: geneontology/go-site#849_

**Comment by sandyl27** [comment]
So @jrr-cpt is a post doc and I am teaching her about CACAO and Noctua.

**Comment by vanaukenk** [comment]
@kltm - I can take over from here if you'd like and add @jrr-cpt to the users.yaml file
@sandyl27 - thank you for the additional info!

**Comment by kltm** [comment]
@vanaukenk I've started here: https://github.com/geneontology/go-site/pull/853
Please go ahead and make any changes for groups, etc.

**Comment by vanaukenk** [comment]
@sandyl27 @jrr-cpt @jimhu-tamu

I just have one question wrt the entry for organization in the users.yaml file.

For Jim, Debby, and Sandy we have 'E. coli' as the organization but the pull request for Jolene has 'CACAO/Texas A&M'.  

Should we have everyone be the same? 'CACAO/Texas A&M' seems more inclusive, but I am happy to go with whatever you guys think is appropriate (mabye EcoliWiki/CACAO ?)

Here's what the users.yaml specs say about organization:

organization (RECOMMENDED) - the primary organization to which a person belongs
although a person may be involved in more than one, typically their GO role will be through one
this field is primarily for informational purposes

Thx.

**Comment by sandyl27** [comment]
I think EcoliWiki/CACAO would be good.

**Comment by suzialeksander** [comment]
Hmm... maybe it's time to remove Brenley? Do we keep the yaml current?

**Comment by kltm** [comment]
That said, it may not be a bad idea to move any given `groups` to `previous-groups` and removing and authorizations a user has, indicating that somebody is not active, which can be helpful for people less familiar or new to the project about somebody's status. We may even want to consider having a `status` field at some point. This is a low priority.

**Comment by jrr-cpt** [comment]
Now that I have been added to the users.yaml file and want to start working on a Noctua model with @sandyl27, I am stuck in a login loop. I login in through Github, which generates a token, which asks me to login via Github (ORCID, Google, and local do not work), which generates a token, that eventually I exit with the Return button only to get two error messages about a bad token. The end result is that I am not logged in. Have I missed something?
![screen shot 2018-11-06 at 3 31 32 pm](https://user-images.githubusercontent.com/38894438/48095302-081c6980-e1da-11e8-8896-f15340f73bc0.png)

**Comment by jrr-cpt** [comment]
@suzialeksander Yes I have checked in a couple different new private browsers now, I am definitely using the public Github account to try to login.

**Comment by jimhu-tamu** [comment]
I'm having the same problem logging into noctua via Github. Tried in Safari and Chrome.

**Comment by kltm** [comment]
@jimhu-tamu You are not registered at all in the system for Noctua (https://github.com/geneontology/go-site/blob/master/metadata/users.yaml#L367), so it would be expected that you cannot login.

@jrr-cpt I've reset the system again. Looking at your record, everything would seem to be correct. I would ask you to try again. Otherwise, we should set up a Zoom or Skype conf so that I can see what is actually going on when it happens.

**Comment by jrr-cpt** [comment]
@kltm I am now able to login successfully. Thank you!

**Comment by kltm** [comment]
@jrr-cpt 
My apologies about that. The topic went far enough afield, here and elsewhere, the finalizing step got put aside. I'm glad it's working now.
