### ISSUE TITLE
Gene ontology terms missing from GOA download files

### ISSUE THREAD

**Issue by oleraj** [geneontology/helpdesk#165]
Hi,

I'm trying to make a list of genes for each gene ontology term and noticed about 80 terms from my list of gene ontology terms that are missing from the human GO Annotations download files from here http://www.geneontology.org/page/download-go-annotations.  For example, the term `GO:0045073` corresponds to "regulation of chemokine biosynthetic process".  When I search in the goa_human* files, I don't see this term:
```
zcat goa_human.gaf.gz | grep GO:0045073
[empty]
```
However, when I search for the term on the website, I get 27 genes associated with the term.  
1. http://amigo.geneontology.org/amigo/medial_search?q=GO%3A0045073
2. Select "Annotations"
3. Filter for Homo Sapiens
![image](https://user-images.githubusercontent.com/10860409/47179733-cd1aca80-d2ec-11e8-951b-d3044718ab5a.png)

Is there any way for me to get a list of genes associated with a term without searching each term one by one?  Is there a more comprehensive gene ontology annotation file that will contain all genes associated with all terms?

Thanks!

Andrew

**Comment by cmungall** [comment]
Hi Andrew,

I'm answering off-line so there is a chance this will appear out of sync 
and someone will have answered already..

The website is using inference to include annotations to descendants of 
'regulation of chemokine biosynthetic process'

We could provide a file that has every gene to every inferred term. We 
generally don't distribute for all species this as it can be large due 
to all the redundancy, and it's fairly easy to calculate by joining a 
term-ancestor table with a gene-to-direct-term table.

If we provided the term-ancestor table, would that help you (I think 
this would be helpful to other users)? Or do you require the ready-made 
complete lookup table?

There are also various programmatic ways to do this kind of thing, e.g. 
in python using http://ontobio.readthedocs.org

**Comment by oleraj** [comment]
Hi Chris,

Thanks for the reply.  Yes, I think a term-ancestor table would be helpful.  It might also be helpful to provide the ready-made file if you have that (for human perhaps?) in case any of our assumptions about the gene ontology annotation database are incorrect which could lead to an incorrect final database.  (For example, can I assume that annotations are always associated with ontological terms that don’t have any child terms?)  Alternatively, some instructions on how to properly construct the complete (redundant) table from the original goa file and the term-ancestor table would probably be sufficient as well.

Thanks,

Andrew

**Comment by suzialeksander** [comment]
@oleraj, was this resolved off this ticket or are you still waiting for some follow-up?

**Comment by suzialeksander** [comment]
@oleraj I'm sorry this one fell through a crack!  Pinging @cmungall because he seemed to have a handle on it.

**Comment by suzialeksander** [comment]
@dougli1sqrd Anything to report on this yet?

**Comment by suzialeksander** [comment]
@dougli1sqrd Did you see this ticket?

**Comment by suzialeksander** [comment]
Hi @oleraj,

>  can I assume that annotations are always associated with ontological terms that don’t have any child terms
 
No, the annotations made are wholly dependent on the literature (or sequence/domain/etc. info for automatic) available, not the structure of the ontology.

Sorry this fell through the cracks.  It turns out the "file that has every gene to every inferred term" isn't normally produced on our end, so there was some confusion in finding it.  Are you still in need?

**Comment by oleraj** [comment]
Hi @suzialeksander, for my particular use case I was able to find a workaround so you can close this if you want, but I still find it odd that this type of information (even the simplest option, a term-ancestor table) is not readily available/retrievable.  I tried the link in @cmungall's reply about ontobio but was not able to get it to work (possibly an issue not being able to figure out the syntax for the command-line tool as the documentation is relatively poor), although that could theoretically be another way to get at the data I was originally looking for.

**Comment by suzialeksander** [comment]
Ok, thanks @oleraj.  We've added building these tables to our to-do list, sorry for any inconvenience and hopefully this will be available by the next time you need it.

**Comment by dougli1sqrd** [comment]
We have several open tickets to address this currently. To add these products to the pipeline, we have https://github.com/geneontology/pipeline/issues/70, and to add any necessary changes to robot we have https://github.com/ontodev/robot/issues/384.
