### ISSUE TITLE
Interpro references disappeared in lite/go_weekly-assocdb.rdf-xml

### ISSUE THREAD

**Issue by martinhilbers** [geneontology/helpdesk#17]
It seems that all but 1 Interpro references have disappeared from the lite/go_weekly-assocdb.rdf-xml
data file in the latest release:
ftp://ftp.geneontology.org/go/godatabase/archive/lite/2017-04-29/go_weekly-assocdb.rdf-xml.gz
They are present in the data file from the week before:
ftp://ftp.geneontology.org/go/godatabase/archive/lite/2017-04-22/go_weekly-assocdb.rdf-xml.gz

Similarly all references to Prints, Prosite, Prodom, Pfam, Smart and Pirsf are also missing in the latest datafile.

Is this by design, or did something go wrong in the data build ?

**Comment by kltm** [comment]
@martinhilbers,

Our apologies for this issue.

We will try and take a look at what is going on here (@cmungall I wonder if you might have any knowledge about what might have happened?), but our bandwidth may be limited until we have switched over to the new pipeline and production site. (You might be interested in the conversation taking place on #4, where we discuss a little bit about the roadmap and the deprecation of the sql dumps and pipeline, to be replaced with a sparql endpoint.)

**Comment by cmungall** [comment]
Apologies for the delay. This is due to a change in the API provided by NCBI, which means xrefs for gene products will be incomplete.

Unfortunately we don't have resources to fix this at the moment. We will be unveiling a new pipeline later this year - were the protein xrefs required for your use of the go-rdfxml files?

**Comment by martinhilbers** [comment]
I'm a bit confused - the missing references re-appeared a few weeks ago. Are you saying that the references now in the data are incomplete or unreliable ?
And yes - we do use the protein xrefs in the rdf-xml files.

**Comment by kltm** [comment]
@cmungall Any firther action here?

**Comment by kltm** [comment]
@cmungall Please reopen if there is further action here.
