### ISSUE TITLE
GO file for three categories: (1) Molecular Function (2) Biological Process (3) Cellular component

### ISSUE THREAD

**Issue by akesarwani** [geneontology/helpdesk#170]
I don’t see an individual GO file (.obo) separately for the  three categories on the GO webpage. I am using Ontologizer, and would to see the enrichment results for these 3 categories individually, instead of all in one.

**Comment by kltm** [comment]
@akesarwani
While there are three different interconnected "aspects" of the GO ontology, the development and downloads are from a single file.
I am personally not familiar with the Ontologizer; we do not provide support for that tool. If you wish to get at a specific subset of the GO, you can either filter it out out the source file, or possible download a specific subset with AmiGO (e.g.: http://amigo.geneontology.org/amigo/search/ontology?q=*:*&fq=idspace:%22GO%22&fq=is_obsolete:%22false%22&fq=source:%22biological_process%22&sfq=document_category:%22ontology_class%22 )

**Comment by suzialeksander** [comment]
Hi @akesarwani, thanks again for contacting GO Helpdesk. Did the above response solve your question, as far as separating the ontology file?

**Comment by suzialeksander** [comment]
The previously provided link allows you to download all BP terms; you can use the toolbar on the left side of Amigo to access 
* Molecular Function http://amigo.geneontology.org/amigo/search/ontology?q=*:*&fq=idspace:%22GO%22&fq=is_obsolete:%22false%22&fq=source:%22molecular_function%22&sfq=document_category:%22ontology_class%22

* and Cellular Component terms: http://amigo.geneontology.org/amigo/search/ontology?q=*:*&fq=idspace:%22GO%22&fq=is_obsolete:%22false%22&fq=source:%22cellular_component%22&sfq=document_category:%22ontology_class%22

Use the blue button in the top right ("Custom DL") to customize file content/order and download search results.  If you are familiar with advanced text editors or the command line interface, it may be easier to download the ontology (http://geneontology.org/page/download-ontology) and separate it based on `namespace:`.

I do not know how aspect-based files can be used in Ontologizer. Again, if you have specific questions about Ontologizer, you will have to contact their developers; they use our data but we have nothing to do with how they manipulate it.  You can contact them at: http://ontologizer.de/impressum/

I hope the above was helpful.  Do you have any other questions that we might be able to answer?

**Comment by pnrobinson** [comment]
@akesarwani this would probably be the best of doing this at this time.

**Comment by suzialeksander** [comment]
Hi @akesarwani, did this help you resolve the issue?

**Comment by suzialeksander** [comment]
@akesarwani Thanks for contacting GO.  I hope your issue has been resolved, and if we can answer anything else please open a new ticket.
