### ISSUE TITLE
EC numbers in go.obo

### ISSUE THREAD

**Issue by MrTomRod** [geneontology/helpdesk#171]
Hi!
I want to create a mapping from GO-terms to EC-numbers using your [go.obo](http://purl.obolibrary.org/obo/go.obo) file.
I noticed that some terms have an EC number in their definition, but not as a `xref` attribute.

Example of an entry that makes sense to me:

> [Term]
id: GO:0103118
name: UDP-3-O-(R-3-hydroxymyristoyl)-glucosamine N-acyltransferase activity
namespace: molecular_function
def: "Catalysis of the reaction: UDP-3-O-[(3R)-3-hydroxytetradecanoyl]-alpha-D-glucosamine(1-) + an (3R)-3-hydroxymyristoyl-[acp] <=> UDP-2,3-bis[O-(3R)-3-hydroxymyristoyl]-alpha-D-glucosamine + H+ + a holo-[acyl-carrier protein]" [**EC:2.3.1.191**, GOC:pz]
**xref: EC:2.3.1.191**
xref: MetaCyc:UDPHYDROXYMYRGLUCOSAMNACETYLTRANS-RXN
is_a: GO:0016747 ! transferase activity, transferring acyl groups other than amino-acyl groups

Example of one that does not:

> [Term]
id: GO:1990886
name: 3,4-dihydroxy-5-polyprenylbenzoic acid O-methyltransferase activity
namespace: molecular_function
def: "Catalysis of the reaction: 3,4-dihydroxy-5-polyprenylbenzoic acid + S-adenosyl-L-methionine = 3-methoxy-4-hydroxy-5-polyprenylbenzoic acid + S-adenosyl-L-homocysteine + H+." [**EC:2.1.1.114**, PMID:10419476, RHEA:44452]
is_a: GO:0008171 ! O-methyltransferase activity
created_by: sl
creation_date: 2015-10-28T22:12:58Z

Is this a mistake?

Should I only take `xref` entries to map GO terms to EC numbers or can I take all "occurrences" of EC numbers?

**Comment by hdrabkin** [comment]
Take nothing if it 's a three digit EC as these are gouping terms and should not have been used for definitions, let alone xrefs; will add the Ec xrefs to the one you mention.

**Comment by MrTomRod** [comment]
This is only the first one I found when I was writing this issue! There are a few more like this.

**Comment by hattrill** [comment]
I'm tagging @sjm41 on this may be of interest to him.

**Comment by hdrabkin** [comment]
No, it's the 3 digit xrefs should not be used with reactions that are more specific; I am working through removing them, replacing with a better EC if available.

**Comment by suzialeksander** [comment]
@MrTomRod Have you found any more entries that need attention or do you have any more questions at this point?

**Comment by MrTomRod** [comment]
I remember I found a few more. If I were you, I'd write a small script to find them!

Can you do this or should I do it?

**Comment by hdrabkin** [comment]
Hi @MrTomRod 
This is part of an ongoing project. When we find one, we need to do searches to see if we can replace them with something else (for a def ref, a PMID is preferred). This means checking Ec, Wiki , Google, Kegg, Metacyc, RHEA, etc etc. If the reaction is well defined, I send a request to EC and RHEA; this is slow because of staff limitations.

**Comment by hdrabkin** [comment]
I have added the xref to your example above.

**Comment by suzialeksander** [comment]
@MrTomRod did you have any more entries that need to be fixed?

**Comment by MrTomRod** [comment]
I wrote a simple Python 3 script to find possible discrepancies for you: [download](https://campuscloud.unibe.ch:443/ssf/s/readFile/share/28141/-2570359996883045275/publicLink/findMissingEC.py)

Use it as follows: `python3 findMissingEC.py /path/to/go.obo`

For each GO-term, it makes a set of EC-numbers that occur in the text and a set of EC-numbers that are annotated via xref. Then, it compares the two sets and gives an error if the sets are not identical. Maybe, you need to improve my code to filter unnecessary results, but I'm sure you can manage this by yourself. This is what some of the output looks like:

```
Error on term: GO:0046932 XrefECs: set() TextECs: {'EC:3.6.3.15'}
Error on term: GO:0046933 XrefECs: set() TextECs: {'EC:3.6.3.14'}
Error on term: GO:0046936 XrefECs: set() TextECs: {'EC:3.5.4.4'}
Error on term: GO:0046961 XrefECs: set() TextECs: {'EC:3.6.3.14'}
Error on term: GO:0046962 XrefECs: set() TextECs: {'EC:3.6.3.145', 'EC:3.6.3.15'}
Error on term: GO:0046969 XrefECs: set() TextECs: {'EC:3.5.1.17'}
Error on term: GO:0046970 XrefECs: set() TextECs: {'EC:3.5.1.17'}
```

There are quite a few more entries, I'm sure. For example GO:0046961.

**Comment by hdrabkin** [comment]
I have been systematically going through a list we have to remove 3 digit ecs a XREFS; replace then when we can with a 4 digit and/or rhea. 
I have NOT altered any use of them in the definition reference. Often it is the only reference, however unsatisfactory. But the FIRST pass is to remove them from Xrefs.

**Comment by cmungall** [comment]
Only catching up with this ticket now

@hdrabkin not sure what the 3 digit issue has to do with this.

There are ~400 GO terms in which a leaf/4-digit EC term has been used in the definition of a GO term, for which there is no EC xref.

EITHER the GO term is equivalent to the EC, in which case an xref should be added
OR the GO term is not equivalent, in which case the definition is suspect and this term needs to be looked at closely, possibly obsoleted.

**Comment by cmungall** [comment]
@hdrabkin this is the set. Happy to automate the adding of the xrefs if you let me know which ones are OK

[suspect.txt](https://github.com/geneontology/helpdesk/files/2978838/suspect.txt)

**Comment by hdrabkin** [comment]
Because some of the 3 digits that are listed in this file (you have to click on the 'here' to get them al) are actually in the defintion ref and not in the Xrefs (ie, already removed as I progress through the spreadsheet you had made for me under ticket #12988. 
'There are ~400 GO terms in which a leaf/4-digit EC term has been used in the definition of a GO term, for which there is no EC xref."
yes, as I find them I add the EC as an xref (as well as a rhea if I can find).

**Comment by cmungall** [comment]
OK, so it sounds like these will be addressed in time. I thought this ~400 would be a good chunk to prioritize as they're presumably mostly easy, & this would be useful to users who are puzzled about the seeming discrepancy -- but if you think it's better to stick to the existing workflow that is fine

**Comment by hdrabkin** [comment]
I see that there are obsolete terms in the suspect.txt file. (95 terms); should I ignore ?

**Comment by cmungall** [comment]
Sorry about that, yes. Let me know if you want it regenerated or in a different format

**Comment by hdrabkin** [comment]
No, that's good; BTW, almost done with spreadsheet from 12988, so that will free me up to address looking at other related issues. I am more than 1/2 -way through low hanging fruit from EC/RHEA/Metacyc alignment also.

**Comment by suzialeksander** [comment]
Update from the GOC Meeting in Cambridge: 
* Of the 424 entries with leaf node EC xrefs, 185 were assigned RHEA ids
    * There remain 240 entries with various issues (unresolved substrate nomenclature mismatches; specificity issues: RHEA more or less specific; multiple RHEA mappings but none match current GO/Metacyc)

@MrTomRod, I'm closing this ticket as it seems @hdrabkin is very aware of and still actively working on this.  Thank you for bringing it to our attention and thanks to @hdrabkin for making such great progress.
