### ISSUE TITLE
Data licences for the annotation files?

### ISSUE THREAD

**Issue by julie-sullivan** [geneontology/helpdesk#173]
I see the data licence for GO here http://geneontology.org/page/use-and-license. `Gene Ontology Consortium data and data products` are covered under the licence -- Does that include the annotation files too? 

Thank you!!

**Comment by kltm** [comment]
@julie-sullivan 
Easy answer: yes, it does indeed cover our annotation files as well. We are almost done with an updated website that will hopefully be a little bit more clear about that.
