### ISSUE TITLE
Relationship between mouse and human GO biological processes

### ISSUE THREAD

**Issue by syouligan** [geneontology/helpdesk#174]
Hi there

I am not sure this is the forum for such a question, fell free to direct me to somewhere more appropriate. I was hoping to understand the relationship between evidence generated in mouse studies and whether this is used to inform relationships and gene associations to the human biological processes ontology.

For example, a gene that is seen to be associated with ossification in a mouse experiment. Will the human ortholog of this gene also be associated with ossification?

Does this mean mice experiments are being used to infer the function of human diseases and their relationships to known pathways?

Any insight would be greatly appreciated.

Thanks!

**Comment by kltm** [comment]
@ukemi @hdrabkin Would either of you be able to speak to this?

**Comment by suzialeksander** [comment]
Hi @syouligan,
I don't know what level of experience you have, so apologies in advance if this is too basic or I misread your question.

Yes, information from one organism can certainly be used to infer functions of genes in another organism.  That is part of the promise of "model organisms": some experiments are really not possible in humans for ethical/financial or other reasons, but the experiment can be done fairly easily and reproduced reliably in yeast, worms, or as you mentioned mice. Or, one particular organism has features that make it ideal to study a particular topic- zebrafish develop from see-through embryos, so are ideal for early development, and yeast share many of the same enzymes as humans but usually have fewer 'versions', so pathways are easier to determine.

However, there are many factors to be taken into account before such an assumption is made, including but not limited to sequence similarity, presence of domains important/essential to that function, existence of interactions with other genes, etc.  A lot of this is done by the authours of the papers used to make the GO annotation, although sometimes curators piece together information that was overlooked by the paper or tool referenced or draw.  An annotation to a mouse term MAY be transferred to a human ortholog, but it's not a certainty. 

GO is a member of the Alliance of Genome Resources, which may have some information you will find useful.  The Alliance site presents an easy to read summary of gene/disease information from members of the Alliance (see https://www.alliancegenome.org/about-us).  For example, if I search for "ossification",  the page https://www.alliancegenome.org/disease/DOID:0060887 pops up.  This page shows annotations done by RGD (Rat Genome Database), for example, that leads to the RGD site: https://rgd.mcw.edu/rgdweb/report/annotation/main.html?term=DOID:0060887&id=1351327.  This is a fairly detailed trail showing the information reviewed by RGD curators.  As you originally mentioned mice, there are mouse annotations on this Disease Page as well- annotations that were based on statements the authours made in the cited literature.  

If this didn't help, please provide a little more info about your background/purpose of looking into GO and we will be happy to answer any GO (or Alliance) questions here.

**Comment by syouligan** [comment]
Hi @suzialeksander 

Thank you for the fast and comprehensive answer. No need to apologise, this response addresses my question perfectly. I was hoping to establish whether there was "cross pollination" between the data obtained from model organisms, and whether this was used in the annotation of human gene-function relationships. It seemed intuitive that it must - as this is the goal of using animal models - however as I couldn't see this overtly stated anywhere I didn't want to just assume.

Thanks very much for your help!
