### ISSUE TITLE
 Gene Ontology Antislim not working

### ISSUE THREAD

**Issue by Manti19** [geneontology/helpdesk#175]
Antislims which are internal controls are not accessible or maintained properly. Error 404 popped up every time when I try to  access it.

**Comment by cmungall** [comment]
Can you say which URL you are trying to access?

**Comment by Manti19** [comment]
> Can you say which URL you are trying to access?
I was trying with these two URLs
https://geneontology.github.io/docs/go-subset-guide/
http://www.geneontology.org/page/go-subset-guide#For_internal_checking_purposes_we_also_provide_two_anti-slims

**Comment by Manti19** [comment]
https://geneontology.github.io/docs/go-subset-guide/
http://www.geneontology.org/page/go-subset-guide#For_internal_checking_purposes_we_also_provide_two_anti-slims

**Comment by Manti19** [comment]
> Can you say which URL you are trying to access?

**Comment by cmungall** [comment]
It looks like a typo on the web page. The name of the slim is `gocheck_do_not_annotate` not `goslim_gocheck_do_not_annotate`.

We will update the links when we move to the new site next week. I will keep this ticket open til then.

For now, use:
http://current.geneontology.org/ontology/subsets/gocheck_do_not_annotate.obo

**Comment by Manti19** [comment]
Thanks.

**Comment by suzialeksander** [comment]
Hi @Manti19, 
Thanks for letting us know about this incorrect link.  I've fixed it on the old and the new versions of the GO website.  You can follow us by watching our [GitHub announcement repo](https://github.com/geneontology/go-announcements/issues); we'll also be announcing the new site release [on Twitter](https://twitter.com/news4go).
