### ISSUE TITLE
File size 

### ISSUE THREAD

**Issue by AramKrol** [geneontology/helpdesk#177]
File size of go_weekly-assocdb-tables.tar.gz was 245mb up to 22-12-2018,  size in the 2 release after that  has shrunk to 55mb. I did not see any announcement in release data .

Is this correct ?

**Comment by suzialeksander** [comment]
@kltm are you able to answer this?

**Comment by suzialeksander** [comment]
I'm closing this ticket due to inactivity.  @AramKrol, I hope this has answered your question, and please contact us again if there's anything else we can help with.
