### ISSUE TITLE
Dead link on GO homepage (pfam2go)

### ISSUE THREAD

**Issue by davidbio** [geneontology/helpdesk#178]
The new GO homepage has a dead link for the Pfam2GO mapping text file:
http://geneontology.org/external2go/pfam2go

The dead link can be found on this page:
http://geneontology.org/docs/download-mappings
-> Pfam domains

**Comment by kltm** [comment]
We are actively working on this ticket at this location: https://github.com/geneontology/go-site/issues/688
We should have a working solution very soon.

**Comment by suzialeksander** [comment]
Hi @davidbio, I just tried this link and can access the file.  I'm closing this as resolved, if you have any issues please let us know.
