### ISSUE TITLE
GO.references no longer produced, is this correct?

### ISSUE THREAD

**Issue by kltm** [geneontology/helpdesk#180]
We used to have a file http://52.27.86.54/doc/GO.references that no longer seems to have an analog. We now produce http://snapshot.geneontology.org/metadata/gorefs/, from the metadata at https://github.com/geneontology/go-site/tree/master/metadata/gorefs
Is the new separated format what we'll be directing people to for parsing and ingest? For a downstream pipeline that may be a bit more work--directory scan and match, frontmatter extraction.

**Comment by kltm** [comment]
Found by @christabone

**Comment by kltm** [comment]
Talked to @cmungall , will support with script point to `current` version, will need to be seeded for the time being until the next release comes out.

**Comment by kltm** [comment]
Actually, will seed with old one in the interim.

**Comment by kltm** [comment]
Work to be done in https://github.com/geneontology/go-site/issues/993

**Comment by christabone** [comment]
Thanks @kltm !

**Comment by kltm** [comment]
Not the work ticket, but the URL should be temporarily active again as a 302.
