### ISSUE TITLE
Question about disposition of gene_ontology.obo

### ISSUE THREAD

**Issue by kltm** [geneontology/helpdesk#181]
Before the transition, the file http://52.27.86.54/ontology/gene_ontology.obo was available, but does not appear in the new mapping. 

The canonical file is likely go.obo. Is the gene_ontology.obo alias useful and should be reinstated? At least one group was burnt by the removal, but I'm unsure of any other historical or architectural considerations here.

**Comment by kltm** [comment]
Tagging @sierra-moxon

**Comment by kltm** [comment]
I've touched bases internally and it looks like that we'd like to have gene_ontology.obo alias go away as deep legacy, in preference for the canonical go.obo, and with our apologies for the sudden transition. Would this be doable at your end? The proper location for all ontologies should be their PURLs, see: http://geneontology.org/docs/download-ontology/

**Comment by suzialeksander** [comment]
For the record, this change just got us too- I think the new go.obo URL will work, will post on this issue if we have problems with it after some tinkering

**Comment by kltm** [comment]
@suzialeksander Yes, please definitely let us know either way.
The fundamental issue is that only PURLs are "officially" supported at this point for the ontologies, with them currently resolving in the obvious ways to the current/releases. By using the PURLs we future proof the world from any further changes like this that might bite us in another ten years.

**Comment by jernst98** [comment]
This change has also broken the GO download capabilities of software I have released, which had a hard pointer to http://www.geneontology.org/ontology/gene_ontology.obo

I should be able to update it in future versions of the software, but I do not have a way to update it for the many users that have already downloaded the software I have written.

**Comment by suzialeksander** [comment]
@jernst98 Thank you for letting us know about your situation.  We're trying to find a solution ASAP, and will tag you with any developments. Again, apologies that this change was so abrupt.

**Comment by kltm** [comment]
@jernst98
We have gone ahead and instantiated a temporary redirect to the legacy alias.

**Comment by jernst98** [comment]
Would it be possible to have it redirect to go-basic.obo instead of go.obo?
There are changes in the go.obo format that is not compatible with my software, but the go-basic.obo file still works.
