### ISSUE TITLE
UCL contribution section revisons

### ISSUE THREAD

**Issue by RLovering** [geneontology/helpdesk#182]
Hi Suzi

thanks for the update on the new website, I'll retweet tomorrow.

Please would you update the text on this page
https://geneontology.github.io/docs/annotation-contributors/

University College London functional gene annotation: Please capitalise all first letters TO: 
>University College London Functional Gene Annotation

Annotation projects: the Cardiovascular Gene Annotation Initiative and Parkinson’s UK Gene Ontology Project : Please change TO:
>Manual annotation of human proteins and microRNAs involved in cardiovascular and dementia-relevant processes.

British Heart Foundation [RG/13/5/30112], Alzheimer’s Research UK [ARUK-NSG2016-13], National Institute for Health Research University College London Hospitals Biomedical Research Centre: please add more funders, so change to:
> British Heart Foundation [RG/13/5/30112; SP/07/007/23671], Alzheimer’s Research UK [ARUK-NSG2016-13; NAS2017A-1; NGS2018-003], Parkinson's UK [G-1307], National Institute for Health Research University College London Hospitals Biomedical Research Centre: 

UCL functional gene annotation: Please capitalise all first letters TO: 
>UCL Functional Gene Annotation

Thanks

Ruth

**Comment by suzialeksander** [comment]
Hi Ruth,

Thanks for checking all of those out and for the new info.  It should all be changed now.

**Comment by RLovering** [comment]
Hi Suzi

Thanks for doing this so quickly. Unfortunately I noticed another couple of edits required:

sorry there is one other link on our section which doesn't work. Please replace the link to our title in the first colum: University College London Functional Gene Annotation with: 
www.ucl.ac.uk/functional-gene-annotation/

Also I noticed that there is a page of 'Past collaborations' http://geneontology.org/docs/collaborations/ please would you include the following papers in this list:
Alzheimer’s Disease Publication available here with a link to:
https://www.ncbi.nlm.nih.gov/pubmed/30501127
micrRNA annotation guidelines Publication available here with a link to: https://www.ncbi.nlm.nih.gov/pubmed/26917558

Thanks

Ruth

**Comment by suzialeksander** [comment]
No worries! I changed all of that too.  Let me know if there's anything else.
