### ISSUE TITLE
go-ontology-edit.obo missing from new site

### ISSUE THREAD

**Issue by suzialeksander** [geneontology/helpdesk#184]
Related to the same topic. 

Could you help me to point me out which one is the replacement for this
file in the new site: http://geneontology.org/ontology/go-ontology-edit.obo because I am not sure if I should replace it with http://geneontology.org/ontology/go-basic.obo or http://snapshot.geneontology.org/ontology/go.obo (we download the obo file in our IntAct and ComplexPortal release)

Kind regards

_Originally posted by @noedelta in https://github.com/geneontology/helpdesk/issues/179#issuecomment-462398884_

**Comment by kltm** [comment]
@noedelta 

Our apologies for the jarring transition. All GO ontology files should be accessed by their PURLs to ensure that legacy aliases do not accidentally get transitioned away in the future: http://geneontology.org/docs/download-ontology/

After a little discussion, I believe that the file you're looking for is: http://purl.obolibrary.org/obo/go/go-basic.obo

If you need any further help, please let us know.

**Comment by suzialeksander** [comment]
@noedelta, I'm closing this because I think this is the solution you needed, please let us know if you needed anything else.
