### ISSUE TITLE
Why Epidermal differentiation complex is not available in GO?

### ISSUE THREAD

**Issue by pengyu** [geneontology/helpdesk#19]
I see epidermal differentiation complex which has been studied quite extensively. Is there a reason why it is not included in GO? Thanks.

https://en.wikipedia.org/wiki/Epidermal_differentiation_complex

**Comment by hdrabkin** [comment]
Hi, thank you for contacting GO.
It appears what  you describe is a gene complex, which is more appropriate for the sequence ontology
The GO has terms describing protein complexes as an indication of when a protein functions as part of a protein complex.

**Comment by cmungall** [comment]
SO would not have individual named gene complexes, just the generic complex.
