### ISSUE TITLE
Link gene_ontology.obo to go-basic.obo instead of go.obo

### ISSUE THREAD

**Issue by jernst98** [geneontology/helpdesk#194]
The URL http://www.geneontology.org/ontology/gene_ontology.obo use to point to files in the go-basic.obo format, but is now pointing to the go.obo file. The go.obo file format breaks legacy software. Since that URL is being maintained to support legacy software I think it would make more sense if it pointed to the go-basic.obo file. Would that be possible?

I also raised this in the comments of issue #181, but since that issue is still closed I am opening it here.

**Comment by pgaudet** [comment]
@cmungall Where should this file be redirecting ?

**Comment by jernst98** [comment]
It should be redirect to one of these:

http://purl.obolibrary.org/obo/go/go-basic.obo
http://snapshot.geneontology.org/ontology/go-basic.obo

**Comment by kltm** [comment]
Talked to @cmungall , we'll move ahead with this.

**Comment by jernst98** [comment]
Thanks!
