### ISSUE TITLE
Contributing new genome-wide predictions for maize, wheat, rice, barley, soy, and cotton

### ISSUE THREAD

**Issue by iacornflake** [geneontology/helpdesk#195]
We have developed a pipeline to aggregate computational functional annotations for plants, with increased genome coverage and increases in GO assignment per gene, with performance (based on F-Score calculated based on a curated gold standard set of assignments) comparable to the Ensemble pipeline (for maize and rice, where we have goldstandards for assessments). (See https://onlinelibrary.wiley.com/doi/full/10.1002/pld3.52 for details in maize). We are releasing these annotations for maize, rice, cotton, soy, cotton, and barley via DOI and are in the process of writing a paper. How do we contribute these genome-wide computational predictions with the appropriate evidence codes (IEA) via GO?

Thanks!
Carolyn J. Lawrence-Dill

**Comment by suzialeksander** [comment]
@iacornflake it seems like you have produced these IEA annotations already, but I didn't see them attached as SI- are these available for us to look at somewhere? 

Thanks!

**Comment by Thyra** [comment]
We are putting them up here: https://dill-picl.org/projects/gomap/gomap-datasets/
So far there's two maize sets, one for rice, and one for wheat. The other genomes are still being worked on.

**Comment by suzialeksander** [comment]
Hi @Thyra, am I correct in understanding these sequences are not in UniProt? I'm trying to do a little spot checking and am having difficulties finding information to map the identifiers given to any database.  In other words- which set has existing IEAs (or even better, manual annotations) that we can compare with your results?

**Comment by Thyra** [comment]
Yes, that's a problem we could probably write a book about as well; we got the peptide sequences directly from the groups working on these organisms:

**Source of Input Sequences**
- Maize: [MaizeGDB](https://www.maizegdb.org/) -- @wkpalan can you supply the direct link to where you got the input sequences from?
- Rice: [Gramene](http://www.gramene.org), more specificially the file `Oryza_sativa.IRGSP-1.0.pep.all.fa.gz` from ftp://ftp.gramene.org/pub/gramene/CURRENT_RELEASE/fasta/oryza_sativa/pep/ 
- Wheat: [IWGSC RefSeq 1.1](https://wheat-urgi.versailles.inra.fr/Seq-Repository/Annotations), direct link: file `IWGSC_v1.1_HC_20170706_pep.fasta` in [here](https://urgi.versailles.inra.fr/download/iwgsc/IWGSC_RefSeq_Annotations/v1.1/iwgsc_refseqv1.1_genes_2017July06.zip).

**Other GO Annotations**
- Maize: There is a hand-curated dataset and we also compared ours to the existing IEAs on Gramene and Phytozome in terms of quantity and quality using that gold standard - see this publication: https://onlinelibrary.wiley.com/doi/full/10.1002/pld3.52
- Rice: You can get annotations with the same gene identifiers from [Gramene Biomart](http://ensembl.gramene.org/biomart/martview/): Choose _Plant Genes 60_ -> _Oryza sativa Japonica group genes (IRGSP-1.0)_. Then on the left hand side click on attributes, open the _EXTERNAL_ collapse and check _GO term accession_ and _GO term evidence code_. Then click on _Results_ and you will be presented with some rows of the result, you can download them all as a file as well. Most of those are IEA but some are also of higher confidence. You can _Filter_ through biomart or using the file after you downloaded it with grep etc. We have not compared our dataset yet to those annotations but are planning to do so for the publication.
- Wheat: There are some limited attempts at creating IEA annotations ( https://doi.org/10.1186/s12864-015-1496-2 , http://doi.org/10.1093/database/bat014 ) but I am not aware of another genome-wide annotation set or a gold standard.

**Mapping to Other Databases**
This is probably the most annoying part, and we actually have someone in our lab working on a pipeline to create such mappings.
- Maize: MaizeGDB publishes [a mapping](https://www.maizegdb.org/search/gene/download_gene_xrefs.php) across its different genomes and that also includes an Entrez column. I have not really looked into that, though; @wkpalan do you know of any mappings to external databases?
- Rice: Again, through Biomart, you can get external references (PDB ID, BRENDA, NCBI ...), also in Attributes -> External.
- Wheat: I am not aware of any, unfortunately.

**Comment by suzialeksander** [comment]
@Thyra, one of the main requirements is for all annotations to be traceable back to a record, specifically, a UniProt accession- do you have immediate plans to submit any/all of these sequences to UniProt (or NCBI)?

**Comment by Thyra** [comment]
The gene model sequences were not generated by us so we won't submit them to UniProt, but it seems that at least for some genomes mappings between our gene names and UniProt IDs exist on [Gramene Biomart](http://ensembl.gramene.org/biomart/martview/), e.g. for rice (Choose _Plant Genes 60_ -> _Oryza sativa Japonica group genes (IRGSP-1.0)_. Then on the left hand side click on _attributes_, open the _EXTERNAL_ collapse and check the UniProt IDs. Then click on _Results_ and you will be presented with some rows of the result, you can download them all as a file as well):

![Screenshot from 2019-04-09 15-00-31](https://user-images.githubusercontent.com/15807779/55831281-5b238100-5ad8-11e9-85f9-6ad3bb6c1888.png)

I would have to inquire where they come from to make sure they are reliable and refer to the same assembly for each of the genomes but given that's the case, would that fulfill the requirement?
