### ISSUE TITLE
GO enrichment with filtered reference gene list

### ISSUE THREAD

**Issue by gabriella-quinn** [geneontology/helpdesk#197]
Hi, 

I am working with differentially expressed gene from the Homo sapien reference. When calculating DEG's I first filtered for genes with a low read count and then continued looking at fold change and corrected p values from this filtered list (11,149 genes from the initial 24,381)

When doing a GO enrichment on the downregulated or upregulated genes from this analysis would my reference list be the list of genes captured by sequencing (24,381) or the list of genes after the filtering for low read count (11,149).

Thank you for your help.

**Comment by suzialeksander** [comment]
@huaiyumi or @thomaspd can you provide an answer?

**Comment by huaiyumi** [comment]
Should use all the genes from the experiment.

**Comment by suzialeksander** [comment]
Hi @gabriella-quinn, I'm closing this as answered.  Please let us know if there's anything else we can help you with, and thanks for getting in touch with us.

**Comment by gabriella-quinn** [comment]
That answer was informative.

Thank you!
