### ISSUE TITLE
Release information for the GO annotations in the NCBI Gene tool

### ISSUE THREAD

**Issue by LorraineW01** [geneontology/helpdesk#199]
Dear GO Team,

I write you because I am not sure which GO ontology release was provided during the NCBI Gene search during the 22th of February and the 7th of March this year.
After asking the NCBI Help Desk I was informed that the provided GO release is updated on a daily basis.

Have you a accessable release update overview table for the corresponding time period which I can use or maybe tell me which GO release version was run at the time, please?

Thanks in advance for any kind of help!

Sincerely,
Lorraine Weidner

**Comment by suzialeksander** [comment]
Hello @LorraineW01, 

It looks like searches run on those two dates both use the 01 Feb 2019 release (we had a hiccup that delayed the March release).

The official releases for those dates are available on Zenodo: https://zenodo.org/record/2598349 or even https://zenodo.org/search?page=1&size=20&q=conceptrecid:%221205159%22&sort=-version&all_versions=True

The blue info bar has the original date for the first GO upload to Zenodo (July 2, 2018) for all files, immediately followed by the release date (eg (2019-03-18) was the release on the 18th of this month).

You can also find these dates at http://release.geneontology.org/, but this page doesn't contain the individual release accessions (10.5281/zenodo.2555602 for the February release).

Thanks for asking!

**Comment by LorraineW01** [comment]
Hello @suzialeksander,

thanks, the detailed information helped me a lot!

**Comment by suzialeksander** [comment]
Great! Let us know if there's anything in the future we can help you with. Thanks for contacting GO.
