### ISSUE TITLE
Panther tool includes NOT annotations in enrichment

### ISSUE THREAD

**Issue by rachhuntley** [geneontology/helpdesk#2]
Hello,
I recently noticed that several term enrichment tools are including NOT annotations in their enrichment, Nancy and I between us have contacted g:Profiler, DAVID and ClueGO who are working to remove these annotations. I also tried this on Panther and it seems this too also includes NOT annotations in the enriched set as if they are positive annotations.

I used the protein list copied below. Out of four AGO proteins, only AGO2 (Q9UKV8) is capable of mRNA cleavage and so is annotated to “mRNA cleavage involved in gene silencing by miRNA”. AGO1, 3 and 4 (Q9UL18, Q9H9G7, Q9HCK5) are annotated to the same term but with a NOT qualifier.

I've attached screenshots of the original annotations and the Panther enrichment of this term.

[AGO_Annotation.pptx](https://github.com/geneontology/helpdesk/files/813421/AGO_Annotation.pptx)

Q9NRR4
Q8WYQ5
Q9HAV4
P62826
Q9UPY3
Q15633
O75569
Q9UL18
Q9UKV8
Q9H9G7
Q9HCK5

I apologise if this is a known issue, but if we're telling other tools they should ignore NOT annotations then the GOC should also be doing this.

Thanks,
Rachael.

**Comment by kltm** [comment]
PANTHER question, so probably @mugitty. Maybe better on PANTHER tracker?

**Comment by rachhuntley** [comment]
OK, I didn't know there was a Panther-specific tracker. I have added it there instead and will close this ticket.
See https://github.com/geneontology/panther-enrichment/issues/4

**Comment by kltm** [comment]
@rachhuntley No problem that's what the helpdesk is here for ;)
We still trying to work out how we should do this as well, so there will be a period of adjustment.
