### ISSUE TITLE
unable to download monthly release as termdb

### ISSUE THREAD

**Issue by sgrote** [geneontology/helpdesk#200]
Hi all, 
in [FUNC](https://www.ncbi.nlm.nih.gov/pubmed/17284313) and it's R-wrapper [GOfuncR](http://bioconductor.org/packages/release/bioc/html/GOfuncR.html) we use the GO termdb tables.
I usually download the latest version from here:
http://archive.geneontology.org/latest-termdb/go_daily-termdb-tables.tar.gz
However, in the README there it says:
> For a release that is manually QC'd, see the monthly download area

However, I was unable to find the monthly release in the termdb tables format and
http://archive.geneontology.org/latest-full/ seems to be outdated.
I hoped a monthly release would still be provided since there is still an up-to-date daily build in that format.
Sorry if I missed something obvious.

Cheers,
Steffi

**Comment by suzialeksander** [comment]
Hi @sgrote,
Thank you for contacting us, and apologies for the misleading documentation.  We're in the process of moving away from MySQL permanently; we strongly recommend users shift away from the MySQL dumps as soon as possible.  

Until we finish the transition to Blazegraph on our end, the file you are looking for will be available at  http://archive.geneontology.org/lite/

> As well, from #140 :
> 
> The legacy systems (mainly the pipeline and delivery of the MySQL, mentioned in #4 ) are being decommissioned as they fail or no longer become viable. The new system is in various states of readiness, with the rdf endpoint (rdf.geneontology.org) being largely ready to use, with the peripheral query interface and documentation still being built up.
> A couple of good places to start with the new system would be:
https://github.com/geneontology/go-site/blob/master/graphstore/triplestore_info.md
With some templated examples here:
https://github.com/geneontology/sparqlr/tree/master/templates
> We're currently working on more documentation and introductions. Our apologies for the awkward transition period.


Please also look at https://github.com/geneontology/helpdesk/issues/4 for a little more info on the transition.

If you need more info than this please let us know.

**Comment by sgrote** [comment]
Thank you for the quick response and the clarification.
