### ISSUE TITLE
Changes to Gene Annotation File Names

### ISSUE THREAD

**Issue by jernst98** [geneontology/helpdesk#202]
The naming of annotation files available at this URL http://www.geneontology.org/gene-associations/ has changed and is breaking software I have written.
For example there use to be a file named gene_association.PAMGO_Oomycetes.gz, but that is no longer the case.
I can still see the file with the naming my software is expecting at this URL
ftp://ftp.geneontology.org/pub/go/gene-associations/

Note that http://www.geneontology.org/gene-associations/  now redirects to
http://current.geneontology.org/annotations/
My software can handle the redirection, but can't handle the naming of the files.

Would it be possible to still have files with the old naming at one of those two http locations?
I can update future releases in my software, but I do not have a way to update it for the many users that have already downloaded the software I have written.

**Comment by suzialeksander** [comment]
Hi @jernst98, Sorry for the delayed response- most of the GO members are at Biocuration and then the GO Conference this week.  We'll get back to you as soon as we can, I expect by the end of this week.  Just letting you know we haven't forgotten your question, we are just trying to get as accurate and informative answer as possible for you.

**Comment by suzialeksander** [comment]
Hi @jernst98 

We have renamed the files in order to clearly differentiate GAF files from GPAD and GPI files. We apologise that this has caused a problem with your software. We are also planning on shutting down the FTP site when we are confident in the stability of current.geneontology.org and notified our users of the change.
We don't have a way to support the older file nomenclature, but suggest users update their versions with your next release.  

Again, apologies for any difficulties this may have caused.

**Comment by jernst98** [comment]
What URLs and file naming is there currently a commitment to keep stable and which ones are subject to change going forward?

**Comment by suzialeksander** [comment]
Hi @jernst98, for the foreseeable short-ish term (1-2 years+), we believe the current.geneontology.org/ URL and the filenames you see on http://current.geneontology.org/annotations/  
(So, the GROUP.gaf file will be reliable and regularly updated, not the gene_association.GROUP file).  

We have discussed adding PURLs for the annotation files, but there is no working group currently assigned to implement those.  We cannot guarantee these filenames will remain the same permanently, but we are certainly not going to change the names again unless it is absolutely necessary.  We recognize that many of our users are in similar situations to yours, and again apologise for the difficulty during this transition.  We will do our best to notify users in advance of any further infrastructure changes like this that may affect external tools.
