### ISSUE TITLE
Dead link on GO homepage (cog2go)

### ISSUE THREAD

**Issue by davidbio** [geneontology/helpdesk#203]
There is another deadlink for the cog2go mapping text file:
http://geneontology.org/external2go/cog2go

The dead link can be found on this page:
http://geneontology.org/docs/download-mappings
-> COG functional categories

**Comment by suzialeksander** [comment]
Hi @davidbio, 

Thank you for finding this and letting us know you're looking for this file. We're currently trying to track down this file, I will update this when we have any news.  We apologise for this disruption.

**Comment by suzialeksander** [comment]
This link was removed as it doesn't look like we can replace it with a working link.
