### ISSUE TITLE
Create template for new users

### ISSUE THREAD

**Issue by pgaudet** [geneontology/helpdesk#204]
As indicated here: 

http://wiki.geneontology.org/index.php/Documentation_for_New_Members#Checklist_for_all_Gene_Ontology_Consortium_Members_and_Contributors

Create a ticket in the Helpdesk repo to request to (please copy the following list in the ticket):

    Be invited to the Gene Ontology Project: Please mention your role: Biocurator, software developer or domain expert.
    Get access to GO google drive: Please provide the email account you want to use
    Be added to the GO Google calendar, so you can view conference call information
    Be added to Group contacts: Please provide your expertise (1-3 keywords) and
    Be added to Users: Please provide your ORCID, the name of your organization, and group.

**Comment by suzialeksander** [comment]
addressed in https://github.com/geneontology/helpdesk/pull/210
