### ISSUE TITLE
API for Panther Enrichment?

### ISSUE THREAD

**Issue by duncster94** [geneontology/helpdesk#205]
Hello, I was wondering if there is an API for programmatically running Panther GO enrichment tests. I'm developing a small web application for a few people in my lab.

Failing this, is there any GO enrichment tool that has an API?

Thanks for the help.

**Comment by mugitty** [comment]
You can invoke PANTHER web services programmatically.  There is documentation from http://pantherdb.org/help/PANTHERhelp.jsp#V.E.

We will be releasing a version that confirms to Open API Version 3 in the future.

**Comment by duncster94** [comment]
Great, thanks for the extremely quick response!

**Comment by duncster94** [comment]
On that note, I've been using the API successfully for a number of days but as of ~Thursday last week the API returns `null` for any request I send. It's not an issue on my end since I'm using Postman to send the exact same request that was successful last week.

Any ideas?

**Comment by mugitty** [comment]
Can you send the code that is being used to send the request

**Comment by mugitty** [comment]
There was a server casting issue.  It has been resolved.
