### ISSUE TITLE
accessing all annotated GO terms IDs (Including ancestors) for a gene programatically

### ISSUE THREAD

**Issue by ValWood** [geneontology/helpdesk#22]
One of our users  has asked how to do this as part of some protein-protein interaction prediction method.

I have seen it answered previously on the GO helpdesk more than once but I don't see it in the FAQ . Could it be added?

Thanks,

VAl

**Comment by ValWood** [comment]
Hi,

Can anyone help with this? @cmungall 
I know I have seen this question answered on Jira, but I don't think this archive is available.

The user has mailed our helpdesk again, and I am on vacation so I don't want it to slip through the cracks.

The user mentioned using python.... but I guess  any  method would do...

**Comment by cmungall** [comment]
python, perfect. We can demonstrate this with a notebook like this: https://github.com/biolink/ontobio/blob/master/notebooks/Remote_Ontology.ipynb

I'd like to build up a large library of these notebooks as part of our FAQ (and they can easily be replicated as simple scripts). 

@dougli1sqrd can you take this one? I can help. Let's do PomBase:SPBC11B10.09 as our example. I'll start it off.

**Comment by cmungall** [comment]
Don't send it out yet, first pass: https://github.com/cmungall/go-notebooks/blob/master/Annotations_for_a_Gene.ipynb

**Comment by ValWood** [comment]
I told our user to follow this ticket so I can close in our help-desk.

I had a look at the first pass. That looks OK for cdc2 (direct only?)

Notebooks sound cool....
Happy to check any examples.

**Comment by kltm** [comment]
@cmungall @dougli1sqrd We should open a ticket for this item in the appropriate tracker and close this one out.

**Comment by kltm** [comment]
@cmungall @dougli1sqrd I'll close it out here, you can use issue mover to get it reopened in the right tracker.
