### ISSUE TITLE
Some terms are not listed as children in their parent terms

### ISSUE THREAD

**Issue by zhuying912** [geneontology/helpdesk#220]
For example, GO:0016765 is a parent GO:0019007, but GO:0019007 is not in the children list of GO:0016765. I actually found many of these cases when going down from level-0 terms. Is it intentional or by mistake? If it is by mistake, would you please fix? Thank you!

**Comment by kltm** [comment]
@zhuying912 Looking at what is currently in AmiGO, things seem to be in order:

http://amigo.geneontology.org/amigo/term/GO:0016765#display-lineage-tab
http://amigo.geneontology.org/amigo/term/GO:0047444#display-lineage-tab

Noting that GO:0019007 was replaced by GO:0047444.

If you are still having problems, can you state where you are having this issue?

**Comment by pgaudet** [comment]
Hi @zhuying912,  
GO:0019007 was merged into GO:0047444; could this be the problem ? 

Thanks, Pascale

**Comment by suzialeksander** [comment]
Marking as stale, @zhuying912 if you're still having this issue can you please provide the requested information above:

> can you state where you are having this issue?
