### ISSUE TITLE
How to make custom GO graph?

### ISSUE THREAD

**Issue by lawchen** [geneontology/helpdesk#222]
Dear GeneOntology Helpdesk,

I'd like to create something like a GO graph but only with select terms that I received in an enrichment analysis. Perhaps even better (or as an option), the non-selected GO terms that should fill in the gap between branching terms could be filled in or indicated somehow. This would help me visualize the parent and child terms from a list of significantly enriched processes, as well as which would be independent/standalone terms.

That's just an idea, but do you know where I can find a GO tool to make a graph like that, or a tool that can help me visualize the branching terms from a select list of GO terms?

If there's none, could you advise an easy way to create a table for a list of select GO terms (e.g., 10 to 50 terms) such that each term has info about their direct parent term(s) and child term(s)? I would like to avoid manually searching through each one on the website.

Thank you,
Lawrence

**Comment by kltm** [comment]
@lawchen 

From the AmiGO tools page, you may want to start with the visualizer:

http://amigo.geneontology.org/visualize?mode=client_amigo

There may also be features in command line tools such as ROBOT (https://github.com/ontodev/robot#term-lists https://github.com/ontodev/robot/blob/master/docs/extract.md) that could be of use as well. @cmungall May have more information.

**Comment by cmungall** [comment]
Unfortunately ROBOT does not yet have the complete behavior, as it will only gap fill using is-a. You can follow the ticket to fix this here: https://github.com/ontodev/robot/issues/497

For now you can use owltools. This will work file, although owltools is overall a much more idiosyncratic command line tool to use.

You would do it like this:

```
owltools go.obo --extract-ontology-subset -i my_ids.txt -o -f obo myslim.obo
```

Where the txt file is a newline separated list of GO IDs

You can find information on how to obtain owltools here: https://github.com/owlcollab/owltools/

(it's a bit harder than robot, sorry)

**Comment by suzialeksander** [comment]
marking as stale, as this looks like there are solutions provided; @lawchen if you need more information please let us know.
