### ISSUE TITLE
Genes annotated to GO term, filtering by species

### ISSUE THREAD

**Issue by vd22** [geneontology/helpdesk#225]
I am attempting to find all the human genes annotated to a particular GO term (e.g., B cell proliferation, GO:0042100). I know how to search for this (i.e., search for "B cell proliferation", clicking "link" to all genes and gene products annotated to B cell proliferation), and filtering by Homo sapiens under "Organism." 

My question is whether the filtering by Homo sapiens step filters only for genes for which there is evidence in **human cells** of B cell proliferation, for example, or whether it filters for all genes implicated in B cell proliferation, regardless of species/experiment/prediction algorithm, and then filters only for genes/homologues that exist in humans? Or is it doing something else?

Thank you!

**Comment by suzialeksander** [comment]
Hi @vd22, 
The GO annotations as supplied through AmiGO contain a basic core of information: 

- the exact gene or gene product (e.g. protein) the annotation applies to
- a GO term to describe the function
- the reference/literature used to assign the GO term
- a code to describe how the reference supports the GO term (evidence)

Most annotations contain more information too- but the point is the GO term is tied directly to the protein.  Therefore, when you search for GO:0042100 B cell proliferation and constrain the results to Human, the results will all be human proteins that were annotated to GO:0042100 (directly, or indirectly, depending on if you selected "GO class" or "GO class (direct)".

One evidence code (IBA, Inferred from Biological aspect of Ancestor) used by PANTHER indicates the annotation used phylogenetic analyses to transfer annotations amongst related sequences based on common ancestry- for more information on these please see https://www.ncbi.nlm.nih.gov/pubmed/21873635.

Rarely, some experiments may be done in another organism (eg, mouse), with the *express intent* that the experiment models human biology, and a curator may annotate the human homolog.  This is rare, and only done by some of the most experienced curators in the Consortium.

**Comment by suzialeksander** [comment]
closed due to inactivity; @vd22 if you have further questions please let us know.
