### ISSUE TITLE
EcoCyc GAF GO data

### ISSUE THREAD

**Issue by kltm** [geneontology/helpdesk#227]
The following message came in on the helpdesk:

===

I was trying to work with the GO annotation provided for E.coli via
your website, the file
http://current.geneontology.org/annotations/ecocyc.gaf.gz

About 1900 gene identifiers used therein appear to be EcoCyc-internal gene identifiers. Are you aware of a simple and publicly available mapping of these IDs to other gene IDs?

EcoCyc has flat files for download, but it requires to go through a licensing agreement. I am an academic researcher, so it would be free. However, for the sake of reproducability, I  like to base my analyses on publicly available data. In this case it is really just a gene identifier mapping. If this is not available I can unfortunately not use your E.coli annotation file.

**Comment by kltm** [comment]
@vanaukenk The core issue here seems to be the mapping of EcoCyc IDs to a different space.

**Comment by vanaukenk** [comment]
@kltm 

UniProt hosts an ID mapping service here, but I don't see EcoCyc gene identifiers as a possible input value:
https://www.uniprot.org/uploadlists/

Tagging @huaiyumi and @thomaspd to see if PANTHER has any tools for this or they have other suggestions.

**Comment by vanaukenk** [comment]
Also tagging @jimhu-tamu to see if he can help, too.

**Comment by kltm** [comment]
@vanaukenk As a possible step forward, for the primary gene product identifier, there is EcoGene and UniProtKB in that file. I tried to put the former through the UniProt service that you have above (EcoGene is available in the dropdown) and was apparently able to map all but two:
https://gist.github.com/kltm/1e4b5a256e5815ef87b203b8255bf1fd

**Comment by kltm** [comment]
As long as I'm here, here's the TSV/tab output of that: https://gist.github.com/kltm/15508ba4d8e889fc6c6a1bbcef0a691d

**Comment by cmungall** [comment]
I believe this is a temporary issue. Note that IDs from the EcoCyc file have been a longstanding issue. There should be no reason to mix gene IDs and protein IDs in col2 in a GAF.

Here is the ticket:
https://github.com/geneontology/go-site/issues/969

However, it seems this has been fixed upstream:

```
$ curl -L -s https://ecoliwiki.org/gaf/gene_association.ecocyc.gz | gzip -dc | grep -v ^UniProtKB
[no output]
```

So this should be fixed next release. 

**IMPORTANT NOTE** This ecocyc file we pull is still lacking interpro2go and hamap annotations!!! https://github.com/geneontology/go-site/issues/1142 this is a serious omission!!!

**Comment by cmungall** [comment]
Note I wouldn't point this user at the source file as this doesn't have IBAs integrated.

It looks like the pipeline is still sticking as snapshot doesn't reflect any changes yet, ugh, I say just see if the user can hold off til next release

**Comment by kltm** [comment]
@cmungall `snapshot` passed a couple of days ago and today, so what new product should look like should be available. If it's not looking right at this point, there's something else going on.

**Comment by cmungall** [comment]
ARGH!! I spoke too soon. @dustine32 we need to switch PAINT to exporting UniProtKB IDs, not gene IDs. 

ftp://ftp.pantherdb.org/downloads/paint/presubmission/gene_association.paint_ecocyc.gaf.gz uses EcoGene IDs.

**Comment by cmungall** [comment]
Here is the ticket: https://github.com/pantherdb/fullgo_paint_update/issues/29 @dustine32 is there any hold up on this? Note the E vs EG is now moot, paint_gaf needs to start using UniProt IDs since that is what UniProt is producing.

**Comment by suzialeksander** [comment]
It looks like this issue was resolved, based on https://github.com/pantherdb/fullgo_paint_update/issues/29

and a cursory glance at the 2019-10-07 ecocyc.gaf

Closing.
