### ISSUE TITLE
Access denied on a public URL

### ISSUE THREAD

**Issue by tedgoldstein** [geneontology/helpdesk#23]
Click on http://www.geneontology.org/page/tools   (which is a link on the site)
result is

Access denied
You are not authorized to access this page.

Expected result:  a nice web page describing all the wonderful third party tools or a message saying that this is now discontinued and the user should search at ....

Ted

**Comment by kltm** [comment]
@tedgoldstein 

Thank you for pointing this out. Unfortunately, that URL went stale a long time ago; would you know where in the documentation you found it?
We've updated the URL to redirect to a page that briefly discusses the discontinuation of the GO Tools Registry.

Thank you for your help!

**Comment by kltm** [comment]
My apologies, to further clarify, at this time, the GOC does not make explicit recommendations about tools or the best ways to find them. The best path forward on this is under discussion.
