### ISSUE TITLE
assigning functions to protein domains

### ISSUE THREAD

**Issue by sghazanfari** [geneontology/helpdesk#230]
Dears,

I want to find the functions of protein domains. As I read in FAQs, It is possible to find it in your website. However after searching a lot, I couldn't find it.
I would appreciate If you can help me on this.

Thanks,
Sara, Bioinformatics student

**Comment by suzialeksander** [comment]
Hi Sara, 

Thank you for writing in to the GO helpdesk.  Are you looking for existing data, where others have already annotated specific proteins based on the presence of specific domains, or are you trying to do the annotation yourself? If you're looking for existing annotations, try the AmiGO browser (http://amigo.geneontology.org/).  I recommend you find annotations you want by filtering for annotations based on sequence similarity evidence, the ISS evidence code.  Other computational evidence codes may also be of interest.  See http://geneontology.org/docs/guide-go-evidence-codes/ for more evidence code info.

If you're looking to do the annotation yourself, you will likely need to use an external tool specific to your goals.  You may want to look at existing literature to decide on the best method for your purposes.

I hope you find this information helpful.

**Comment by sghazanfari** [comment]
Thanks for your answer.
I just need to find the annotation for protein domains, not for proteins.
Could you help me find it?

**Comment by suzialeksander** [comment]
@sghazanfari, although Gene Ontology can and is used to assign functions to domains, the annotations maintained by the GO are gene-product centric (typically proteins) as the ultimate purpose of the GO is to describe gene function.  We do not produce or maintain information about protein domains in isolation; that is, you'll need to look up a representative protein and view the annotations that have been made based on sequence, modeling, or other domain-based reasoning.  See http://geneontology.org/docs/guide-go-evidence-codes/ for more evidence code info.

As the GO data and data products are licensed under the Creative Commons Attribution 4.0 Unported License, and therefore open for use by outside groups, it is quite possible there is a database that uses the GO to store information about domains, but that information is not in the GO database as an official GO product.  

I hope this answers your question.

**Comment by srengel** [comment]
http://current.geneontology.org/ontology/external2go/interpro2go

**Comment by sghazanfari** [comment]
Thanks suzialeksander for your kind help.
Thanks Stacia for your exact answer 👍

**Comment by suzialeksander** [comment]
@sghazanfari if this answer worked, we can close this ticket- or was there was something else?
