### ISSUE TITLE
secure, authenticated downloads (`https`)

### ISSUE THREAD

**Issue by dlaehnemann** [geneontology/helpdesk#231]
From what I can see, all the current download links are `http` (<http://geneontology.org/docs/download-ontology/>). It would be great if a secure and authenticated download via `https` was available (and the default), to protect against any possible tampering during the file transfer.

For background, e.g. see:
<https://en.wikipedia.org/wiki/HTTPS>

**Comment by suzialeksander** [comment]
Hi @dlaehnemann, that's a good suggestion.  I believe we are already working on trying to implement something like this, but it will take quite a bit of time to change everything over.  

In the meantime, you may be interested in using our Zenodo releases, which are secure: See our October 2019 release at https://zenodo.org/record/3477535

**Comment by dlaehnemann** [comment]
Hi @suzialeksander ,

that's a cool resource, indeed. But for our current use case we don't need the full gene ontology but only go-basic. But as a reference resource to download once and share across users, that's definitely useful. Will keep in mind! Thanks again!

**Comment by suzialeksander** [comment]
For the record, this has come up again from a different source; a DCC user has noted because their systems are behind a https, they cannot download from a http site.  Not sure how common this is?

**Comment by kltm** [comment]
@suzialeksander For the ontologies, that's an ontology and obolibrary issue, not completely a "GO" one. This is further exacerbated by the fact that the OWL world treats a URL that is only different in the scheme as a different entity--you can see how this is ripe for confusion if not everybody is on board the same way. (@cmungall if a reality check is needed here)

That said, this should only be a thing when somebody is trying to get something hot within a web application based on HTTPS (good overview: https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content); this is not something that's an issue for download and pipeline users, for example. Until a better solution is found, an alternative could be to use the current.geneontogy.org or release.geneontology.org files, which we could work towards supporting HTTPS as well. (Well, they support HTTPS *now*, but the cert they are using would likely cause issues with most browsers.)
