### ISSUE TITLE
New releases not on FTP server?

### ISSUE THREAD

**Issue by rudolfsberzins** [geneontology/helpdesk#232]
Hi,

I have recently noticed that the go.owl file available on your FTP server (ftp://ftp.geneontology.org/pub/go/ontology) has not been updated since 20/09/2018. Is this an overlooked mistake or is there another FTP server where I could get access to newer versions of GO in OWL format? I understand that your site has a download section, but is there a dedicated FTP site for it?

Best, 
RB

**Comment by suzialeksander** [comment]
Hi @rudolfsberzins, 

Thanks for contacting the GO Helpdesk.  We are in the process of migrating away from FTP and SVN, so the FTP site is no longer being updated. You can find newer files at release.geneontology.net; the OWL files will be in the ontology directory. 

I hope this is useful.  Let us know if there's anything else we can help with.

**Comment by rudolfsberzins** [comment]
Hi, 

Thanks for the answer! I think that the url you provided is incorrect. It should be release.geneontology.org. Anyway, i will be using it from now on.

**Comment by suzialeksander** [comment]
Fixed the URL, no idea where I got the .net from.  Thanks for pointing it out.
