### ISSUE TITLE
Are the GO databases under maintenance?

### ISSUE THREAD

**Issue by AshYao** [geneontology/helpdesk#233]
Dear GO team:

I found the GO databases(ftp://ftp.geneontology.org/pub/go/godatabase) haven't been updated since 2019-07-06. However, the newest version of Uniprot had just published in Oct. 16. Are the databases under maintenance?

I had tried to check the "full documentation" page(http://www.geneontology.org/GO.database.shtml) in the README file, but the page doesn't exists any more. 

P.S. I also found that only very small database files are provided in the ftp between 2019-02-02 and 2019-04-06. Was that intended?

Thanks,
Shuwei Yao, Bioinformatics student

**Comment by suzialeksander** [comment]
Hi @AshYao, 

Thanks for contacting the GO. The following are archived: 

-     CVS repository
-     FTP site
-     SVN access

Please use http://release.geneontology.org/ or Zenodo (https://zenodo.org/record/1205166).  If you need something specific you can't locate in the provided locations, please let me know.

**Comment by AshYao** [comment]
> Hi @AshYao,
> 
> Thanks for contacting the GO. The following are archived:
> 
> * CVS repository
> * FTP site
> * SVN access
> 
> Please use http://release.geneontology.org/ or Zenodo (https://zenodo.org/record/1205166) for current or recent releases. If you need something specific you can't locate in the provided locations, please let me know.

Dear @suzialeksander,
I want to download assocdb like go_weekly-assocdb-tables.tar.gz(ftp://ftp.geneontology.org/pub/go/godatabase/archive/lite/2019-07-06/go_weekly-assocdb-tables.tar.gz) but I can't find it on the new websites.
Can you help me with this?
Thanks,
Shuwei Yao

**Comment by kltm** [comment]
@AshYao,

MySQL database dumps are no longer provided, as we have been moving away from that format/system for some time. For more detail, I would point you to a couple of previous discussions:
 
https://github.com/geneontology/helpdesk/issues/200
https://github.com/geneontology/helpdesk/issues/140

**Comment by AshYao** [comment]
@kltm 
Thank you so much for your kind reply, but I still have a question:  now that FTP site is archived, how can I find the new "gp2protein" files(ftp://ftp.geneontology.org/pub/go/gp2protein/) in the future? There are only "external2go" files on http://release.geneontology.org/.

**Comment by kltm** [comment]
@AshYao 

Currently, we do not have a pass-through for the gp2protein data. There is a discussion of how these files came to be discontinued starting from here: https://github.com/geneontology/go-site/issues/1071#issuecomment-488509360

We still do however mark the upstream information. Currently, there is `type: gp2protein` information in the following files:

metadata/datasets/fb.yaml
metadata/datasets/pombase.yaml
metadata/datasets/goa.yaml

**Comment by suzialeksander** [comment]
@AshYao, we have made announcements on our GO-friends mailing list, facebook, and twitter that we are retiring the gp2protein files.  If this message has not been brought to your attention yet, and you still use these files, please let us know and we can help you learn to use the GPI files.

>  Dear GO Friends,
> 
> The GOC would like to retire the gp2protein files that map gene identifiers from databases, e.g. MGI or WB, to the canonical reference protein in UniProtKB.
> 
> These files have been generated by groups contributing annotations to the GOC.
> 
> We plan to retire these files in ~ one month's time, February 15th.
> 
> We encourage anyone who may still be using these files to contact us (help@geneontology.org) to discuss alternative ways of obtaining these mappings (e.g. gene production information (gpi) files).
> 
> You may also comment on the corresponding github ticket:
> 
> geneontology/go-site#1324
