### ISSUE TITLE
http://www.pantherdb.org/ - Maximum number of sessions exceeded

### ISSUE THREAD

**Issue by iansealy** [geneontology/helpdesk#234]
Hi,

(This is similar to issue #122, so I'm hoping this is the right place to report it.)

We're doing some training this week at EMBL-EBI, including using http://www.pantherdb.org/. The problem is, all 30 computers in the training room share the same IP address, so once a few of the students go to http://www.pantherdb.org/ they get a message saying that the maximum number of sessions has been exceeded. I totally understand that this is to prevent accidental (or deliberate!) denial of service, but is it possible to add an exception for specific IP addresses? Thanks in advance.

Cheers,
Ian

**Comment by suzialeksander** [comment]
Paging @mugitty @huaiyumi

**Comment by mugitty** [comment]
I have increased both maximum number of sessions for a given IP address and the maximum number of concurrent requests for a given IP address.

**Comment by suzialeksander** [comment]
@iansealy do you have any more upcoming training sessions so we can check that the problem is solved?
