### ISSUE TITLE
Archived versions of GO not changed since 9/20/18

### ISSUE THREAD

**Issue by cpesquita** [geneontology/helpdesk#238]
Dear GO,

I am trying to download an older version of the GO release. In ftp://ftp.geneontology.org/go/ontology-archive/ all versions since October 2018 have 9/20/18 as the Last Modified date, meaning every month since 2018-10 the same version of the ontology is being put in the archive. Did GO really not change during these months or is something else going on? 

Glad for any help you can give me in understanding this situation.

Best,
Catia

**Comment by kltm** [comment]
@cpesquita We are currently transitioning over to a new release and download system, so we unfortunately currently do not have a uniform system for downloading ontologies across the full history of the GO, although we are working towards it (https://github.com/geneontology/go-site/issues/483). With that as context, I can give you an outline of how to get at different ontology versions.

First, we highly encourage authors to cite both the DOI and date of a release (http://geneontology.org/docs/go-citation-policy/). A listing of releases within the new release and download system can be found at http://release.geneontology.org (where the related DOI can be found at, for example, http://release.geneontology.org/2019-11-01/metadata/release-archive-doi.json) or at https://zenodo.org/record/1205166, note that past versions are listed in the lower right and that the "Version" is the release date (as well as the file metadata/release-date.json within a release).

Within these releases, ontology files can be found in ontology/ . As well, for the GO, the versioned file should also be found at official PURL; for example: http://purl.obolibrary.org/obo/go/releases/2019-10-07/extensions/go-plus.owl .

You will note that these new archives only go back to 2018-03-06; before that we used a less formal system. While we are in the process of producing easy-to-use archives for all of our history, as mentioned above, we have not arrived at that state yet. If you are interested in earlier GO files, I would suggest the GitHub repo (https://github.com/geneontology/go-ontology, back to Feb 26th, 2016), and then farther back the old SVN repository (http://geneontology.org/docs/SVN-access/ and http://viewvc.geneontology.org/viewvc/GO-SVN/trunk/).
