### ISSUE TITLE
All GO annotations

### ISSUE THREAD

**Issue by jrr-cpt** [geneontology/helpdesk#239]
If we want to do analyses that include ALL non-IEA GO annotations, can we download and combine the full list of GAFs available [here](http://current.geneontology.org/products/pages/downloads.html) or [here](http://current.geneontology.org/), and effectively create a full, current GO representation?

Looks like this is related to [#4](https://github.com/geneontology/helpdesk/issues/4) and [#133](https://github.com/geneontology/helpdesk/issues/133). Just making sure I understand the list of files. 

@jimhu-tamu @cross12tamu

**Comment by suzialeksander** [comment]
Hi @jrr-cpt, 
If you want all annotations, you can use just the downloads from 
http://current.geneontology.org/annotations/index.html.  
The files on 
http://current.geneontology.org/products/pages/downloads.html 
do not contain any annotations that you would not already have from the
http://current.geneontology.org/annotations/index.html files. 

There is a little more documentation about the pipeline and different URLs here: http://wiki.geneontology.org/index.php/Release_Pipeline

Also, if you are not already aware, the documentation about our Zenodo downloads at http://geneontology.org/docs/tools-guide/#programmatic-download-bdbag may be of interest.

**Comment by jrr-cpt** [comment]
Thank you @suzialeksander. I think this answers our questions.
