### ISSUE TITLE
Some Questions About .obo Format Files

### ISSUE THREAD

**Issue by liuzhe93** [geneontology/helpdesk#24]
Dear Professor,
       Hello!
       Now, I research that “Comprehensive Identification of Cell Fate Decision-related ncRNAs in Human”. So far, I’ve read your paper “OBO-Edit—an ontology editor for biologists.”.
       I'm very interested in your work that “OBO-Edit—an ontology editor for biologists.”. For identification of ncRNA (particularly lncRNA and miRNA), we need firstly that systematically select core reprogramming-related transcript factors (TFs). Then, identifying ncRNAs that associated with these TFs. To calculate differential expression genes, I need two classes of sample: the first is case, and the second is control. I want to class samples by cell type's .obo format files.
       However, I don’t know how to operate cell type tree file (.obo format file, ff-phase1-prerelease-20130717.obo). The people around me also did not have the experience of dealing with thus data.
I think it's very helpful for my experiments with your help. Because it’s the beginning of our research. Do you have some recommended software packages or papers for dealing with .obo format files to calculate differential expression for me? It’s not possible to manually handle the cell types, because of the number of human cell types in our research is more than 800.
       I really appreciate your positive response.
      Thank you very much! Good Luck!
Best Regards.
Liuzhe

**Comment by cmungall** [comment]
Liuzhe,

First, I don't think OBO-Edit is useful for your purposes, it's an ontology editor.

Second, it looks like your question doesn't have anything to do with the Gene Ontology, so it's out of scope for this tracker. I'm fairly sure your question pertains to the FANTOM5 sample ontology. It just so happens I am also responsible for this ontology as well as working on GO. However, I'm not sure I'm able to help you here, but some general pointers:

 * the obo file just describes the samples and cell types. Your analysis will require expression data, which is not represented in the obo file
 * there are many software packages for dealing with differential expression data, you might want to look at tools like bioconductor/R
 * we have python packages for working with obo files, see http://ontobio.readthedocs.org -- but this will just help with the ontology files itself
 * you may have more luck asking your question on a general bioinformatics forum like biostars. https://www.biostars.org/

Good luck, sorry I couldn't help more.

**Comment by liuzhe93** [comment]
Dear Professor,
        Thanks for your reply.
        Thank you for your kind help and email. I will try ask some
questions via biostars web site.
        Thank you very much!
Sincerely,
Liuzhe
Key laboratory of RNA biology, the Institute of Biophysics, Chinese Academy
of Science, China.
15 Datun Road, Chaoyang District, Beijing City, 100101, the People's
Republic of China
web site: http://english.ibp.cas.cn/

2017-06-07 9:06 GMT+08:00 Chris Mungall <notifications@github.com>:

**Comment by liuzhe93** [comment]
Thanks for your reply.
        Thank you for your kind help and email.
        Thank you very much!
