### ISSUE TITLE
GO:0140293 missing in gene_ontology_edit.obo.2020-01-01.gz

### ISSUE THREAD

**Issue by moxgreen** [geneontology/helpdesk#241]
I expect the term GO:0140293 (http://amigo.geneontology.org/amigo/term/GO:0140293) to be present in ftp://ftp.geneontology.org/go/ontology-archive/gene_ontology_edit.obo.2020-01-01.gz but I can not find it.

The term is not present neither in .obo file in the ftp://ftp.geneontology.org/go/ontology/ directory.

**Comment by kltm** [comment]
@moxgreen 

Our apologies: for the legacy systems, we're still trying to pull them out of use in a staged manner, that sometimes causes confusion (e.g. https://github.com/geneontology/helpdesk/issues/232). I'll look into how the FTP system is still getting updated; however, it should be considered legacy and not used in most circumstances.

For the official way to access ontology file downloads, please see:

http://geneontology.org/docs/download-ontology/

**Comment by suzialeksander** [comment]
@kltm I know nobody actually reads them, but would it be possible/helpful to modify ftp://ftp.geneontology.org/go/README to strongly suggest people instead go to http://geneontology.org/docs/download-ontology/ ?

**Comment by kltm** [comment]
@suzialeksander I agree, but I'm not even sure where that is at this point--it's not in the svn or anywhere that has "normal" controls that I've been able to find so far. I'm tempted to just declare the FTP site defunct and move the domain to something we create fresh, or to nothing at all. The file you are referencing is already from *2012*, so it's been whacky for some time. It seems like the last thing to update that area properly was in 2016.
