### ISSUE TITLE
ontology snapshot

### ISSUE THREAD

**Issue by ValWood** [geneontology/helpdesk#242]
The ontology  (snapshot) did not update since 28th. Any idea when it will next update?

**Comment by kltm** [comment]
Due to issues with https://github.com/geneontology/pipeline/issues/159 , the `snapshot` has not run since last week. However, it looks like it's doing well now (https://build.geneontology.org/job/geneontology/job/pipeline/job/snapshot/), we'd hopefully have results later this afternoon.

**Comment by suzialeksander** [comment]
@ValWood looks like today’s snapshot also had some issues, so it may take another day or so to resolve those.

**Comment by kltm** [comment]
Currently holding on: https://github.com/geneontology/go-site/issues/1377

**Comment by ValWood** [comment]
Thanks for the update.
v

**Comment by ValWood** [comment]
It didn't seem to work?

**Comment by kltm** [comment]
It starts at midnight PST, and runs for about 20hrs. We'll get the results from our last effort to fix in about six more hours, assuming it gets to the end.
