### ISSUE TITLE
ontology not updated this month

### ISSUE THREAD

**Issue by hattrill** [geneontology/helpdesk#245]
The GO hasn't been updated since 1st Jan 2020

I have checked go-basic and go.obo:
data-version: releases/2020-01-01 

When is the Feb 2020 due?

**Comment by hattrill** [comment]
Can I poke you @kltm - any clue when the next release is due?

**Comment by kltm** [comment]
This month's build was cancelled once. The second built has been approved, but we are currently having some issues with the offsite archive. Likely a day or so.

**Comment by hattrill** [comment]
Thanks @kltm ...the anticipation is killing me!

**Comment by suzialeksander** [comment]
@hattrill I hope you noticed, but we managed to squeak out a Feb release: http://release.geneontology.org/2020-02-26 . Already working on March :)

**Comment by dhimmel** [comment]
Mostly unrelated to this isssue, but I was looking for how to get a stable URL for a given release file. Via the website and google searched, I only found references to http://current.geneontology.org. Looks like http://release.geneontology.org is what I was looking for.

Thanks for these public support issues!
