### ISSUE TITLE
How do I disentangle one species from a multi-species GAF?

### ISSUE THREAD

**Issue by jcrunden** [geneontology/helpdesk#248]
I want to find out how many GO terms have been annotated to the Candida glabrata genome. I have the CDG GAF file, but it covers 14 species.

**Comment by suzialeksander** [comment]
Hi @jcrunden,

If you recently (in the past few years) downloaded a CGD GAF, you should see 

> !gaf-version: 2.1

in the header.  Looking at the file information for that format (http://geneontology.org/docs/go-annotation-file-gaf-format-2.1/), you'll notice the taxon is ALWAYS in column 13.  Some columns may not have data and _appear_ "missing", such as the Qualifier in column 4, but all columns are present and the taxon info is always in column 13.

The header also states 

> ! Organism 2: Candida   glabrata CBS138, genome version: s02-m07-r44, taxon: 284593

Depending on your computing level, you can either 
1) open the GAF in Excel or similar and filter column M for your taxon of choice (likely taxon:284593)
2) filter by taxon using grep in your preferred programming text editor or Terminal if you're on a Mac

Alternatively, as there are fewer that 50,000 annotations, you can download a taxon-specific GAF in your preferred GO browser (please see http://geneontology.org/docs/faq/#what-are-the-differences-between-the-data-available-in-amigo-and-those-on-quickgo)

http://amigo.geneontology.org/amigo/search/annotation?q=*:*&fq=taxon_subset_closure_label:%22%5BCandida%5D%20glabrata%20CBS%20138%22&sfq=document_category:%22annotation%22

https://www.ebi.ac.uk/QuickGO/annotations?taxonId=284593&taxonUsage=exact
