### ISSUE TITLE
Click on "View" button in CAM's card opens a blank page

### ISSUE THREAD

**Issue by kon-rafikov** [geneontology/helpdesk#257]
## Description
Click on "View" button in CAM's card opens a blank page.

## Expected behavior
A page with a graph for selected CAM.

## To Reproduce
1) Go to https://geneontology.cloud/browse
2) In any model's card click "View" button (Open Graph View).
3) It will open a new tab which is empty (example: http://noctua.geneontology.org/editor/graph/gomodel:5e72450500002381)

### CAMs list
<img width="625" alt="Снимок экрана 2020-05-29 в 18 01 53" src="https://user-images.githubusercontent.com/8498865/83274711-ce092300-a1d6-11ea-8259-163629080a42.png">
<img width="2035" alt="Снимок экрана 2020-05-29 в 18 03 43" src="https://user-images.githubusercontent.com/8498865/83274701-c9446f00-a1d6-11ea-8c03-22d68e5c5ad2.png">

---

### Graph page
<img width="1782" alt="Снимок экрана 2020-05-29 в 18 02 22" src="https://user-images.githubusercontent.com/8498865/83274710-cd708c80-a1d6-11ea-921d-56ce2a19d9d2.png">

**Comment by kltm** [comment]
Our apologies for the inconvenience. This is likely related to an electrical outage that is occurring at the LBL site in Berkeley. We have word that this should be fixed today.

**Comment by kon-rafikov** [comment]
Yes, it's accessible now. Thanks for response!
