### ISSUE TITLE
How to find GO ID lineage for each human gene?

### ISSUE THREAD

**Issue by jrxubio** [geneontology/helpdesk#258]
I got the GO IDs of each gene from ensembl. The IDs include molecular functions, process and component etc. associated with each gene. For these tip ID, I would like to find all the ancestral IDs. Where could I download the text files containing such information?
Thanks!

**Comment by suzialeksander** [comment]
Hi @jbmunro, 
If you would like to map the annotations up to an informative but high level term, you can use GO Term Mapper.  This "bins" terms into broad categories.  See more at 
http://geneontology.org/docs/faq/#how-do-i-map-a-set-of-annotations-to-high-level-go-terms-go-slim

If instead you would like to crawl up the ontology from your given term to the root nodes, you can download complete ontology files as OBO or OWL files at 
http://geneontology.org/docs/download-ontology/
http://geneontology.org/docs/go-subset-guide/
