### ISSUE TITLE
tracker update to mailing list

### ISSUE THREAD

**Issue by ValWood** [geneontology/helpdesk#259]
Is the daily tracker update working?
I don't think I have seen this for quite a while. This is how I know if I need to monitor tickets...

**Comment by kltm** [comment]
@ValWood If this is the new GitHub tickets summary email, the email stopped a few months ago, as was announced at the meeting. The machine that used to run it had a failure and the script was not ported as there seemed to be little interest and little feedback after the failure (which was only discovered after the fact). The general feeling seemed to be that interested people could follow activity by subscribing to `go-ontology` and `go-annotation` in GitHub.

The old scripts could possibly be ported to the new pipeline, or a new pipeline could be created for it. Looking into it a little, it looks like you are currently following the `go-ontology` repo/tracker, but not the `go-annotation` one. Is that setup (for `go-ontology` anyways) not sending email for new issues for you?

Tagging @ValWood @ukemi What is the current SOP for users wanting to track activity?

**Comment by ValWood** [comment]
I totally missed that announcement.
I used  the list to know which tickets to follow. Otherwise the GO list is incredibly high traffic (because you receive every post on ever ticket).

**Comment by hattrill** [comment]
I missed that too.
I tried to follow the annotation and ontology tracker, but the amount of notifications was over-whelming.
I liked the digest and found it useful....if the titles were easy to understand, that is!

**Comment by Antonialock** [comment]
I would like a digest too. Like Helen I find separate emails overwhelming and without a digest I feel I miss out on tickets of interest.

**Comment by srengel** [comment]
+1 for a digest email.  not having it has negatively impacted my GO activities.

**Comment by kltm** [comment]
This work is now be tracked here: https://github.com/geneontology/go-site/issues/1530
