### ISSUE TITLE
How to find genes associated with GO Terms from previous release (GO Ontology database  Released 2019-10-08)

### ISSUE THREAD

**Issue by jhattz** [geneontology/helpdesk#260]
I performed a Panther GO enrichment analysis several months ago and exported the analysis table. Now I would like to go back and see what human genes were annotated under particular GO terms at the time of analysis  (GO Ontology database  Released 2019-10-08) (this has changed slightly since then). Is there a way to access archived GO Terms from this release?

**Comment by suzialeksander** [comment]
Hi @jhattz, 

If you look on http://release.geneontology.org/2019-10-07/annotations you will be able to find the annotations for the 2019-10-07 release, which I suspect is the one you're looking for.
