### ISSUE TITLE
GO term to genes

### ISSUE THREAD

**Issue by bsmith030465** [geneontology/helpdesk#263]
Hi,
I looked through the FAQ, but couldn't find the right answer. My question is, after submitting a gene list to GO, the results say that 'x' number of genes mapped to a particular GO Term; how do I find the gene symbols for these 'x' genes?

For example, on the GO page (http://geneontology.org/), if I go with the 'examples' gene list, and click on launch, the results page shows:

"vestibulocochlear nerve structural organization | 2 | 2 |  -- | -- | -- | --"

Is there a way to download the details of the two 'significant' genes? The 'export' option gives the numbers, but not the details (e.g. gene symbol) of the genes.

many thanks for your help!

**Comment by chestnzu1** [comment]
Hello:
      I am not from the GO team. But I think I can help you with your problem. According to your question, I think you are doing an Gene Enrichment analysis. After trying the example list, you will get a full list of GO terms that example genes enriched in. In your example, 'vestibulocochlear nerve structural organization' ,at the second column(Column name is 'Homo sapiens(REF') you can click on '2', then you will see the information of genes enriched in this GO terms in detail including their Gene ID. if you wanna download the results of these genes, in the toolbar there is a 'send list to', after select the genes you want to download, you can select send list to TXT for example, and you will get the file. I hope my answer could help you solve your problem.

**Comment by lpalbou** [comment]
Hi @bsmith030465 , sorry for the delay in our response.

Your observation is correct, there is no way to export the list of genes associated to each enriched GO term from the export options (table, xml, json). Only the number of genes enriched will appear in the exports. @chestnzu1 is also correct that while doing the enrichment on the webpage, the numbers are clickable but this is clearly not aimed for large scale analysis or reuse in other pipelines.

We have discussed that issue several times but we don't have a definite resolution yet. I'll raise the issue again at the next manager call.

Additional note: this may not be exactly what you are looking for, but we have started some experiments into producing GMT files (GO term -> list of genes): https://github.com/geneontology/go-site/issues/1536 . This could possibly be used in combination to one of the enrichment export to get the the IDs of the genes enriched for each term.

**Comment by lpalbou** [comment]
**Update**: I just discussed with the Panther team and we already integrated the functionality some time ago.

If you download either the XML or JSON export, you'll get access to the genes (from your gene set) that were enriched for a GO term. Example (see mapped_id_list):

```
{"overrepresentation": {
    "reference": "",
    "upload_lists": {"input_list": {
        "organism": "Homo sapiens",
        "list_name": "upload_1"
    }},
    "tool_release_date": 20200407,
    "data_version_release_date": "GO Ontology database DOI:  10.5281/zenodo.3873405 Released 2020-06-01",
    "annotation_type": "GO biological process complete",
    "correction": "FDR",
    "test_type": "FISHER",
    "group": [
        {"result": [
            {
                "input_list": {
                    "number_in_list": 2,
                    "fold_enrichment": 534.6410256410256,
                    "fdr": 0.0024220395031944613,
                    "expected": 0.0037408277780442184,
                    "pValue": 2.0329050637523195E-5,
                    "mapped_id_list": {"mapped_id": [
                        "NRP1",
                        "VEGFA"
                    ]},
                    "list_name": "upload_1",
                    "plus_minus": "+"
                },
                "number_in_reference": 2,
                "term": {
                    "level": 0,
                    "id": "GO:0038190",
                    "label": "VEGF-activated neuropilin signaling pathway"
                }
            },
...
```
