### ISSUE TITLE
How to query GO graph and all annotations locally?

### ISSUE THREAD

**Issue by hoogla** [geneontology/helpdesk#264]
What is the best way to access the GO graph and all annotations from few species (w.g. human, mouse, fly) in a programmatic way, on a local machine? 

In the past I used to download the full MySQL releases and had my scripts to query the database (e.g. get all annotations for certain proteins or get all proteins annotated with a certain term or a descending term). This was very easy to achieve as there were extensive [example MySQL LEAD queries](https://web.archive.org/web/20161203203055/http://wiki.geneontology.org/index.php/Example_Queries) provided.

Now I understand that the graph store should be the replacement for the full MySQL dump and I would like to see if I can transform my MySQL queries to get more or less the same information via SPARQL from the graph store. But after reading through most of the [issues](https://github.com/geneontology/helpdesk/issues) and the [documentation](https://github.com/geneontology/go-site/blob/master/graphstore/triplestore_info.md), I still struggle to convert my queries (I feel much like @juanjoDiaz throughout his issue [#126](https://github.com/geneontology/helpdesk/issues/126)). Are there any example queries for those rather common questions (e.g. get all annotations with evidence codes for a protein) that one could adapt or extend? The only working examples I could find [here](https://github.com/geneontology/sparqlr/tree/master/templates/website) are more focused on GO contributors and GO-CAMs.

I've also seen the section about [programmatic access to GO](http://geneontology.org/docs/tools-guide/) and was wondering if those tools (GOlr, BioLink) can be installed locally on top of a blazegraph dump? This way I might not need the SPARQL queries but could use the GO API instead.

Thanks a lot for this wonderful resource,
hoogla

**Comment by kltm** [comment]
@hoogla 

It looks like you've gone through most of the relevant documentation. Unfortunately, at this point in time, while we are starting to use the SPARQL endpoint more internally, we still have more work to do to have the same coverage we had with the MySQL dumps for end users. There are a few more examples here https://github.com/geneontology/api-gorest/tree/master/queries . Please do be aware that, as we continue to develop our triplestore, the queries and structures are still subject to change and this is not yet a fully supported final product.

As you point out, we do have blazegraph (http://release.geneontology.org/2020-06-01/products/blazegraph) and solr (http://release.geneontology.org/2020-06-01/products/solr) products available. Blazegraph can be run with just the journal; AmiGO and Solr can be run through docker fairly easily:

``` bash
mkdir -p /tmp/srv-solr-data/index
cd /tmp/srv-solr-data/index
wget http://release.geneontology.org/2020-06-01/products/solr/golr-index-contents.tgz
tar -zxvf golr-index-contents.tgz
docker run -p 8080:8080 -p 9999:9999 -v /tmp/srv-solr-data:/srv/solr/data -t geneontology/amigo-standalone
```

For a local GO biolink instance, you may be interested in looking at: https://github.com/geneontology/biolink-api

For graph reading and access, you may want to check out the ontobio python library https://github.com/biolink/ontobio/ , docs and notebooks.
As well, for programmatic ontology access, I'd also note the GO JSON for the ontology http://release.geneontology.org/2020-06-01/ontology/go.json .

**Comment by hoogla** [comment]
Dear @kltm,

thanks for the quick and detailed reply.  

If I understand you correctly there is currently no way to perform more complex queries against GO data based on some readily available dump? With complex queries I just mean those examples that were provided in the LEAD MySQL page (e.g. "[All genes in Drosophila annotated to 'nucleus' (including transitive indirect annotations)](https://web.archive.org/web/20161203203055/http://wiki.geneontology.org/index.php/Example_Queries#All_genes_in_Drosophila_annotated_to_.27nucleus.27_.28including_transitive_indirect_annotations.29)" or "[Immune response gene products and their associated cell component terms in human](https://web.archive.org/web/20161203203055/http://wiki.geneontology.org/index.php/Example_Queries#Immune_response_gene_products_and_their_associated_cell_component_terms_in_human)").

Are there any time estimates as to when the graph store might be able to support similar kind of functionality and when it will be a documented product?

And thanks a lot for the pointer to [ontobio](https://github.com/biolink/ontobio/). If we have to implement those functionalities "from scratch", it seems like this would be the best way to go, as it provides access to both the GO graph and the associations.

**Comment by kltm** [comment]
@hoogla 

If you are looking for data products that support complex queries of the level that you mention here, the best place to start at this point would be the Solr or Blazegraph data dumps, as mentioned above. I believe that both would be sufficient for these types of queries. The Solr index may be being a little more handy and transparent (if one is used to Solr, basically anything that can be done in AmiGO can be done there, see docker instructions above); the Blazegraph journal should be more flexible and complete. Medium to long term, it is expected that the Blazegraph journal and endpoint should fit the niche that was supported by MySQL in the past. Shorter term, there is an unfortunate gap in the documentation, examples, and immutability of the structures found in the triple store that one may want. While this is something that we are actively working towards, I cannot give any firm dates or timeline at the moment.
