### ISSUE TITLE
no snapshot

### ISSUE THREAD

**Issue by ValWood** [geneontology/helpdesk#266]
Hi,

There has been no snapshot for a while- so we can't annotate to new terms.

Wed Jun 24 00:01:41 PDT 2020

Release notes: https://github.com/geneontology/go-site/tree/master/releases
Branch: snapshot
Start day: Wednesday
Start date: 2020-06-24
Official release date: metadata/release-date.json
Official Zenodo archive DOI: metadata/release-archive-doi.json
Official Zenodo archive DOI: metadata/release-reference-doi.json
TODO: 

thanks

Val

**Comment by kltm** [comment]
@ValWood This is correct, the `snapshot` has been held up on attempts to fix https://github.com/geneontology/pipeline/issues/192 . We may be rolling these fixes back as they hold up the pipeline.
Current progress on snapshot builds can be found here:  https://build.geneontology.org/job/geneontology/job/pipeline/job/snapshot/

**Comment by ValWood** [comment]
@kimrutherford 
@mah11

**Comment by suzialeksander** [comment]
Looks like this has been resolved, so closing.
