### ISSUE TITLE
How to obtain an old GO release with correct/complete information

### ISSUE THREAD

**Issue by allenbaron** [geneontology/helpdesk#267]
This may be related to issues [#241](https://github.com/geneontology/helpdesk/issues/241) and [#232](https://github.com/geneontology/helpdesk/issues/232).

A transcriptomics pipeline I'm using downloaded the go-basic.obo file on 2020-04-30 from (http://purl.obolibrary.org/obo/go/go-basic.obo) but it deleted the file after loading data into a database, without extracting any GO relationship information (`is_a`, `part_of`, _etc_). Now, I want to do some work with the `is_a` relationships. I downloaded the gene_ontology_edit.obo.2020-04-01.gz from the FTP site thinking it would be the same as the original file but it appears to be missing ~160 GO terms which were loaded from the original file. 

I would love to use the most up-to-date GO terms but I have a lot of predicted proteins from blast searches against the 2020_02 release of the SwissProt and UniRef90 databases and I can't redo that. Can you help me find an archived version of GO terms that would best correspond to this UniProt release?

**Comment by suzialeksander** [comment]
Hi @allenbaron, 
According to [Zenodo](https://zenodo.org/search?page=1&size=20&q=conceptrecid:%221205166%22&sort=-version&all_versions=True) as well as our Release directory at http://release.geneontology.org/, it looks like a file you downloaded on 2020-04-30 would have been the 2020-04-23 release, as http://geneontology.org/docs/download-ontology/ points to the current release.  I don't see an official release on 2020-04-01, the previous release was 2020-03-25.  Can you check the 2020-03-25 and 2020-04-23 files from our official sources, either Zenodo or release.geneontology.org?


If neither of these releases has what you are looking for, please let me know and I will dig around a little more.

**Comment by allenbaron** [comment]
Thank you for pointing me to your Release directory. I'm not sure how I missed that when searching your website. It made it possible for me to identify the correct file quickly (without having to wait for huge file downloads from Zenodo). You were right, the 2020-04-23 release was the original one downloaded by the pipeline. Thanks again.
