### ISSUE TITLE
GO Analysis: usage, limitations, validation

### ISSUE THREAD

**Issue by suzialeksander** [geneontology/helpdesk#269]
From Helpdesk email: 

I have a question regarding proper application of GO analysis.  Can you utilize GO analysis from RNA-seq data from an organism where RNA-seq has not previously performed and lacks an extensive database of functional annotation and compare it to human transcriptome data? For example, a pangolin transcriptome compared to human?

Also, what are the major limitation of utilizing this analysis? Would you need to follow up with functional experiments to validate the analysis?

Thanks,
Peter

**Comment by suzialeksander** [comment]
@huaiyumi  @thomaspd can you add anything here?

**Comment by suzialeksander** [comment]
@thomaspd did you have a response for this user?

**Comment by thomaspd** [comment]
There are two approaches we'd recommend for annotating genes in a new genome with GO terms. In both cases you'll need a single representative protein sequence for each protein-coding gene in your organism. Note that GO analysis should generally be performed at the gene level, not the transcript level.
1. if there are GO annotations for a closely related organism, you can use an orthology method (we recommend one of the benchmarked methods in the Quest for Orthologs Consortium, see https://academic.oup.com/nar/article/48/W1/W538/5831173) to identify orthologs. In general, you can safely transfer the annotations from 1:1 orthologs. For pangolin, the mammalian genomes human, mouse, and rat are the best annotated.
2. no matter what the evolutionary relationship to other GO-annotated genomes, you can use the TreeGrafter software to make annotations using the manual GO phylogenetic inference-based annotations, see https://pubmed.ncbi.nlm.nih.gov/30032202/.
