### ISSUE TITLE
Custom Annotation Download Incompatible With Cytoscape BiNGO Plugin

### ISSUE THREAD

**Issue by shir1ey** [geneontology/helpdesk#271]
Hi! I am trying to download a custom annotation for sus scrofa to use in Cytoscape's BiNGO plugin. I downloaded the GAF, GPAD, and GPI files for sus scrofa from Gene Ontology (http://current.geneontology.org/annotations/index.html) however, none of those annotation files could be read or parsed. I also tried renaming the files following the format "gene_association.<provider>" (ie. gene_association.goz_porcine), but this still did not work. I am not sure what I am doing wrong and any help would be appreciated! 

Thanks in advance!

**Comment by kltm** [comment]
@shir1ey 
Apologies that you're having trouble here. Are you able to use your tool with previous releases? For example: http://release.geneontology.org/2020-06-01/annotations/ ?

**Comment by shir1ey** [comment]
@kltm Unfortunately the same error message pops up (picture attached below).

![IMG_9414](https://user-images.githubusercontent.com/68932767/88826195-723b2600-d196-11ea-98f8-21f3ec738edb.jpg)

**Comment by kltm** [comment]
@shir1ey 
Hm, I think that if you are having issues with this and past releases, it might be an issue with tool usage or the tool itself--you might want to try the BINGO developers? It possible that there is a more uniform error in our file creation, but I think it might be useful to see if there might be some other issue in play here.

**Comment by shir1ey** [comment]
Yes, I will definitely check with them. Thank you!
