### ISSUE TITLE
Question- missing header from GAF file

### ISSUE THREAD

**Issue by prasad-693** [geneontology/helpdesk#272]
**Please describe your question, idea, or concern.**
Latest GAF files does not have mandatory header mentioning the GAF version in the files. Is this a new modification? Could not find the update page regarding the same. thank you

**Comment by kltm** [comment]
@prasad-693 

Thank you for contacting the GO Helpdesk.

This was an issue that we discovered recently (https://github.com/geneontology/pipeline/issues/198) and now reflected in the release notes. Or next release (any day now) will have the fix in place.

**Comment by prasad-693** [comment]
@kltm Thank you for the details.
