### ISSUE TITLE
Different Results between May and August using PANTHER-GO-Slim BP (Bonferroni correction)

### ISSUE THREAD

**Issue by MBugger** [geneontology/helpdesk#274]
## Describe the issue/bug
Analysis of the same gene list in May 2020 vs August 2020 gave completely different results.
Bonferroni count in May was "1", while now it is "1711".
## Expected behavior
Explanation how this number can change so dramatically in this time. Was there an update? 

## To Reproduce

Please include any information you can about: what, where, when, and why. Please include any URLs involved in the issue.

## Screenshots
![image](https://user-images.githubusercontent.com/70595847/91882384-2e4eab80-ec83-11ea-9cf0-22886a4a79f9.png)

## Additional context

Add any other context about the issue that you feel may be important. E.g. browser version, time of day.

**Comment by mugitty** [comment]
There was an issue with Bonferroni correction that was resolved in 7/28/2020.  The software version # was updated:
![image](https://user-images.githubusercontent.com/6527204/91886581-6253ad80-ec3e-11ea-8697-ff2c4fab2527.png)
