### ISSUE TITLE
Screenshot of Gene Ontology from Bioportal

### ISSUE THREAD

**Issue by laiasubirats** [geneontology/helpdesk#276]
Dear Sir/Madam,

I am writing a chapter of a book called Gender Bias, Artificial Intelligence and Healthcare of the editorial Elsevier.

In our chapter, we are including a screenshot of the GeneOntology from Bioportal website. For this reason, we would like to ask you for permission to use this screenshot.

I am looking forward to hearing from you.

Yours faithfully,

L.

**Comment by suzialeksander** [comment]
Hi @laiasubirats, 

Please find our citation policy at http://geneontology.org/docs/go-citation-policy/.  It would seem a screenshot falls under CC by 4.0 (https://creativecommons.org/licenses/by/4.0/) and we ask it is properly attributed to GO- please mention the Ashburner and our 2019 paper if you publish before our 2020 NAR paper is published.  

It would be simplest if you used the Gene Ontology tool (AmiGO, eg http://amigo.geneontology.org/amigo/term/GO:0099606) to display GO information, but if you wish to use the BioPortal view you will need to contact them separately to confirm this use is acceptable.  

Best, Suzi

**Comment by laiasubirats** [comment]
Dear @suzialeksander,

Thank you. We will cite the two papers you mention as requested. We have contacted BioPortal separately to confirm this use is acceptable.

Best regards,

L.
