### ISSUE TITLE
API for GO analysis?

### ISSUE THREAD

**Issue by bsmith030465** [geneontology/helpdesk#277]
Hi,

How can I programmatically replicate the GO analysis? For example, currently I just c&p my genes into the text box (using defaults 'biological process' and 'Homo Sapiens') and click 'Launch'.

Is there an API thru' which I can do the same thing programmatically that will give me the same results?

thanks!!

**Comment by mugitty** [comment]
You can use PANTHER tools - Enrichment from http://pantherdb.org/services/tryItOut.jsp?url=%2Fservices%2Fapi%2Fpanther to access the service programmatically.

**Comment by bsmith030465** [comment]
Thanks for that! I am almost there! 

The query I execute is:

```
panther.url <- "http://pantherdb.org/services/oai/pantherdb/enrich/overrep"
pan.body <- list(geneInputList=tgenestr,organism="9606",annotDataSet="GO:0008150") #
myresult <- POST(url=panther.url, body = pan.body, verbose()) # the default
print(myresult)
```

However, I get an error:

```
Response [http://pantherdb.org/services/oai/pantherdb/enrich/overrep]
  Date: 2020-09-16 17:15
  Status: 200
  Content-Type: application/json;charset=UTF-8
  Size: 116 B
{"search": {
    "error": "Error annotation type data set not specified",
    "search_type": "overrepresentation"

```

How should I specify the annotDataSet in my query string?

many thanks!

**Comment by mugitty** [comment]
You can determine the list of annotation data sets from the following service:
http://pantherdb.org/services/oai/pantherdb/supportedannotdatasets

When invoked from the Geneontology website, the system uses biological process (GO:0008150) by default.  You are already specifying it in your code (...annotDataSet="GO:0008150"...(.  Ensure parameters are escaped

Something like the following should work:
http://pantherdb.org/services/oai/pantherdb/enrich/overrep?geneInputList=Q96PB1&organism=9606&annotDataSet=GO%3A0008150&enrichmentTestType=FISHER&correction=FDR
