### ISSUE TITLE
Replaced term among examples in "Relations in the Gene Ontology"

### ISSUE THREAD

**Issue by paolaroncaglia** [geneontology/helpdesk#278]
Hi,

Looking at http://geneontology.org/docs/ontology-relations/
The third example lists a term (anti-apoptosis) that was merged in 2012. Therefore its label is only available as a synonym, and its ID is now secondary. You may want to update (or replace) the example please?

Thanks,

Paola

**Comment by suzialeksander** [comment]
Good catch! I'll get to this, thanks for reporting!
