### ISSUE TITLE
How to make a list of mitochondrial genes and one of ribosomal genes?

### ISSUE THREAD

**Issue by Munfred** [geneontology/helpdesk#280]
Hello, I’m trying to compile two lists: one of C elegans mithochondrial genes, and one of ribosomal genes.

For ribosomal genes I know there are `rpl` and `rps` gene families for large and small subunits, and similarly for mitochondrial genes there are `mrpl` and `mrps` gene families, but there are many more.

How could I use GO to create these lists programmatically?

Thanks!

**Comment by suzialeksander** [comment]
Hi @Munfred, 

You might want to try using Amigo.  Here's a link to all worm entities under GO:0005840 ribosome: 
http://amigo.geneontology.org/amigo/search/bioentity?q=*:*&fq=regulates_closure:%22GO:0005840%22&fq=taxon_subset_closure_label:%22Caenorhabditis%20elegans%22&sfq=document_category:%22bioentity%22

If this isn't what you were looking for, we also have an API at http://api.geneontology.org, where you can get back to http://api.geneontology.org/api/bioentity/function/GO%3A0005840/genes.  If you'd like to get more info on the API, or ontobio for Python (https://github.com/biolink/ontobio), let me know.

**Comment by Munfred** [comment]
Thanks, that answers my questions!
