### ISSUE TITLE
Is there any annotation for chlorocebus sabaeus?

### ISSUE THREAD

**Issue by raquelfm1** [geneontology/helpdesk#281]

**Comment by suzialeksander** [comment]
Hi @raquelfm1, 

There are some GO annotations for _Chlorocebus sabaeus_, taxon:60711

You can find them at 

http://amigo.geneontology.org/amigo/search/annotation?q=*:*&fq=taxon_subset_closure_label:%22Chlorocebus%20sabaeus%22&sfq=document_category:%22annotation%22

Also check out QuickGO (https://www.ebi.ac.uk/QuickGO/annotations?geneProductType=protein&taxonId=60711&taxonUsage=descendants), and see our FAQ for why AmiGO and QuickGO have a different number of results: 
http://geneontology.org/docs/faq/#what-are-the-differences-between-the-data-available-in-amigo-and-those-on-quickgo 

AmiGO also has many more annotations (739) to _Chlorocebus aethiops_, with another handful for each of _C. pygerythrus_ and _C. tantalus_, if that will help in your work.
