### ISSUE TITLE
"No results associated with your search, please try again"

### ISSUE THREAD

**Issue by akaraw** [geneontology/helpdesk#283]
## Describe the issue/bug

Hi I am using panther for functional classification using a list produced by panther hmm scoring tool against version 15 panther db. I could get results for most of the outputs I uploaded to the panther but three of the outputs from the scoring tool did not work and I am keep getting the same error "No results associated with your search, please try again". I have uploaded one example output that produces this error message. Any help would be highly appreciated. 

[panther37.txt](https://github.com/geneontology/helpdesk/files/5486042/panther37.txt)

## Expected behavior

Expected beahviour is to have functional classification. 

## To Reproduce

http://pantherdb.org/
![Capture](https://user-images.githubusercontent.com/43054305/98080392-18e34100-1ec1-11eb-8cf7-967216341329.PNG)

**Comment by mugitty** [comment]
There is a problem with the input.
A single sequence cannot be mapped to multiple PANTHER HMM's

ENSACYP00000010407.1	PTHR11442:SF84	HEMOGLOBIN SUBUNIT EPSILON-Y2	1.5e-52	180.7	1-106
ENSACYP00000010407.1	PTHR11442:SF52	HEMOGLOBIN SUBUNIT GAMMA-1	1.5e-52	180.7	1-106

**Comment by akaraw** [comment]
Hi @mugitty 

Great! That worked. I will use one of these as input. Thank you very much!

Kind regards,
Anjana
