### ISSUE TITLE
qualifier order

### ISSUE THREAD

**Issue by murphyte** [geneontology/helpdesk#284]
We're getting gaf files from: http://current.geneontology.org/annotations
for example: goa_cow.gaf.gz

for the qualifiers, we're now seeing both:
NOT|colocalizes_with
colocalizes_with|NOT

Is the qualifier order supposed to be constrained, or does it not matter? The spec doesn't say (http://geneontology.org/docs/go-annotation-file-gaf-format-2.1/#qualifier-column-4), but I wanted to check in case having NOT first vs last is unexpected.

Thanks!
-Terence

**Comment by kltm** [comment]
Tagging @dougli1sqrd for confirmation.

I believe that answer is that in GAF 2.1, there is no enforced order for this; for GAF 2.2 (upcoming format switchover), the spec dictates that the "NOT" needs to come first.

**Comment by murphyte** [comment]
Thanks! I do see this in the updated spec:
https://github.com/geneontology/geneontology.github.io/blob/issue-go-annotation-2917-gaf-2_2-doc/_docs/go-annotation-file-gaf-format-22.md#qualifier-column-4

Is there a timeline for GAF2.2 becoming official, and the GOA files being updated to meet the new spec?

**Comment by kltm** [comment]
There should be an announcement in the next week or so that includes something close to the final timeline.

**Comment by murphyte** [comment]
ok, thanks. That takes care of this ticket as far as I'm concerned.
