### ISSUE TITLE
New taxon format causing our GAF readers to crash: Curie(namespace='NCBITaxon', identity='1280')

### ISSUE THREAD

**Issue by dvklopfenstein** [geneontology/helpdesk#287]
Hello,

Thank you for the great annotations. They are extremely helpful.

Our GPAD reader tests are **FAILing** due to a taxon in *goa_human.gpad*, downloaded just now from http://current.geneontology.org/annotations, having this format in 526 lines:

**Curie(namespace='NCBITaxon', identity='<some integer'>)**

rather than the format of either:

  * **taxon:9606**
  * **NCBITaxon:9606**

Should we support this new format, which will make reading GPAD files slower, or can the 526 GPAD file taxon lines be changed from:

  * **Curie(namespace='NCBITaxon', identity='<some integer'>)**

to:

  * **NCBITaxon:NNNN**

cc: @tanghaibao @judowill @dvklopfenstein

**Comment by suzialeksander** [comment]
Hi @dvklopfenstein, 

Thank you for reporting this.  According to the current GPAD file format (you can find this at http://geneontology.org/docs/gene-product-association-data-gpad-format/ ), we expect files to only have the taxon number without the other characters.  I will pass this info on to either resolve the issue upstream and/or add in a check for this column.

**Comment by suzialeksander** [comment]
@dougli1sqrd would this be a Rules issue 

or 

@kltm @pgaudet is this an issue from upstream files- although most of the lines are attributed to UniProt, ParkinsonsUK-UCL, BHF-UCL, CAFA, ARUK-UCL, & DIBU have the incorrect format in goa_human.gpad

**Comment by kltm** [comment]
Exploration for this issue is underway at https://github.com/biolink/ontobio/issues/489 .

**Comment by suzialeksander** [comment]
Great, thanks.  @dvklopfenstein, thank you again for reporting this and I apologise that it was buried before we could address the issue.  If you find any other issues in the future, please feel free to report them in this repo.  I am closing this ticket to avoid duplicating /biolink/ontobio#489 - if you would follow the ontobio ticket, it sounds like they are working on a fix.
