### ISSUE TITLE
GO accession number clustering

### ISSUE THREAD

**Issue by kavithamallayaa** [geneontology/helpdesk#289]
Hi,

I have list of GO accession IDs ( GO:xxxxxxx ) associated with the gene list in a dataset.

I would like to group these GO_ids based on their ontology. How to get the GO_ids associated with different biological process.

regards
Kavitha

**Comment by suzialeksander** [comment]
Hi @kavithamallayaa, 

Thank you for contacting our Helpdesk.  You should be able to find the answer at http://geneontology.org/docs/faq/#how-do-i-get-the-term-names-for-my-list-of-go-ids

If you need any assistance with YeastMine (yes, the steps described will work with any/all organisms not just yeast) or further help, please let me know.

**Comment by kavithamallayaa** [comment]
Hi Suzialeksander,

I am interested in the gene ontology hierarchy for Chlamydomonas
reinhardtii and the GO accession id associated with each level. GO slim
terms for Chlamydomonas will also help.

I think YeastMine has not included Chlamydomonas.

with regards
Kavitha

**Comment by suzialeksander** [comment]
Hi @kavithamallayaa , 

Sorry, I misunderstood what you needed.  I thought you needed your GO IDs translated to GO terms.  

There is a generic GO Slim, as well as a plant-specific slim.  You can find both of these at http://geneontology.org/docs/download-ontology/#download-go-subsets.

The generic slim is preloaded and is one of several slims available in the Term Mapper tool: https://go.princeton.edu/cgi-bin/GOTermMapper.  I suspect the "TAIR" option is the same as the Plant Slim, but you can also use the Advanced options at the bottom of the tool.

If neither slim quite meets your needs for Chlamydomonas, let me know and I can provide guidance for you to try and make your own slim, but it does require some manual steps so hopefully one of the available slims will work for you.
