### ISSUE TITLE
saccharomyces GAF file has 16 fields instead of expected 17

### ISSUE THREAD

**Issue by dvklopfenstein** [geneontology/helpdesk#292]
## Describe the issue/bug

The GAF file downloaded from yeastgenome.org has 16 fields, (missing the  field: *Gene Product Form ID*) instead of the 17 fields defined in the [GAF 2.0 ](http://geneontology.org/docs/go-annotation-file-gaf-format-2.0/) file format guide.

## Expected behavior

GAF files that are version 2.0 (deprecated) or 2.1 are expected to have 17 fields.

## To Reproduce

Please include any information you can about: what, where, when, and why. Please include any URLs involved in the issue.

* Download the GAF file from: http://downloads.yeastgenome.org/curation/literature/gene_association.sgd.gaf.gz
*  Run test:
https://github.com/tanghaibao/goatools/blob/main/tests/test_i195_sgd_gaf.py

## Additional context

See this GOATOOLS open issue:  https://github.com/tanghaibao/goatools/issues/195

**Comment by suzialeksander** [comment]
Hi @dvklopfenstein 

Thank you for reporting this issue.  As SGD does not use the optional Gene Product Form ID field, this field is not included in the version produced by SGD.  We thank you for pointing this out and will bring this up with the SGD team, who will likely address the issue while converting to the new GAF version (https://github.com/geneontology/go-announcements/issues/182).  

We would like to direct you to the official GO product at http://current.geneontology.org/annotations/sgd.gaf.gz, which has been processed by GO and not only has the expected number of fields, but also has additional yeast annotations including those from the PAINT pipeline. 

For best results, please use the files found at http://current.geneontology.org.

**Comment by suzialeksander** [comment]
SGD has made a code release with a fix, the next GAF produced will be the Feb 1 GAF but it seems it's a code issue rather than an intentional omission.  Again however, http://current.geneontology.org is the preferred source for a complete GAF.  Closing as this is an issue at the source, not through GO- but thank you for reporting the issue so we could inform SGD.
