### ISSUE TITLE
Reasoning rules for relations in GO

### ISSUE THREAD

**Issue by rashmie** [geneontology/helpdesk#293]
**Please describe your question, idea, or concern.**
Hello,

The following link describes the reasoning rules for some of the relationships used in GO. 

http://geneontology.org/docs/ontology-relations/

Just wondering what the rules are for the rest of the relationships.

**Comment by kltm** [comment]
@balhoff Would you have a good resource for these?

**Comment by balhoff** [comment]
@rashmie the reasoning rules for the relationships are defined by the Relation Ontology (RO): http://obofoundry.org/ontology/ro.html

and also by the OWL language itself. GO imports relation axioms from RO.

For example, you can see for 'part of' that it's marked as a Transitive Property: http://www.ontobee.org/ontology/RO?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FBFO_0000050

this gives the rule shown on the GO webpage:

`'part of' o 'part of' -> 'part of'`

This is a nice introduction to OWL: https://www.w3.org/TR/owl2-primer/

The book 'Introduction to Bio-Ontologies' by Robinson and Bauer has some good background as well.

**Comment by rashmie** [comment]
@balhoff Thanks so much for the suggested sources. They are very helpful.

However, I noticed that some of the reasoning rules mentioned in the GO webpage is different than the source you suggested.

For example, for the 'regulates' relation, Go webpage mentions,

'regulates' o 'part_of' -> 'regulates'

But this is not there in the following source (I checked under property chains): 
http://www.ontobee.org/ontology/RO?iri=http://purl.obolibrary.org/obo/RO_0002211

Also, the above link mentions that the 'regulates' relation is transitive. However, GO webpage reasoning rules for the 'regulates' relation does not state this.

Just wondering whether I am missing something here.

**Comment by balhoff** [comment]
Hi @rashmie good catch, the `'regulates' o 'part_of' -> 'regulates'` rule you noticed has been removed from the ontology. This (and similar for positively/negatively) were asserted in GO, but never added to RO. Later it was decided it wasn't valid: https://github.com/geneontology/go-ontology/issues/12344

So we need to update that documentation, thanks! I don't think that page is meant to be exhaustive (the ontology itself is authoritative) but I agree we ought to add 'regulates' transitivity to the graphic.

**Comment by rashmie** [comment]
Hi @balhoff! Thank you so much for the clarification. That helps a great deal. 

Something I noted is,
1. 'is_a' o <any_object_property> -> <any_object_property>
2. <any_object_property> o 'is_a' -> <any_object_property>

Also, other such rules with 'is_a', and rules indicating transitiveness of some object properties, the following seems to be the only rules that hold in GO.
1. 'occurs_in' o 'part_of' -> 'occurs_in'
2. 'part_of' o 'occurs_in' -> 'occurs_in'
3. 'negatively_regulates' o 'negatively_regulates' -> 'positively_regulates'

Kindly let me know whether my understanding is correct. Out of these,  'part_of' o 'occurs_in' -> 'occurs_in' does not appear in the OWL file when I checked it with protege.

**Comment by balhoff** [comment]
@rashmie sorry for the slow reply. If you are interested in detailed OWL reasoning going on in GO, it helps to know that the main release file (at `http://purl.obolibrary.org/obo/go.owl` is simplified compared to the editors version. The release file most closely corresponding to the editors source is available at `http://purl.obolibrary.org/obo/go/extensions/go-plus.owl`, and you will see the relation chain there. You can also see that relation chain if you look directly in the Relation Ontology.

**Comment by rashmie** [comment]
@balhoff Thank you very much for pointing this out. Really appreciate this. I will use go-plus.owl for my work then.
