### ISSUE TITLE
Links to QC page in FAQ broken

### ISSUE THREAD

**Issue by jrr-cpt** [geneontology/helpdesk#295]
I am looking for the QC standards on IEA annotations. In the GO site [FAQ](http://geneontology.org/docs/faq/), there is a link to a [QC page](http://geneontology.org/page/annotation-quality-control), which is broken.

**Comment by jrr-cpt** [comment]
The [wiki on IEA](http://wiki.geneontology.org/index.php/Inferred_from_Electronic_Annotation_(IEA)) has an external link that says it will says IEAs older than one year will be deleted. But the linked page does not mention IEAs, nor quality controls performed.

**Comment by suzialeksander** [comment]
Thanks for reporting that!  The old IEAs are addressed by GORULE:0000029, which you can find at  https://github.com/geneontology/go-site/blob/master/metadata/rules/gorule-0000029.md
