### ISSUE TITLE
broken link to sparql endpoint documentation

### ISSUE THREAD

**Issue by odameron** [geneontology/helpdesk#296]
Hello,
   The page http://geneontology.org/sparql.html has a broken link to the "GO SPARQL documentation" at http://geneontology.org/docs/sparql/.

thank you

**Comment by suzialeksander** [comment]
Thank you @odameron for reporting this.  @lpalbou where was this link supposed to go?

**Comment by lpalbou** [comment]
Hi @odameron , thanks for reporting this, it was a simple typo in the URL (no / at the end) and this is now fixed. Let us know if you any other question or comment.

**Comment by suzialeksander** [comment]
Great, thanks @lpalbou.
