### ISSUE TITLE
Looking for goa_unprot_all.gaf.gz

### ISSUE THREAD

**Issue by kltm** [geneontology/helpdesk#297]
Hi @kltm,
I am looking for the latest version of http://current.geneontology.org/annotations/goa_uniprot_all.gaf.gz
It looks like the specific organism GAFs were already updated to the latest 2021 build, but the UniProt link still returns the version from 2020.
Can you help with this?

_Originally posted by @davidbio in https://github.com/geneontology/helpdesk/issues/282#issuecomment-779799804_

**Comment by kltm** [comment]
@davidbio

As we transition away from the consumption of goa_uniprot_all.gaf ourselves (https://github.com/geneontology/pipeline/issues/207), we stopped (what was basically) mirroring them a few months ago. 
The best place to get this file would be at the origin at: ftp://ftp.ebi.ac.uk/pub/databases/GO/goa/UNIPROT/goa_uniprot_all.gaf.gz

**Comment by davidbio** [comment]
Thanks a lot!
