### ISSUE TITLE
What is the syntax of Annotation Extension (column 16 of GAF 2.1 format)?

### ISSUE THREAD

**Issue by azat-badretdin** [geneontology/helpdesk#299]
What is the syntax of Annotation Extension (column 16 of GAF format)?

http://geneontology.org/docs/go-annotation-file-gaf-format-2.1/

says: `This field is optional, cardinality 0 or greater.` while similar fields (with one-to-many attributes) have also a specifier for item separation: example: `for cardinality 2 use a pipe to separate entries (e.g. taxon:1|taxon:1000).`

I stumbled upon a situation where both commas and pipes are used, apparently, as separators.

Is this a reflection of a different logic between these items? 

Example: 

```

dictyBase       DDB_G0270218    glkA            GO:0010629      PMID:31581556   HDA             P       Probable serine/threonine-protein kinase glkA   glkA|DDB_G0270218       protein taxon:44689     20191021        dictyBase       has_input(DDB:DDB_G0288591),has_input(DDB:DDB_G0275673),has_input(DDB:DDB_G0269418),has_input(DDB:DDB_G0292574),has_input(DDB:DDB_G0268102),has_input(DDB:DDB_G0280051),has_input(DDB:DDB_G0288757),has_input(DDB:DDB_G0281171),has_input(DDB:DDB_G0276109),has_input(DDB:DDB_G0274203),has_input(DDB:DDB_G0282433),has_input(DDB:DDB_G0273861),has_input(DDB:DDB_G0280997),has_input(DDB:DDB_G0291336),has_input(DDB:DDB_G0271886),has_input(DDB:DDB_G0348183),has_input(DDB:DDB_G0290503),has_input(DDB:DDB_G0269628),has_input(DDB:DDB_G0273433),has_input(DDB:DDB_G0286009),has_input(DDB:DDB_G0273073),has_input(DDB:DDB_G0286535),has_input(DDB:DDB_G0274799),has_input(DDB:DDB_G0285295)|part_of(GO:0071320)     

```

**Comment by suzialeksander** [comment]
Hi @azat-badretdin, 

Thank you for contacting the GO Helpdesk.  The usage for commas and pipes is the same for column 16 as it is defined for column 8 (http://geneontology.org/docs/go-annotation-file-gaf-format-2.2/#with-or-from-column-8): 
>The pipe (|) specifies an independent statement (OR) and is equivalent to making separate annotations, i.e. not all conditions are required to infer the annotated GO term. The comma (,) specifies a connected statement (AND) and indicates that all conditions are required to infer the annotated GO term. In this case, ‘OR’ is a weaker statement than ‘AND’, therefore will be correct in all cases. Pipe and comma separators may be used together 


We have defined this usage for column 16, but it is a little hidden at
http://wiki.geneontology.org/index.php/Annotation_Extension#Format_for_referencing_multiple_relationship.28identifier.29_pairs.  I will make a note to improve our description of the Annotation Extension column on http://geneontology.org/docs/go-annotation-file-gaf-format-2.1/ , thank you for alerting us of an area where our documentation is not clear. 

Please also be aware that future releases, including the next release in March, will be in GAF 2.2 not GAF 2.1 format.  If you are looking at the GAF format right now it will be best to work from the 2.2 document (where I will also update the description  for Column 16).

**Comment by azat-badretdin** [comment]
Thanks, Suzi!

**Comment by suzialeksander** [comment]
I've updated the docs for both 2.1 and for GAF 2.2 formats.  Thanks again for letting us know about this.

**Comment by azat-badretdin** [comment]
You are welcome! I would like to use this opportunity to invite you to have a look at our relatively recent new product: PGAPx hosted at github as well. This product will be using Gene Ontology links in the future (that's what I am doing now). https://github.com/ncbi/pgap
