### ISSUE TITLE
Size of go_monthly-assocdb-data.gz     

### ISSUE THREAD

**Issue by tamiyajima** [geneontology/helpdesk#3]
Hi,
The size of go_monthly-assocdb-data.gz dated 07-Mar-2017 is 228M, whereas that of the same file dated 07-Jan-2017 is 6.2G.
Is this file correct?

Thanks.

**Comment by kltm** [comment]
@tamiyajima,

Thank you for contacting the GO Helpdesk.

Our apologies for the trouble. There were apparently some issues with the final build for the GO full database. @stuartmiyasato may have some more information there. I would suggest using the 2017-01-01 build instead.

It may be good to note that we will soon be switching over to a graph store and that the mysql dumps may not be produced in the future.

Best wishes, kltm
