### ISSUE TITLE
Can I perform term enrichment analysis for a species not listed in the enrichment tool?

### ISSUE THREAD

**Issue by jeniferfrancis** [geneontology/helpdesk#30]
Hi
I am working on Streptococcus agalactiae and streptococcus equi, is there any chance for me to perform Enrichment analysis because I couldn't find the organisms in the list.
thanks

**Comment by monicacecilia** [comment]
Hi @jeniferfrancis,

The Term Enrichment tool on the GO and AmiGO websites __centers only__ on data from the genomes available on the [PANTHER Classification System Database](http://go.pantherdb.org); that is, if the species is not listed there, then data from that species is not available for enrichment analysis using our Enrichment tool. 

A few alternatives for organisms not included in the data available from the PANTHER and more information on this subject are available on the [Gene Ontology Website, in our FAQ page](http://geneontology.org/faq/how-can-i-do-term-enrichment-analysis-species-not-present-list-amigo). 

We hope this information is helpful. Please let us know if you have any additional questions about the resources of the Gene Ontology Consortium via the [Help Desk](http://help.geneontology.org/).
