### ISSUE TITLE
Import of GO-CAMS to neo4j

### ISSUE THREAD

**Issue by kltm** [geneontology/helpdesk#305]
We had a question come in on the Helpdesk:

```
I wonder if you have a way to import the GO ontology and GO-CAMs to neo4j. I would like to connect this to a gene set.
```
 
While this is not directly supported as part of our data products, I'm pretty sure that we have affiliated groups loading to Neo4J in various ways. What would be the best way to connect this user to that kind of information?

**Comment by kltm** [comment]
Tagging @cmungall @balhoff

**Comment by cmungall** [comment]
While it should be possible to use the existing generic neo4j rdf loaders it's not clear this will give an optimal graph-oriented representation. For example you will end up with nodes for axioms.

I think formally we say that this is unsupported but if the questioner is interested in this as a research topic they should feel free to reach out for me. There are a number of approaches to mapping OWL to Property Graphs, and we are also exploring GO-CAM specific mappings
