### ISSUE TITLE
 How to determine release date programmatically

### ISSUE THREAD

**Issue by jmcherry** [geneontology/helpdesk#307]
For some time I have used a script to download the releases. A few months back the release.geneontology.org webpage changed to use a js script access to S3. The result is that the full URL for a release is not in the HTML, rather created via client side via js. My script used Python and the requests modules to parse the HTML. 

Can you suggest a method that I can programmatically check for releases and download them when available.

-Mike

**Comment by lpalbou** [comment]
Hi Mike,

For my secondary pipeline I check every 6h for a change in http://current.geneontology.org/metadata/release-date.json . It has worked flawlessly for me since 2018.

ThIs file is updated only when there is a new release and all release files are updated at the same time on current.geneontology.org .

Thanks

**Comment by lpalbou** [comment]
As an additional note, a secondary file is generated at every release and is the one used to show the release date and stats on the top right of the go website:

http://current.geneontology.org/release_stats/go-stats-summary.json

**Comment by jmcherry** [comment]
Thanks. I have a need to know the previous releases not just the current release. Thats why I used released.geneontology.org. However, maybe there is a json file that has the release dates, then I can download previous versions. I agree that I can use current.geneontology.org for the current version of the released files.

**Comment by lpalbou** [comment]
I had thought of that and I think the GO API should have a simple route to list all the releases. Had that on my experimental API but it’s not in production. Definitely something that can be added.

If you need the previous releases and are only interested in the DOI releases since 2018, that file might do the trick for you:
http://current.geneontology.org/release_stats/aggregated-go-stats-summaries.json

Contains all the go-stats-summary ever computed with the release dates.

If you want all the releases ever published by GO, then either parse the html of http://release.geneontology.org/

or look at the JS code to list the “folders” / releases of the S3 bucket behind that website: https://github.com/lpalbou/aws-js-s3-explorer/blob/4c248661dff339deb574fa42bc7e78a2faa89090/index.html#L283

**Comment by suzialeksander** [comment]
@pascale it sounds like this needs discussion still, can we add it to Manager's call this week?

**Comment by pgaudet** [comment]
Mike needs all the files from the command line.

**Comment by pgaudet** [comment]
@cmungall can you make clear specs and assign someone?

**Comment by cmungall** [comment]
@kltm specced this out here https://github.com/geneontology/pipeline/issues/231, I approve the spec

@jmcherry - as an interim measure you can do this:

```
s3cmd ls --recursive s3://go-data-product-release
```

I am attaching the results here

[go-data-product-release.txt](https://github.com/geneontology/helpdesk/files/6353137/go-data-product-release.txt)

an exert:

```
2021-02-03 19:09      3340524  s3://go-data-product-release/2021-02-01/annotations/sgd.gaf.gz
2021-02-03 19:09      1559996  s3://go-data-product-release/2021-02-01/annotations/sgd.gpad.gz
2021-02-03 19:11       190456  s3://go-data-product-release/2021-02-01/annotations/sgd.gpi.gz
```

You can use this to access the s3 bucket objects directly, or you can construct URLs from these by replacing `s3://go-data-product-release/` with `http://release.geneontology.org`

E.g.

http://release.geneontology.org/2021-02-01/annotations/sgd.gaf.gz

**Comment by lpalbou** [comment]
Depending of the AWS CLI that you installed, the command line can also be:

```
aws s3 ls --recursive s3://go-data-product-release
```

but indeed this would list all the files. since the question is more about the releases, we don't need the --recursive:

```
aws s3 ls s3://go-data-product-release
```

**Comment by jmcherry** [comment]
Perfect. Thats just what I needed. I’ll first do:

aws s3 ls s3://go-data-product-release

Then if I have not already downloaded the release I’ll get the files with something like this:

aws s3 cp s3://go-data-product-release/2021-02-01/annotations/ .

Thanks,
Mike





On Apr 26, 2021, at 12:29 PM, lpalbou ***@***.******@***.***>> wrote:



Depending of the AWS CLI that you installed, the command line can also be:

aws s3 ls --recursive s3://go-data-product-release


but indeed this would list all the files. since the question is more about the releases, we don't need the --recursive:

aws s3 ls s3://go-data-product-release

**Comment by lpalbou** [comment]
Glad this helps.

Note that to copy multiple files, you will need either to use --recursive:
```
aws s3 cp s3://go-data-product-release/2021-02-01/annotations/ . --recursive
```

Or to use the sync command:
```
aws s3 sync s3://go-data-product-release/2021-02-01/annotations/ .
```

**Comment by jmcherry** [comment]
Thanks. I’ve written a new script and now have all the files I want. I want all gaf and gpad files from all releases. I have a copy of all these files going back to the time GOC used CVS to manage their distribution. Nice to be able to easiest update these files.

-Mike


On Apr 26, 2021, at 6:33 PM, lpalbou ***@***.******@***.***>> wrote:



Glad this helps.

Note that to copy multiple files, you will need either to use --recursive:

aws s3 cp s3://go-data-product-release/2021-02-01/annotations/ . --recursive


Or to use the sync command:

aws s3 sync s3://go-data-product-release/2021-02-01/annotations/ .

**Comment by jmcherry** [comment]
One question on the AWS S3. There is a “directory” 2021-02-03 but it is empty. Maybe that should be deleted?

On Apr 28, 2021, at 9:19 AM, J. Michael Cherry PhD ***@***.******@***.***>> wrote:

Thanks. I’ve written a new script and now have all the files I want. I want all gaf and gpad files from all releases. I have a copy of all these files going back to the time GOC used CVS to manage their distribution. Nice to be able to easiest update these files.

-Mike


On Apr 26, 2021, at 6:33 PM, lpalbou ***@***.******@***.***>> wrote:



Glad this helps.

Note that to copy multiple files, you will need either to use --recursive:

aws s3 cp s3://go-data-product-release/2021-02-01/annotations/ . --recursive


Or to use the sync command:

aws s3 sync s3://go-data-product-release/2021-02-01/annotations/ .

**Comment by kltm** [comment]
@jmcherry Hm, looking on the console, there is only `2021-02-01` at the top level--there is nothing after it and no `2021-02-03`. I'll poke around a little and see if I can figure that out.

**Comment by lpalbou** [comment]
![Screen Shot 2021-04-28 at 10 50 24 AM](https://user-images.githubusercontent.com/24249870/116449910-8ab49b80-a80f-11eb-97ad-a544afafc5ea.png)

Yep, I don't see any 2021-02-03 either except for the index.html (each "folder" has that file for web browsing). You may want to filter the list obtained with ```aws s3 ls s3://go-data-product-release``` by removing the lines not ending by /.

**Comment by jmcherry** [comment]
I see its an error in my script. I must be grabbing that last date as a directory.  Thanks

On Apr 28, 2021, at 10:52 AM, lpalbou ***@***.******@***.***>> wrote:



[Screen Shot 2021-04-28 at 10 50 24 AM]<https://user-images.githubusercontent.com/24249870/116449910-8ab49b80-a80f-11eb-97ad-a544afafc5ea.png>

Yep, I don't see any 2021-02-03 either except for the index.html (each "folder" has that file for web browsing). You may want to filter the list obtained with aws s3 ls s3://go-data-product-release by removing the lines not ending by /.

**Comment by suzialeksander** [comment]
I think this is resolved, since it picked up the May release.  Let us know if anything changes.
