### ISSUE TITLE
GO Enrichment analysis: incomplete mapping of UniProt IDs

### ISSUE THREAD

**Issue by PSekula-FR** [geneontology/helpdesk#308]
Dear all,

when uploading a list of UniProt-IDs one could not be mapped and thus was discarded from analysis.
However, this specific ID (P60568) is not a recent addition (https://www.uniprot.org/uniprot/P60568, last modified April 2018) and can essentially be found on http://geneontology.org/ (http://amigo.geneontology.org/amigo/gene_product/UniProtKB:P60568).

So why could it not be mapped?

Thanks for your help in advance.

Best regards,
Peggy

**Comment by suzialeksander** [comment]
@mugitty, it looks like PANTHER does not think P60568 is a uniquely mapped ID. http://pantherdb.org/genes/geneList.do?searchType=basic&fieldName=all&listType=1&fieldValue=P60568&organism=all 

Do you know what's happening? also tagging @huaiyumi

**Comment by mugitty** [comment]
@suzialeksander, we are already looking into it. I will let you know when we have something to report.

**Comment by suzialeksander** [comment]
Fixed! thanks all.
