### ISSUE TITLE
owl and obo purls resolve to an older release?

### ISSUE THREAD

**Issue by janelomax** [geneontology/helpdesk#309]
Hi GO!

## Describe the issue/bug

[http://purl.obolibrary.org/obo/go.obo](http://purl.obolibrary.org/obo/go.obo) and [http://purl.obolibrary.org/obo/go.owl](http://purl.obolibrary.org/obo/go.owl) are on version 2021-02-01 but looks like the latest release should be 2021-04-02?

thanks 

Jane

**Comment by cmungall** [comment]
Hi @janelomax! 2021-02-01 is in fact the latest, there were some delays with the new GO release (new version of GAF!)

Hope things are well at scibite, I enjoyed James' ISB panel contributions today!

**Comment by janelomax** [comment]
Thanks Chris! Yes was a great session - can't wait until we can all get together again in RL though!
