### ISSUE TITLE
GO's fully update 

### ISSUE THREAD

**Issue by cheanney** [geneontology/helpdesk#31]
Hi,

I noticed http://archive.geneontology.org/latest-full/go_monthly-assocdb-tables.tar.gz is not been updated for several months now (the last update was in JAN). I am wondering if there will be updates soon.

Thanks,

Anney

**Comment by kltm** [comment]
@cheanney 

We are in a bit of a transition period right now, but there will be no further builds of the full database. For more details, please see the discussion on this issue: https://github.com/geneontology/helpdesk/issues/4
