### ISSUE TITLE
About the number of GO terms 

### ISSUE THREAD

**Issue by chestnzu1** [geneontology/helpdesk#311]
**Please describe your question, idea, or concern.**
Hello:
            Recently I am working with GO and I found the total number of BP terms is different from the number shows in GO statistics. On this page(http://geneontology.org/stats.html), it says in May 2021, there are 28642 BP terms. But when I use QUICKGO API to retrieve descendants of GO:0008150(GO version 2021-05-02), it has 31527 descendants which is around 3000 more than the number on the aforementioned webpage.  Can anyone explain what causes the discrepancy? Thanks in advance.

**Comment by suzialeksander** [comment]
Hello @chestnzu1 

Although the QuickGO API is not a Gene Ontology resource (it's run by EMBL-EBI) and I am not entirely familiar with their API, could it be you were using https://www.ebi.ac.uk/QuickGO/api/index.html#!/gene_ontology/findDescendantsUsingGET_1 ?
There is an option where you can specify relations, and the default is `is_a,part_of,occurs_in,regulates`; including more than `is_a` will change the results.  

I just tried 

`curl -X GET --header 'Accept:application/json' 'https://www.ebi.ac.uk/QuickGO/services/ontology/go/terms/GO%3A0008150/descendants?relations=is_a'`

Request URL

https://www.ebi.ac.uk/QuickGO/services/ontology/go/terms/GO%3A0008150/descendants?relations=is_a

and had 28642 results, consistent with our stats page at http://geneontology.org/stats.html.  You can also see on our stats page, in the "Number of GO terms by aspect" table, that we have not had more than 29700 BP terms in the recent past, so I do not suspect this is a version issue. 

You might want to contact QuickGO (https://www.ebi.ac.uk/QuickGO/api/contact.html) if you continue to have discrepancies.

**Comment by chestnzu1** [comment]
> Hello @chestnzu1
> 
> Although the QuickGO API is not a Gene Ontology resource (it's run by EMBL-EBI) and I am not entirely familiar with their API, could it be you were using https://www.ebi.ac.uk/QuickGO/api/index.html#!/gene_ontology/findDescendantsUsingGET_1 ?
> There is an option where you can specify relations, and the default is `is_a,part_of,occurs_in,regulates`; including more than `is_a` will change the results.
> 
> I just tried
> 
> `curl -X GET --header 'Accept:application/json' 'https://www.ebi.ac.uk/QuickGO/services/ontology/go/terms/GO%3A0008150/descendants?relations=is_a'`
> 
> Request URL
> 
> https://www.ebi.ac.uk/QuickGO/services/ontology/go/terms/GO%3A0008150/descendants?relations=is_a
> 
> and had 28642 results, consistent with our stats page at http://geneontology.org/stats.html. You can also see on our stats page, in the "Number of GO terms by aspect" table, that we have not had more than 29700 BP terms in the recent past, so I do not suspect this is a version issue.
> 
> You might want to contact QuickGO (https://www.ebi.ac.uk/QuickGO/api/contact.html) if you continue to have discrepancies.

Hello Suzialeksander:
              Thank you for your reply.
