### ISSUE TITLE
What is the state of LEGO ?

### ISSUE THREAD

**Issue by bioinfornatics** [geneontology/helpdesk#312]
Dear

Currently, I try to perform links between process and molecular function, but those «links» terms are missing in GO (I think). For instance, it is difficult to retrieve the different sets of enzymatic activities that compose a metabolic pathway.
I though that was the goal of [LEGO](http://wiki.geneontology.org/index.php/Category:LEGO). So what is the status of this project?

Thanks

Best regards

**Comment by suzialeksander** [comment]
Hi @bioinfornatics, 

Thank you for contacting our Helpdesk.  I think you're referring to our GO-CAMs (Gene Ontology Causal Activity Modeling), which used to be referred to as LEGO.  You can find the overview at http://geneontology.org/docs/gocam-overview/, including a link to our paper (https://rdcu.be/bRIgY).  

We are also actively working on displaying both YeastPathways (https://pathway.yeastgenome.org/) and Reactome (https://reactome.org/) as GO-CAMs, and hope to make these available to the public in the future.

Please let me know if you were looking for something specific.

**Comment by bioinfornatics** [comment]
Hi, thanks @suzialeksander 
Indeed, I did not see that the LEGO project now is named GO-CAMs. Thanks a lot

Best regards @suzialeksander
