### ISSUE TITLE
Chlorocebus sabaeus gene annotation file

### ISSUE THREAD

**Issue by dayena123** [geneontology/helpdesk#319]
Hello, 

I would like to download the gene annotation file for Chlorocebus sabaeus (Vervet - green monkey) in a .gaf (gzip) format, please. Could you help me do that, please?

Best wishes, 

Diana

**Comment by suzialeksander** [comment]
Hi @dayena123, 

Thank you for contacting us about Chlorocebus sabaeus (Taxonomy ID: 60711).  There are very few manual annotations, which you can grab from http://amigo.geneontology.org/amigo/search/annotation?q=*:*&fq=taxon_subset_closure_label:%22Chlorocebus%20sabaeus%22&sfq=document_category:%22annotation%22 (note this bookmark may expire in a week or so).  There's a `Custom DL` button at the top of the results that you can use to get a GAF (or any format). 

Furthermore, there are actually about 251k more annotations with the evidence code IEA (https://geneontology.github.io/docs/guide-go-evidence-codes/#electronic-annotation-evidence).  You can obtain the full set of IEA + manual annotations from QuickGO at https://www.ebi.ac.uk/QuickGO/annotations?taxonId=60711 (also see http://geneontology.org/docs/faq/#what-are-the-differences-between-the-data-available-in-amigo-and-those-on-quickgo).  Like AmiGO, you can use the blue buttons directly above the results to either `Customise` the results, or even better use the `Export` button and select "GAF" in the Format dropdown.  Make sure you set the limit to larger than 251,154.  EBI also has an API, https://www.ebi.ac.uk/QuickGO/api/index.html#/annotations.   If you need assistance with EBI/QuickGO tools, you can contact them at https://www.ebi.ac.uk/QuickGO/feedback.

**Comment by dayena123** [comment]
Hi @suzialeksander 

Thank you so much, I followed your suggestion and it worked well! :)

Best wishes, 

Diana
