### ISSUE TITLE
GO_cellular component

### ISSUE THREAD

**Issue by EvlampiaPar** [geneontology/helpdesk#322]
Hello! I recently did a GO analysis and I have a question regarding the "cellular component" output (please see the attached figure below). My question is: Which is the differenece between the extracellular region and cell wall in plants? Since the cell wall is the extracellular region (the space external to the outermost structure of a cell) in plants why these two terms are presenting differently? Happy to hear your feedback!

![cellular component_upregulated genes](https://user-images.githubusercontent.com/86246045/122782158-c704f500-d2b0-11eb-8d5b-6003dd167947.png)

**Comment by lpalbou** [comment]
My understanding is that Cell Wall is still a part of the Cell Periphery (http://amigo.geneontology.org/amigo/term/GO:0071944#display-lineage-tab), an encapsulating structure of the cell, whereas the extracellular region is truly outside of the cell and its encapsulating structures (http://amigo.geneontology.org/amigo/term/GO:0005576). 

The [cellular anatomical entity](http://amigo.geneontology.org/amigo/term/GO:0110165#display-lineage-tab) term has the two separate branches / child terms: 
* [cell periphery](http://amigo.geneontology.org/amigo/term/GO:0071944#display-lineage-tab), a parent of [cell wall](http://amigo.geneontology.org/amigo/term/GO:0005618)
* [extracellular region](http://amigo.geneontology.org/amigo/term/GO:0005576#display-lineage-tab)

**Comment by EvlampiaPar** [comment]
@lpalbou and @cmungall thank you very much for your input! It s very helpful! I appreciate it!
