### ISSUE TITLE
http://geneontology.org/ - website down?

### ISSUE THREAD

**Issue by callahantiff** [geneontology/helpdesk#324]
## Describe the issue/bug

When trying to programmatically access http://geneontology.org/gene-associations/goa_human.gaf.gz a ```ConnectionRefusedError:``` error was triggered. After further exploration, it appears that http://geneontology.org/ is unreachable and that the site may be down.

## Expected behavior

Expected to be reach website, but was unable to

## To Reproduce

Unable to reach http://geneontology.org/ from landing page or any other pages

## Screenshots

Browser returned when trying to access http://geneontology.org/

<img width="1487" alt="Screen Shot 2021-07-04 at 12 19 34" src="https://user-images.githubusercontent.com/8030363/124395578-1b9d6c80-dcc2-11eb-80cf-86041ba2ca2f.png">

<br>

## Additional context

Tested on Chrome `Version 91.0.4472.114 (Official Build) (x86_64)` and Firefox `88.0.1`

**Comment by kltm** [comment]
@callahantiff 

Apologies for the trouble. The server in charge of the proxying and redirecting for the root domain had some issues that have now been cleared. Things should now be working again. 

As a note, while your links are still good from porting over from our legacy system, it might be good to update to the newer versions, which are less likely to experience outages (as they do not need to transit the redirect):

http://current.geneontology.org/annotations/

**Comment by callahantiff** [comment]
Hi @kltm!

Thanks so much for the update and for the pointer to the new system. Will be updating my system this morning. As always, you guys are awesome and I'm incredibly grateful for all of your hard work in maintaining this resource!

Hope you have a great day! 😄
