### ISSUE TITLE
relations betwee gene products and entities

### ISSUE THREAD

**Issue by ValWood** [geneontology/helpdesk#325]
**Please describe your question, idea, or concern.**

Hi,

Where can I find the list of available relations between each entity?
Thanks,

Val

**Comment by balhoff** [comment]
@ValWood is this what you're looking for? https://github.com/geneontology/go-annotation/blob/master/specs/gpad-gpi-2-0.md#allowed-gene-product-to-go-term-relations

**Comment by ValWood** [comment]
Yes, thanks Jim!
