### ISSUE TITLE
How to reproduce gene ontology analysis for old release

### ISSUE THREAD

**Issue by YangpingLi** [geneontology/helpdesk#327]
I conducted Gene Ontology analysis for a gene list by "http://geneontology.org/" in June. However, when I trying to reproduce this analysis today, the result is different from the previous one.

I realize that the database has been updated and current release is 2021-07-02. So I'm wondering if it is possible that I can specify the old release of database and reproduce the analysis so that I can make everything in my manuscript consistent.

Thank you in advance for your help!

Yangping

**Comment by pgaudet** [comment]
Dear @YangpingLi 

You can get older releases from this location: 
http://release.geneontology.org/

Best regards, Pascale

**Comment by YangpingLi** [comment]
Hi Pascale,

Thank you for your help! I've found the proper release in "http://release.geneontology.org/". Could you please explain how can I use this release for GO analysis?

Is it web based or I have to install it on local? It could be very helpful if there's a manual or detailed pipeline for this kind of analysis.

Thank you so much!

Yangping

**Comment by YangpingLi** [comment]
> Dear @YangpingLi
> 
> You can get older releases from this location:
> http://release.geneontology.org/
> 
> Best regards, Pascale

Hi Pascale,

Thank you for your help! I've found the proper release in "http://release.geneontology.org/". Could you please explain how can I use this release for GO analysis?

Is it web based or I have to install it on local? It could be very helpful if there's a manual or detailed pipeline for this kind of analysis.

Thank you so much!

Yangping

**Comment by pgaudet** [comment]
Dear @YangpingLi , 
you should be able to navigate to the file you need. 

I am assuming you want 
`2021-06-16`
 and then in the ontology folder you can get the file you need. 

If you had used 'go-basic.obo', for the June release the direct link is: 
http://release.geneontology.org/2021-06-16/ontology/go-basic.obo

Thanks, Pascale
