### ISSUE TITLE
Data Dump for Plant GO Annotations

### ISSUE THREAD

**Issue by Shalsh23** [geneontology/helpdesk#328]
Hello,

I am trying to download all the GO annotations for the root plant taxon `Viridiplantae` and its descendants. 

1. Download Annotations [page](http://current.geneontology.org/products/pages/downloads.html) has only `Arabidopsis`.
2. The [directory](http://current.geneontology.org/annotations/) of annotations has nothing for plants.

I was able to filter for the needed annotations on [QuickGO](https://www.ebi.ac.uk/QuickGO/annotations?taxonId=33090&taxonUsage=descendants&geneProductType=miRNA,complex,protein) but it supports export of only 2 million annotations while I am looking to download all the 53 million returned. Ideally, a data dump file with all the plant annotations would be great, but if that isn't available can you please advise on the best way to get this data file?

**Comment by suzialeksander** [comment]
Hi @Shalsh23, 

Thank you for contacting the GO helpdesk.  We are currently working on making the annotations more accessible by taxon, but for now http://current.geneontology.org/annotations/index.html is your best bet.  You'll definitely want to take tair.gaf (or the gpad/gpi companion files) and sgn.gaf, as well as goa_uniprot_all.gaf.  That should be enough to get all the Viridiplantae annotations.

**Comment by suzialeksander** [comment]
Also, it was just suggested that  https://ftp.ebi.ac.uk/pub/databases/GO/goa/UNIPROT/ might work for you as well.

**Comment by Shalsh23** [comment]
This is helpful, thanks!

**Comment by suzialeksander** [comment]
Closing the issue as there's an alternative to retreive through EBI, but we are still working on making annotations more accessible through GO
