### ISSUE TITLE
Gene Ontology terms with GO IDs and their hierarchical relationship

### ISSUE THREAD

**Issue by chrispam10** [geneontology/helpdesk#329]
Hello,

Is there any way I can get a table for all Gene Ontology terms (eg.  acetyl-CoA biosynthetic process from pyruvate ) and their corresponding GO IDs (eg. GO:0006086) along with whether they are a parent or child node of whichever Gene Ontology/GO ID?

I would like to have them in a tabular format for visualization purposes.

**Comment by suzialeksander** [comment]
Hi @chrispam10, 

Have you looked at our Ontology file formats (descriptions available at http://geneontology.org/docs/download-ontology/, the permalinks there redirect you to current.geneontology.org)?
The relations in the go-basic.obo are described on http://geneontology.org/docs/ontology-relations/

If this isn't what you were looking for, please let us know.  Also, if you are looking to visualise specific terms, you might look at QuickGO's Ancestor Chart.  You can even put several terms in the Basket and have them all display on the same Ancestor Chart - when in your Basket, use the round icon that has no writing on it (it's a simple Ancestor Chart but looks a bit like a set of scales).
