### ISSUE TITLE
how to download the go list with the related user ids? the xml file doesn't work

### ISSUE THREAD

**Issue by rosafontana** [geneontology/helpdesk#334]
## To Reproduce

Please include any information you can about: what, where, when, and why. Please include any URLs involved in the issue.

## Additional context

Add any other context about the issue that you feel may be important. E.g. browser version, time of day.

**Comment by rosafontana** [comment]
how to download the go list with the related user ids? the xml file doesn't work

**Comment by suzialeksander** [comment]
Hi @rosafontana , I'm not sure what you're asking, feel free to use the three dots at the top of your comment to fill out the form or respond free-text in a comment below.  

If you're asking about go_daily-termdb.rdf-xml or go_monthly-termdb.rdf-xml, please see

http://geneontology.org/docs/faq/#why-am-i-having-issues-accessing-the-ftpcvssvn-service-where-is-go_daily-termdbrdf-xml-i-cant-find-a-file-weve-been-downloading-for-years

If you are looking for a simple ontology file, it's likely go-basic.obo will work for you, see http://geneontology.org/docs/download-ontology/ for a brief description.

**Comment by rosafontana** [comment]
Hi @suzialeksander thanks for the answer. I checked these links but I don't think they solve my issue. I will explain better my problem. I have a list of protein IDs and I run the GO for biological processes. using gene ontology website that is connected to Panther. When I download the list from panther with the GO terms in the format table it works, but I need the list of GO with the related protein IDs that I input on the website. The XML file that should contain this info doesn't work. Do you know if there is another way to get this list of Go that I got from my analysis with the related protein IDs?
Thanks
Rosa

**Comment by suzialeksander** [comment]
OK, thanks for the details.  When you say 
>The XML file that should contain this info doesn't work
does that mean the " XML with user input ids" download is blank, fails to download, or just doesn't contain the information you're looking for (which I'm reading as the protein IDs you uploaded)? 

Also going to bring in @mugitty from the PANTHER team, who can better answer this.

**Comment by rosafontana** [comment]
I can download the XML but when I tried to open it with Excel I can only see the first column and all the data are missing. WHen I opened it with Text it's all in Chinese. 

Thanks for helping me 

Rosa

**Comment by suzialeksander** [comment]
Sounds like @huaiyumi is on it.

**Comment by mugitty** [comment]
@rosafontana, drag the file into a browser.  You will be able to view with XML formatting.

**Comment by rosafontana** [comment]
@mugitty thanks it works now :) do you know how to convert in excel?

**Comment by mugitty** [comment]
@rosafontana, there are multiple levels in the document.  You need to use the XML data import feature. The system will prompt you and you have to select the fields to expand.

**Comment by rosafontana** [comment]
ok thank you so much :))
