### ISSUE TITLE
Need to update IEA documentation

### ISSUE THREAD

**Issue by suzialeksander** [geneontology/helpdesk#351]
Seems like what was ECO:0000501 is changing to be ECO:0007669.  Leaving a note here to update the wiki:

http://wiki.geneontology.org/index.php/Inferred_from_Electronic_Annotation_(IEA)

**Comment by suzialeksander** [comment]
Background ticket is https://github.com/evidenceontology/evidenceontology/issues/251

**Comment by pgaudet** [comment]
Wont fix. This was reverted in ECO, we are back to using ECO:0000501. Lets open a new documentation ticket when new changes are made in ECO.
