### ISSUE TITLE
GPAD v1.2?

### ISSUE THREAD

**Issue by dvklopfenstein** [geneontology/helpdesk#358]
## Is there a new GPAD version (1.2)?

I do not see GPAD version 1.2 documented at http://geneontology.org/docs/gene-product-association-data-gpad-format/

GPAD version 1.2 is found in .gpad annotation files from http://current.geneontology.org/annotations/.
GPAD version 1.1 is found in .gpa annotation files from https://ftp.ebi.ac.uk/pub/databases/GO/goa/HUMAN/

## Expected behavior

I expect the GPAD documentation to discuss v1.2 at http://geneontology.org/docs/gene-product-association-data-gpad-format/ if there is a new version.

If there is not a new GPAD version 1.2, I expect to not see it in the annotation files from http://current.geneontology.org/annotations/

Where might we find the documentation for v1.2?

## To Reproduce

Download .gpad or .gpa files from both http://current.geneontology.org/annotations/ and https://ftp.ebi.ac.uk/pub/databases/GO/goa/HUMAN/ and 

`$ grep version *.gpa*`

**Comment by suzialeksander** [comment]
Closing, as GPAD 2.0 is soon to be the official format.
