### ISSUE TITLE
PANTHER webiste down for maintenance 

### ISSUE THREAD

**Issue by apinharanda** [geneontology/helpdesk#36]
Hi, 

Since Satruday the PANTHER website seems to be down for maintenance (http://pantherdb.org) and 
I was wondering whether you were aware of this as when I check your status page it seems to indicate everything is working fine.
Do you have any predictions of when the service will be resumed? 

Thank you in advance,

Best,

Ana

<img width="1166" alt="captura de ecra 2017-07-10 as 11 47 19" src="https://user-images.githubusercontent.com/7189503/28014706-9a465b9c-6565-11e7-891e-1e2ed4863523.png">
<img width="1162" alt="captura de ecra 2017-07-10 as 11 49 32" src="https://user-images.githubusercontent.com/7189503/28014852-e019087c-6565-11e7-8f09-40e8140fe84e.png">

**Comment by cmungall** [comment]
@kltm - any idea why the false positive on the status page?
@mugitty - do you have an estimate of when panther/enrichment will be up again?

**Comment by kltm** [comment]
@cmungall The "test" just checks if a page is there, it doesn't run an analysis. 
If we at some point graduate to cachet.io, we can get a lot more serious.

**Comment by cmungall** [comment]
thanks @kltm good to know

@mugitty informs us that the panther service is up again so I will close this
