### ISSUE TITLE
GO-CAM model browser on 'geneontology.cloud' not loading.

### ISSUE THREAD

**Issue by malcolmfisher103** [geneontology/helpdesk#366]
## Describe the issue/bug

When trying to browse GO-CAM models from 'https://geneontology.cloud/browse' I get a 'Loading Models ...' message but they never load even after minutes.

## Expected behavior

After a reasonable time the GO-CAM model browser should load.

## To Reproduce

Go to 'https://geneontology.cloud/home' and click on the 'Browse Models' button.

## Additional context

I am using Chrome from the UK at around 4:28 pm GMT. I also encountered this issue a few days ago so it seems to be persistent.

**Comment by kltm** [comment]
@tmushayahama @dustine32 Would you have any idea what might be going on here? I took a look at the debug console, and while it was throwing an error, it wasn't apparent to me what *exactly* the error was. It seems like https://api.geneontology.cloud/models?last=12 might not be responding and that may be the underlying issue. Is this possibly another expression of https://github.com/geneontology/api-gorest/issues/3 , or a related problem?

**Comment by dustine32** [comment]
Short answer is the GO-CAM browser is trying to read an S3-cached file `gocam-goterms.json` (available [here](https://geneontology-public.s3.amazonaws.com/gocam/gocam-goterms.json)), but that file's contents are currently:
```
{"message": "Endpoint request timed out"}
```
This "message" is actually the response from https://api.geneontology.xyz/models/go, the route used to create `gocam-goterms.json`. So the root error appears to be somewhere in that api.geneontology.xyz route. It could actually be the SPARQL query timing out while running against the GO prod triplestore.

**Comment by kltm** [comment]
Trying to track progress foe this here: https://github.com/geneontology/api-gorest/issues/4

**Comment by suzialeksander** [comment]
Closed, resolved.
