### ISSUE TITLE
Where is the list of allowable relations in GO-CAM and information about use

### ISSUE THREAD

**Issue by RLovering** [geneontology/helpdesk#373]
Hi Chris

Following from the github ticket I submitted to obo-relations:
https://github.com/oborel/obo-relations/issues/226

It would be very nice to have a page that lists all the allowable relations in GO-CAM, when they should be used and how these align (or not) with the relations being used in AEs.

Plus information about the AEs that are created when GO-CAM models are exported

Probably this information exist but I have missed the notification about it

Thanks
Ruth

@cmungall

**Comment by vanaukenk** [comment]
Hi @RLovering 

We have this page on the GOC wiki that covers the main relations used:
http://wiki.geneontology.org/index.php/Annotation_Relations

As you now, we've been revising the relations used in GO, so we continue to update and work on the page above as well as the pages for the individual relations.

There is also the [ShEx](https://github.com/geneontology/go-shapes/blob/master/shapes/go-cam-shapes.shex), but that is not intended to be the main source of curator documentation.

There is still work to be done on the GO-CAM GPAD export, specifically wrt AEs, and there is an active GO [github project ](https://github.com/orgs/geneontology/projects/52 )for that work.

If you have specific questions about relations, please let me know and I will try to help.

Thanks,
--Kimberly

**Comment by RLovering** [comment]
Thank you so much and apologise for forgetting about all of this
Happy New Year
Ruth
