### ISSUE TITLE
Pfam2go download is corrupt

### ISSUE THREAD

**Issue by fra-gh** [geneontology/helpdesk#38]
The pfam2go file http://geneontology.org/external2go/pfam2go is just an error message. 
interpro2go, smart2go, and other files updated on Jul 16 have the same issue. 

Can it be fixed? Thanks.

**Comment by kltm** [comment]
@fra-gh Our apologies for the outage--this should now be fixed: https://github.com/geneontology/go-site/issues/411#issuecomment-316298816
