### ISSUE TITLE
Discrepancy between AmiGO and remote MySQL-amigo server database

### ISSUE THREAD

**Issue by jzqin** [geneontology/helpdesk#39]
Hi,

I have a question about how AmiGO queries the Gene Ontology database. I have a found a couple instances of AmiGO queries matching gene products to terms that differs from queries I make locally on a copy of the MySQL GO database.

For instance, when I search AmiGO for the gene _Herc2_ in _Mus musculus_, 21 annotations are returned. However, when I connect via mysql to the latest version of the remote MySQL database (hosted on mysql-amigo.ebi.ac.uk, with the credentials taken from http://www.geneontology.org/page/lead-database-guide), and load the view "term_J_association_J_gene_product" with the following query:
```
SELECT * FROM go_latest.term_J_association_J_gene_product
WHERE gp_symbol = 'Herc2'
AND gp_species_id = 336870
```
I receive 28 annotations. Among these extra 7 annotations are unique terms like "ligase activity" and "ribosomal S6-glutamic acid ligase activity". Even when I download the latest release of the full database, the query results are slightly different.

Another example is _Sharpin_ in _Mus musculus_, which in my local database is annotated with "nucleus". Via the AmiGO website, nucleus isn't one of the annotations returned for _Sharpin_.

Is this purely a result of difference in version of the database between the remote mysql-amigo server and the backend database for the AmiGO website? Or are there specific references that are filtered out of queries returned by the AmiGO web interface?

Thank you!
Jason

**Comment by kltm** [comment]
@jzqin Apologies for a quick answer.

I suspect what you're seeing is essentially the difference between the "assocdb" and the "full" db:
http://www.geneontology.org/page/lead-database-guide#dbtypes
While AmiGO is no longer directly driven by an SQL backend, the data load that it does use is more similar to the "assocdb" load in that it does not include the full IEA set. You should see more similar numbers with evidence filtering.

In addition to that, the "full" db is somewhat out of date at this point as we are transitioning to a new pipeline. #4 gives a good overview.

**Comment by jzqin** [comment]
Your solution did the trick. Thank you! I see that I can get access to the graph through https://github.com/geneontology/go-graphstore/

The README says that the build isn't stable - do you know when a stable build will be released?

**Comment by kltm** [comment]
@jzqin 
No problem.
Unfortunately, I cannot give you a firm date other than "ASAP". This transition is currently a main focus of our group, but we are still testing.
