### ISSUE TITLE
GO-UBERON annotation queries

### ISSUE THREAD

**Issue by NatalieThurlby** [geneontology/helpdesk#40]
I am wondering if there is any guidance for using the annotations between GO and other ontologies (e.g. UBERON), specifically with respect to propagating annotations between two ontologies.

I am trying to do some research about the tissue-specific gene expression (related to genes being more highly expressed in tissues which they effect) and I'm trying to use GO-UBERON annotations as part of this work.

For example, if a given GO biological process term occurs_in an UBERON tissue term, is it safe to say that for example:
- the GO term occurs_in all parents tissues of the UBERON term?
- the GO term occurs_in at least one one of the children of the UBERON term?
- At least one of the children of the GO term occurs_in the UBERON term?
Etc

And how do these relationships change if the relationship is instead (for example, results_in_morphogenesis_of instead of occurs_in)?

Is there any guidance about this anywhere? 

Thanks!

**Comment by cmungall** [comment]
Hi Natalie,

All of the relation composition rules used by GO are in the RO. Most of these are visible by looking at the PURL, e.g

http://purl.obolibrary.org/obo/BFO_0000066

![image](https://user-images.githubusercontent.com/50745/28723329-459d87a0-736b-11e7-83d5-d42947261f1a.png)

You can also see these in Protege. Let us know if you need help understanding the OWL constructs, the main ones for your purposes as subPropertyOf, TransitiveProperty and PropertyChains, the latter can be thought of as rules. E.g.  given

 1. P occurs_in C
 2. C part_of D
 3. `occurs_in o part_of -> occurs_in`

You infer P occurs_in D

I would avoid writing any code for this. this can all be done using standard OWL reasoners.

In some cases there may be no chain specified and no way to 'reduce' a chain to a simpler relationship. E.g. if X r-i-m-o Y and Y part-of Z then there may not be much more to say than "X r-i-m-o a part of Z"

For propagating annotations you'll need to know what the relationship is between the gene product and the annotated term to apply the logic

See: https://github.com/geneontology/go-annotation/blob/master/specs/gpad-gpi-1_2.md#default-annotation-relations

**Comment by cmungall** [comment]
@geneontology/ontology team - we should have better user-facing documentation for this, and I think it would be good to have in our internal editors guide docs, what do you think?

**Comment by cmungall** [comment]
@NatalieThurlby - you will also want to use annotation extensions where possible as these will give you greater tissue specificity. Let us know how you get on!
