### ISSUE TITLE
Visualization result of a set of GO terms in DOT file format?

### ISSUE THREAD

**Issue by cytrix1** [geneontology/helpdesk#420]
The currently working amigo visualization tool for GO terms only provides results as PNG and SVG format?
[http://amigo.geneontology.org/visualize?mode=client_amigo](http://amigo.geneontology.org/visualize?mode=client_amigo)

According to Tang's blog, DOT format was also available, but the link to the service is broken.
[https://davetang.org/muse/2012/12/27/gene-ontology-graph-visualisation/](https://davetang.org/muse/2012/12/27/gene-ontology-graph-visualisation/)

How can I get results as DOT format?

Thanks in advance.

Young Soo

**Comment by cytrix1** [comment]
http://amigo.geneontology.org/visualize?mode=amigo&inline=false&term_data=GO%3A0007272&format=dot&term_data_type=string

That would be quite useful if only more than one term_data is allowed. Is it possible to submit GO:0007272 and GO:99536 and get an entire GO graph including all the submitted GO terms?

Young Soo

**Comment by kltm** [comment]
@cytrix1 I'd go ahead with playing with the visualize client and changing the output manually; e.g.:
http://amigo.geneontology.org/visualize?term_data_type=string&mode=amigo&term_data=GO%3A0007272%0D%20GO%3A0099536&inline=false&format=png
and
http://amigo.geneontology.org/visualize?term_data_type=string&mode=amigo&term_data=GO%3A0007272%0D%20GO%3A0099536&inline=false&format=dot
Again, this is an unsupported hack and the current "official" solution would be to look at the obographviz software.
