### ISSUE TITLE
Clarify CC BY 4.0 licensing terms for attribution

### ISSUE THREAD

**Issue by kltm** [geneontology/helpdesk#423]
We recently received an email on the helpdesk asking for specific guidance WRT attribution for the GO as defined in the CC BY 4.0 license within the context of an online platform. Currently, we do not give such specific guidance and only refer to the license itself.
We should define what attribution should be given for data reuse, with examples for a couple of categories so that our intent is clear.

**Comment by kltm** [comment]
Wording for CC BY 4.0:
Section 3a of https://creativecommons.org/licenses/by/4.0/legalcode

CC BY 4.0 attribution elements:
https://wiki.creativecommons.org/wiki/License_Versions#Detailed_attribution_comparison_chart

**Comment by pgaudet** [comment]
Whatever new text we agree on should also go on this page: http://geneontology.org/docs/go-citation-policy/

**Comment by kltm** [comment]
Okay, after the managers' call, I'll go ahead and put something together that hits the points of:
- exists near downloads and in documentation
- asks for versions to be mentioned

**Comment by kltm** [comment]
Text added. Not sure who is "owner" here. Added to "GO Website Improvements" for lack of better location.

**Comment by kltm** [comment]
@suzialeksander Ah--you're owner!

**Comment by suzialeksander** [comment]
I think the only thing to be added here, possibly, are links to each software licence. I'm not sure what the complete list is- Amigo, PANTHER, Noctua ??.  It would be nice to have a kinda current list of active-ish tools.

@kltm what tools/licences are we missing?

**Comment by kltm** [comment]
I think the scope of this ticket is specifically the changes to the CC BY 4.0 verbiage wrt what qualifies as attribution.

Software licensing should be another matter or ticket. Technically speaking, every software repo needs to have a LICENSE file at the top level: https://github.com/orgs/geneontology/repositories

**Comment by suzialeksander** [comment]
OK that settles it for me.  @pgaudet does this new text look sufficient to close this ticket?

**Comment by pgaudet** [comment]
Just wondering - is the '2023-01-01 release' an example? 

If that's the case, it may be better to have YYYY-MM-DD release', so this dont look out of date in a few months/years?

**Comment by kltm** [comment]
@pgaudet 
` For example, if you are...`
I think that it's clear that it's an example, but please feel free to change the text to whatever you feel is necessary to close this out.

**Comment by suzialeksander** [comment]
@pgaudet I do also try and update the years that appear in the text of the site so it doesn't look old, including the FAQ but also these other pages.  It's fairly trivial to update these every year or two, like the copyright dates.
