### ISSUE TITLE
Question about logo usage

### ISSUE THREAD

**Issue by kevinrue** [geneontology/helpdesk#43]
Hello!

I read the [citation policy](http://www.geneontology.org/page/go-citation-policy#GO_Logo) but still wanted to make sure with you guys that you're happy with me using the GO logo in my Bioconductor sticker logo as can be seen [here](https://github.com/kevinrue/BiocStickers/blob/master/GOexpress/GOexpress.png)

My package is primarily designed to run on GO annotation data, which is what my logo is intended to convey. I hope that's all right with you!

Anything I missed, please let me know!

Best regards,
Kevin

**Comment by kltm** [comment]
@kevinrue 
I think that if you are following the terms in the citation policy and CC BY 4.0 you should feel fine.
The one think that we like to avoid is any implied endorsement or sanctioning of a particular project or piece of software, unless it has gone through an official internal vetting process (and it would then show up in our official documentation anyways).
Now, all that said, personally, I think this is fine, and certainly within the accepted use.
