### ISSUE TITLE
Make it clear the sourceforge page is outdated/remove?

### ISSUE THREAD

**Issue by suzialeksander** [geneontology/helpdesk#437]
I keep coming across https://sourceforge.net/projects/geneontology/, and not sure if the header is accurate (could be bots) but it always has 0< "downloads this week". Seems like SVN allows *something* to be downloaded, and worse calls it 'snapshot' that could be muddy to users.

@kltm looked around at settings to turn off anything obvious.

The SF pages also suffer from broken links like 
> Best Way to Get Help
Gene Ontology says the best way to get help with its software is by visiting http://geneontology.org/help.shtml. 

Not sure if we can delete these or need to add to the list of redirects on our site.

@pgaudet should this be added to manager's call, or is ok to turn off everything on SF that we can?

**Comment by kltm** [comment]
Making some changes.

**Comment by kltm** [comment]
@suzialeksander @pgaudet Putting this in website improvements project.

**Comment by pgaudet** [comment]
> we should probably just remove the old SF stuff all together

+1

**Comment by suzialeksander** [comment]
I don't know there's anything else to be done. Still are 300+ downloads a week, mostly from HK, so that might be residual bot activity. @kltm OK to close this?
