### ISSUE TITLE
Wrong media type for .obo downloads

### ISSUE THREAD

**Issue by jar398** [geneontology/helpdesk#44]
The media type for `http://purl.obolibrary.org/obo/go.obo` is rdf+xml, which is wrong. I don't know what it should be - text perhaps - but it shouldn't be rdf+xml.

```
bash-3.2$ curl -I -L http://purl.obolibrary.org/obo/go.obo
HTTP/1.1 302 Found
Date: Sat, 05 Aug 2017 12:03:48 GMT
Server: Apache/2.4.7 (Ubuntu)
Location: http://snapshot.geneontology.org/ontology/go.obo
Content-Type: text/html; charset=iso-8859-1

HTTP/1.1 200 OK
Content-Type: application/rdf+xml
Content-Length: 36388562
Connection: keep-alive
Date: Thu, 03 Aug 2017 17:04:18 GMT
Last-Modified: Thu, 03 Aug 2017 14:18:37 GMT
ETag: "cc9fa236353864d31cd2af755337253e-3"
x-amz-meta-s3cmd-attrs: uid:114/gname:skyhook/uname:jenkins/gid:1003/mode:33188/mtime:1501744075/atime:1501744083/md5:6829075a7f7b950c08509ad414113dfa/ctime:1501744075
Accept-Ranges: bytes
Server: AmazonS3
X-Cache: RefreshHit from cloudfront
Via: 1.1 72882d2d20025ce740b1efae5c3e8544.cloudfront.net (CloudFront)
X-Amz-Cf-Id: 40KAOVo0BLaF2pDhpMV0uQaA38gOErcmDsRioxvHX5hPHVtNT3ZAaw==

bash-3.2$ 
```

**Comment by kltm** [comment]
@jar398 Thank you for bringing additional details. This ticket is currently being handled on the pipeline tracker: https://github.com/geneontology/pipeline/issues/8

**Comment by jar398** [comment]
Thanks for looking into this. By the way that URL (https://github.com/geneontology/pipeline/issues/8) gives a 404. Perhaps the repository is private.

Jonathan

**Comment by kltm** [comment]
Ugh, yes, private repo--thank you for pointing that out. Rest assured that this is a high-priority item.
The repo will be opened as soon as we do a final sweep to ensure that there is no leaked information.
