### ISSUE TITLE
number of curated papers

### ISSUE THREAD

**Issue by dhldhl** [geneontology/helpdesk#45]
Hi, I'm trying to estimate how many papers have been curated for GO. This can be broken down into several more specific questions:

1) how many papers contain EXP annotations.
http://amigo.geneontology.org/amigo/base_statistics#experimental-annotation-publications-by-assigner

The last figure on this page has some numbers, but they appear to be high. For example, according to Fig 3, there are around 700k experimental annotations. If we add up the # of papers in the last figure, it's around 1million, less than the # of total EXP annotations.

2) is there any estimate on how many papers contain gene function information?

I'm trying to scope out how much work remaining to be done for GO annotation. Thanks,

Donghui

**Comment by kltm** [comment]
@dhldhl Hey there!
I suspect the information you want, and why the numbers are "off", is to be found in this issue thread: https://github.com/geneontology/amigo/issues/429 (and a side trip to https://github.com/geneontology/amigo/issues/364)
For the number that people typically want, there needs to be another filtering step in the generation.

**Comment by dhldhl** [comment]
ah, thanks!
in geneontology/amigo#429, there is a table (copied here but format messed up). The numbers in that table look more realistic. Is the last column the # of references that have EXP annotations (or close estimate)?


Stats from @RLovering:    
NAME			       ANNOTATIONS REFERENCES     ------------------------------ ----------- ----------     RGD				     52957	20341     MGI				    104462	17988     UniProt (EBI Curators)		     93287	17308     UniProt (SIB Curators)		     75942	15202     SGD				     39499	10736     FlyBase 			    119281	10076     IntAct				     99178	10014     TAIR				     58670	 8516     Proteome Inc			     14704	 6396     ZFIN				     57528	 5110     EcoCyc				     12422	 4748     BHF-UCL 			     34961	 4709     WormBase			     23622	 3378     PomBase 			     23015	 2702     CACAO				      3779	 2275     AgBase				     19717	 1923     CGD				      9867	 1751     DictyBase			      8555	 1457     Aspergillus Genome Database	      6149	 1421     MTBBASE 			      7620	 1131     EcoliWiki			      2254	  941     PseudoCAP			      2622	  821     Reactome			      1370	  738     Automated Function Prediction	      7018	  735     GeneDB P. falciparum		      5387	  725     ParkinsonsUK-UCL		      6395	  712     CollecTF			      4379	  602     HGNC				      3742	  598     GeneDB T. brucei		      4390	  518     UniProt (PIR Curators)		      1724	  512     NTNU				      1537	  464     Leishmania major GeneDB 	      1033	  279     GO_Central			       616	  163     SynGO				       317	  155     Gramene 			      1457	  151     AlzheimersResearchUK-UCL	       943	   69     Microbial ENergy processes Gen	       101	   59     Alzheimers Project at Universi	       227	   48     DFLAT				       612	   47     TIGR				     10487	   34     GOC OWL Inferences			50	   33     SYSCILIA_CCNET			       162	   33     J. Craig Venter Institute	      2310	   29     Roslin Institute			73	   19     PAMGO A. tumefaciens			76	   19     GDB				       130	   16     SynGO-UCL (UCL Curators)		71	   10     PAMGO M. grisea 		       322	   10
--

**Comment by kltm** [comment]
You'd have to ping @RLovering to learn exactly how that table was generated--I cannot find the email at the moment.
I've iterated a bit on what @cmungall mentioned in https://github.com/geneontology/amigo/issues/429

**Comment by RLovering** [comment]
QuickGO can give you this information, using the filters and the stats tabs
