### ISSUE TITLE
Annotation 'Qualifier' is now really 'Relationship'

### ISSUE THREAD

**Issue by rarebres805** [geneontology/helpdesk#452]
**Please describe your question, idea, or concern.**
With the change to GAF 2 file format for annotations, the allowed values of 'Qualifier' changed, and they no longer actually reflect the original scope of meaning, but now really represent 'Relationship', as described in the GAF documentation.  I respectfully submit that 'Qualifier' is no longer an appropriate designation and the header and documentation should be updated.
Note that the documentation page of the GO web site (http://geneontology.org/docs/go-annotations/) still only reflects the old value types/options.

**Comment by suzialeksander** [comment]
Hi @rarebres805, thanks for this feedback! We understand this is a point of confusion for many.  Let me pass along this suggestion and see what we can do. 

Pinging @vanaukenk or maybe @cmungall

**Comment by vanaukenk** [comment]
Thanks for the feedback and suggestions @rarebres805 
The text at: http://geneontology.org/docs/go-annotations/ should definitely be updated.
We'll otherwise discuss the suggestion to update the header and documentation for GAF.

**Comment by suzialeksander** [comment]
Changed GAF document, column 4 is now Relations not Qualifier. This column isn't required to be listed in the header. 

https://github.com/geneontology/geneontology.github.io/pull/558
