### ISSUE TITLE
Term enrichment, possible bug?

### ISSUE THREAD

**Issue by nataled** [geneontology/helpdesk#455]
Having some trouble with the term enrichment service on https://amigo.geneontology.org/amigo. Leaving all defaults as is (biological process; Homo sapiens) and entering a list of UniProtKB accessions or gene names, after submitting I get an error message:

"Error parsing request, no input specified"

Not that the specific list matters, but here's what I used:

O15287
O15350
O15527
O43543
O76064
O94782
O95243
P07992
P12956
P13010
P16104
P16455
P18074
P19447
P23025
P24522
P25490
P28340
P28715
P38398
P39748
P43246
P46736
P49917
P51587
P52701
P54132
P63146
P78527
Q01831
Q03468
Q06609
Q13216
Q13315
Q13330
Q13535
Q13620
Q13888
Q14191
Q15004
Q16531
Q49AN0
Q5FWF4
Q68E01
Q6PIW4
Q6UWZ7
Q7L7L0
Q7Z2Z1
Q86UA6
Q8IYW5
Q92466
Q92547
Q92698
Q92889
Q96AH0
Q96B01
Q96EB6
Q96K76
Q96RL1
Q96T60
Q99502
Q99504
Q9BQ15
Q9BXW9
Q9H040
Q9H9F9
Q9H9Q4
Q9NRY2
Q9NS91
Q9NWV8
Q9NX61
Q9NXR7
Q9NZJ0
Q9UBZ9
Q9ULG1
Q9Y253

**Comment by kltm** [comment]
Noting for @mugitty and @dustine32 that I tried variations from both the old-AmiGO hook-up and the newer GO landing page.

**Comment by dustine32** [comment]
Thanks @nataled @kltm for informing us! I tried that list myself from [amigo](https://amigo.geneontology.org/amigo) and got the same error, but that was after clicking through a scary Chrome "The information you’re about to submit is not secure" page:
![image](https://github.com/geneontology/helpdesk/assets/2678599/34f40fad-efb8-4adc-aa67-b32570000d2e)
My guess here (@mugitty is out until Tues) is that something broke when we recently switched pantherdb.org to HTTPS and the POSTed genelist is lost in that intermediate warning page. @kltm Maybe this amigo page is still using the none-HTTPS PANTHER URL?

I was able to successfully use the enrichment tool on [geneontology.org](https://geneontology.org/) as well as [pantherdb.org](https://pantherdb.org/).

**Comment by nataled** [comment]
Thank you @ktlm for directing this properly. My only follow-up to what you said is that any requirement for a UniProtKB prefix would have to be rather new-ish. In the past I've used the accessions as-is, or just a list of genes, or even an accession + gene input (like 'Q9Y253   POLH'), all of which gave the same result.

I too got the 'scary message' using both Edge and Firefox.

**Comment by nataled** [comment]
Confirmed that it works exactly as expected on [geneontology.org](https://geneontology.org/).

**Comment by kltm** [comment]
(@nataled noting that `@KTLM` is a different user than me @kltm ). I'll edit your comment to try and prevent confusion on their end.

**Comment by dustine32** [comment]
Oh yeah @nataled, PANTHER ID mapping is very forgiving with UniProtKB IDs not containing the prefix so that shouldn't be the problem.

**Comment by kltm** [comment]
@dustine32 While I get the scary message, I'm a little surprised that clicking through it doesn't work anyways. That said, we have not looked at the AmiGO/PANTHER hook-up for a long time, so maybe we need a little polish there. Is there anything at https://github.com/geneontology/amigo/blob/8fad36622ea66fb21e544490cdc29e2b1af18c24/templates/html/bs3/pages/landing.tmpl#L114 that doesn't look right to you at this point (delta https vs https)?

**Comment by dustine32** [comment]
@kltm Yeah, I'm not very familiar with the amigo->PANTHER code but that [landing.tmpl](https://github.com/geneontology/amigo/blob/8fad36622ea66fb21e544490cdc29e2b1af18c24/templates/html/bs3/pages/landing.tmpl#L114) line has a variable `interlink_rte` that _may_ be referencing the web service URL specified in [rte_resources.yaml](https://github.com/geneontology/amigo/blob/8fad36622ea66fb21e544490cdc29e2b1af18c24/conf/rte_resources.yaml#L8). This is the only instance of the PANTHER webservice URL I could find in the repo so I'm suspecting that needs to be changed to HTTPS.

I can try testing this with a local amigo instance if that's easy to set up.

**Comment by kltm** [comment]
@dustine32 We can easily update that URL at https://github.com/geneontology/amigo/blob/master/conf/rte_resources.yaml; I was more wondering about the other parameters that are getting in there and whether they might be causing issues.

**Comment by dustine32** [comment]
@kltm Ah, right! Ok, I'll double-check the params in `landing.tmpl`, comparing them to the geneontology.org page enrichment code.

**Comment by dustine32** [comment]
The only diff in params with the GO site enrichment code ([index.html](https://github.com/geneontology/geneontology.github.io/blob/4b8a08b0d187a3f34a71e9e525be0f03c5705417/index.html#L113)) is that the default statistical `correction` is `"bonferroni"` (amigo) vs `"fdr"` (GO), which might alter the numbers a bit (both are legit [options](https://www.pantherdb.org/services/openAPISpec.jsp)) but should still produce results.

I'm now suspecting that the automatic HTTP->HTTPS upgrade on the PANTHER web server redirects everything to a `GET` request. This would drop `POST` payload data carrying the enrichment form params. We could (well, hoping @mugitty when she gets back) fix this to always redirect _and_ retain request type, but we could also avoid this situation by updating that URL in [rte_resources.yaml](https://github.com/geneontology/amigo/blob/master/conf/rte_resources.yaml). @kltm What do you think? Shall I make a PR?

**Comment by kltm** [comment]
@dustine32 V/nice: a GET conversion would explain everything!
If the rest is looking good: yes, a PR would be appreciated and I'd put it right out.

**Comment by kltm** [comment]
Okay, I've tested and this seems to be cleared now from the AmiGO side of things. Thank you @dustine32 !
