### ISSUE TITLE
QUESTION about GO:0000112

### ISSUE THREAD

**Issue by monicacecilia** [geneontology/helpdesk#459]
**Please describe your question, idea, or concern.**

A Monarch user asked a question about the representation of cellular components in GO. 

> Anatomy associations are misleading. These include GO annotations. For example, _S. cerevisiae_ has an annotation _expressed_in_ [nucleotide-excision repair factor 3 complex.](https://amigo.geneontology.org/amigo/term/GO:0000112) Which seems strange? (it's _part_of_, not an expression location)

I see the note in the description of the term, which notes that _"process and function information are included in the term and definition for the purpose of describing and distinguishing the complex"_. Could we kindly ask you to please expand and shed some additional light on GO's reasoning for considering the complex as a cellular location?

Thanks!

**Comment by cmungall** [comment]
See https://geneontology.org/docs/ontology-documentation/

Cellular Component | The locations relative to cellular structures in which a gene product performs a function, either cellular compartments (e.g., mitochondrion), or stable macromolecular complexes of which they are parts (e.g., the ribosome). Unlike the other aspects of GO, cellular component classes refer not to processes but rather a cellular anatomy.
-- | --

I think the confusion is coming from the predicate *expressed_in* which doesn't come from GO
