### ISSUE TITLE
secretome and membrane receptor profiles

### ISSUE THREAD

**Issue by cmungall** [geneontology/helpdesk#46]
Can we use GO to give a satisfactory answer for:

https://bioinformatics.stackexchange.com/questions/2241/secretome-and-membrane-receptor-profiles/2268

**Comment by cmungall** [comment]
See my comments on the ticket for the part about querying for membrane proteins.

Can we use GO to obtain the 'secretome'? In GO, "being secreted" is not a function. We annotate gene products that perform some function as part of secretory pathways, but we don't annotate gene products that are secreted.

However, we should still be able to find some secreted proteins. For example, if we look at extensions PRR1 is secreted by the lacrimal gland
http://amigo.geneontology.org/amigo/gene_product/UniProtKB:Q16378
We can see this gene product is in the extracellular space and is part of a salivary secretion.

A query for genes that are extracellular AND part_of some (uberon:secreted substance) would return some of the desired genes.

**Comment by kltm** [comment]
@cmungall Is there any more action for this Helpdesk item, or can we close it?
