### ISSUE TITLE
report-direct-ann-term.yml 

### ISSUE THREAD

**Issue by ValWood** [geneontology/helpdesk#462]
## Describe the issue/bug

The Github workflow workflows/report-direct-ann-term.yml 
https://github.com/geneontology/go-annotation/actions/runs/6710492686

has failed

**Comment by kltm** [comment]
@ValWood I'm not sure why this is an error? It reports:
" ERROR:annotation-review-report:no terms found or label filtered"
Looking at the body of
https://github.com/geneontology/go-annotation/issues/4807#issue-1970991393
There are no terms, so this would be the expected outcome.
Please reopen if I'm misunderstanding.
