### ISSUE TITLE
Download links do not work

### ISSUE THREAD

**Issue by Cimorgh-IT** [geneontology/helpdesk#464]
## Describe the issue/bug

Hello
I would like to download gene ontology terms data from this webpage: http://current.geneontology.org/products/pages/downloads.html
for the Homo sapiens Proteins.  I am coping the link and using wget or other downloading tools , but it can not download and fails. 
 
## Expected behavior

I expect to download the content in each linl.
## To Reproduce

[Please include any information you can about: what, where, when, and why. Please include any URLs involved in the issue.
Page: http://current.geneontology.org/products/pages/downloads.html
link: http://geneontology.org/gene-associations/goa_human.gaf.gz
## Additional context

I tried with different browsers in windows 10 and different commands such as wget, curl and axel in linux

**Comment by nlharris** [comment]
I just went to http://current.geneontology.org/products/pages/downloads.html, clicked on [goa_human.gaf](http://geneontology.org/gene-associations/goa_human.gaf.gz) (gzip), and it downloaded right away. (I'm using Chrome on a Mac.)

**Comment by suzialeksander** [comment]
@Cimorgh-IT Thanks for reporting this.  Can you try downloading it again? I also was able to grab the file from the specified URL.  

If you're not in the US, can you VPN to the USA/UK/etc.? We've had some IP-related issues on PANTHER and as far as I'm aware there shouldn't be any IP-related issues with these GAF/GPAD files, but it might explain why @nlharris and I were able to get this file without any issues. 

I've also tried to attach the file I just downloaded,  it is`!date-generated: 2023-10-10T15:24`
[goa_human.gaf.gz](https://github.com/geneontology/helpdesk/files/13418956/goa_human.gaf.gz)

**Comment by kltm** [comment]
@Cimorgh-IT 

I suspect you are suffering from this issue: https://github.com/geneontology/go-site/issues/2154
This should be fixed with the next release. Until then, as mentioned above, manually entering the URL or changing the link URL to HTTPS should work.

Best,

-Seth

**Comment by Cimorgh-IT** [comment]
Thanks for the response. It worked.


----- Original Message -----
