### ISSUE TITLE
I would like to work with all GO-CAM statements available. For this purpose, would you recommend me to use the available...

### ISSUE THREAD

**Issue by kltm** [geneontology/helpdesk#469]
Thanks for replying. I would like to work with all GO-CAM statements available. For this purpose, would you recommend me to use the available .sif files, or shall I work with Turtle files?

_Originally posted by @NeginBabaiha in https://github.com/geneontology/gocam-sif-pyexport/issues/5#issuecomment-1877651969_

**Comment by kltm** [comment]
@NeginBabaiha As this code is unsupported (and I believe unused at this point), and you want to work with all statements, the current best bet would be the TTL files.
@balhoff May have some other ideas here as well.

**Comment by balhoff** [comment]
I agree, the Turtle files would be best for now.
