### ISSUE TITLE
latest-full/go_monthly-assocdb-tables.tar.gz

### ISSUE THREAD

**Issue by cornett** [geneontology/helpdesk#47]
The following file is dated Jan 2017:

http://archive.geneontology.org/latest-full/go_monthly-assocdb-tables.tar.gz

In prior years, this file was updated 5-6 times per year.    Has the policy changed, or is some technical problem with monthly updates?

Thanks !

**Comment by kltm** [comment]
@cornett 
Our apologies for the inconvenience. We are in a bit of a transition period right now, but there will be no further builds of the full database. For more details, please see the discussion on this issue: https://github.com/geneontology/helpdesk/issues/4
We are just completing our pipeline for the new SPARQL endpoint, and will have a beta development snapshot available later today.

**Comment by cornett** [comment]
Thanks for clearing that up.
