### ISSUE TITLE
BUG?: PomBase annotation has disappeared from AmiGO

### ISSUE THREAD

**Issue by ValWood** [geneontology/helpdesk#470]
## Describe the issue/bug

Not sure. Pombase has 25 annotations to 
https://www.pombase.org/term/GO:0016891

but in aAMiGO currently, only 1 IEA
https://amigo.geneontology.org/amigo/term/GO:0016891

**Comment by ValWood** [comment]
Most annotation does seem to be there. I casn't figure out why this term is a problem....

**Comment by ValWood** [comment]
Ignore!

**Comment by pgaudet** [comment]
@ValWood did you mean to reopen this?

**Comment by ValWood** [comment]
No I always forget tot click the button again if I select "no action"
