### ISSUE TITLE
Duplicate annotation in AmiGO

### ISSUE THREAD

**Issue by ValWood** [geneontology/helpdesk#471]
## Describe the issue/bug

I noticed some duplicate annotations in AmiGO:

<img width="1141" alt="Screenshot 2024-01-31 at 09 27 33" src="https://github.com/geneontology/helpdesk/assets/7359272/ec1e90fe-47d8-42bb-93fb-3e9f09f4b626">

I didn't check how pervasive this is

## To Reproduce

Please include any information you can about: what, where, when, and why. Please include any URLs involved in the issue.

## Additional context

Add any other context about the issue that you feel may be important. E.g. browser version, time of day.

**Comment by pgaudet** [comment]
Actually they are not duplicates - one is IDA, one is EXP, in each case.

**Comment by ValWood** [comment]
Right, I started at that for ages! I did everything wrong yesterday.

**Comment by pgaudet** [comment]
This has also happened to me.... you think you have checked each column one by one, but no...
