### ISSUE TITLE
Issue when using API (Gene Ontology Ribbon Sandbox) with plant genes and GO terms

### ISSUE THREAD

**Issue by AyoubMaatouch** [geneontology/helpdesk#476]
Dear gene ontology team
Thanks for provide use this amazing tool.
I trying to use the API ([Gene Ontology Ribbon Sandbox)](https://geneontology.org/ribbon.html) to map GO terms (plant species) but it not work with me. My question is what is exactly id to use, as seen in "https://geneontology.org/docs/ribbon.html" the tool use only the Authorized IDs as the following [MGD](http://www.informatics.jax.org/): MGI:1099800; [RGD](https://rgd.mcw.edu/): RGD:3017; [SGD](https://www.yeastgenome.org/): SGD:S000004328; [WB](https://wormbase.org/): WB:WBGene00019240; [FB](https://flybase.org/): FB:FBgn0035265; [ZFIN](https://zfin.org/): ZFIN:ZDB-GENE-040113-2; [Homo sapiens](https://www.uniprot.org/): UniProtKB:Q9BYF1. But no one for plant, so any idea to use plant data

**Comment by kltm** [comment]
@AyoubMaatouch When looking for identifiers for the species you're interested in, a good place to start might be AmiGO gene/gene product search: https://amigo.geneontology.org/amigo/search/bioentity
Using the organism filter on the side (e.g. https://amigo.geneontology.org/amigo/search/bioentity?q=*:*&fq=taxon_subset_closure_label:%22Arabidopsis%20thaliana%22&sfq=document_category:%22bioentity%22), you can see that [Arabidopsis thaliana](http://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=3702) has a mix of identifiers in use:

```
(28940)	AGI_LocusCode
(13687)	TAIR
(965)	UniProtKB
```

**Comment by LettuceCara** [comment]
Hi, 

I still don't understand how to enter Arabidopsis genes into Gene Ontology Ribbon Sandbox. Where can I find the correct ID format?

For example for the gene AT1G22770 I have tried:
AT1G22770
AT:1G22770
TAIR:AT1G22770
UniProtKB:Q9SQI2
AT:838883

But nothing is working

Thanks
Cara

**Comment by kltm** [comment]
Talking to @sierra-moxon, you may want to try IDs of the form `AGI_LocusCode:AT1G22770` (possibly your example) and `TAIR:locus:2199685`. Basically, the primary identifiers found in AmiGO should work: https://amigo.geneontology.org/amigo/search/bioentity?q=*%3A*&fq=source:%22TAIR%22&sfq=document_category:%22bioentity%22
