### ISSUE TITLE
Gene Ontology Ribbon JSON formating

### ISSUE THREAD

**Issue by AyoubMaatouch** [geneontology/helpdesk#478]
#### Hello geneontolodym,
hope you are well.
I want to ask a question in regards of using GO ribbon on JSON data, I'm trying to use it with a json formated data as you suggested in your example [here](https://geneontology.org/docs/ribbon.html) in the **Generic Ribbon, other usages and data model** section but when doing so I see that your component makes an API request to 
```API query is https://api.geneontology.org/api/ontology/ribbon/?subset=goslim_agr&subject=subject1&subject=subject2&subject=subject3&subject=subject4&subject=subject5&subject=subject6```,
you can check the attached sample that am using
[sample.json](https://github.com/geneontology/helpdesk/files/14407924/sample.json).
How to show case data without the need to that API call.
any information provided with be appreciated.
Thank you

_Originally posted by @AyoubMaatouch in https://github.com/geneontology/helpdesk/discussions/477_

**Comment by kltm** [comment]
Closing this in preference to earlier https://github.com/geneontology/helpdesk/discussions/477
