### ISSUE TITLE
Querying go-plus.owl with SPARQL in Protege to retrieve GO-UBERON annotations

### ISSUE THREAD

**Issue by NatalieThurlby** [geneontology/helpdesk#48]
Hello,

This is partially related to my last issue (https://github.com/geneontology/helpdesk/issues/40).

I am trying to do some research about the tissue-specific gene expression (related to genes being more highly expressed in tissues which they effect) and I'm trying to use GO-UBERON (and GO-CL) annotations as part of this work.

For example, I would like to have a list of all GO terms which occur in UBERON tissues (including inferences). I would like not only the GO terms but also which (most specific, i.e. no subclasses of each other) UBERON tissues they occur in. 

At the moment, I am able to make some useful DL queries in Protege over the go-plus.owl ontology, but I am unable to export what I need (as I need part of the explanation). 

I have heard that a SPARQL query may be more suitable for this task, but while I have been able to write SPARQL queries in Protege for simple ontologies, and I have been able to write simple SPARQL queries that work on the ontobee SPARQL website (http://www.ontobee.org/sparql) over the GO ontology, I have been unable to write any query that works over GO in Protege. 

I would appreciate any advice on how to move forwards with this.

Many thanks,

Natalie

**Comment by kltm** [comment]
Tagging @cmungall .

**Comment by cmungall** [comment]
You can try

```
prefix obo: <http://purl.obolibrary.org/obo/> 
prefix owl: <http://www.w3.org/2002/07/owl#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT ?x ?p ?y
WHERE {
  ?x rdfs:subClassOf [
    a owl:Restriction ;
    owl:onProperty ?p ;
    owl:someValuesFrom ?y ] .
  FILTER(regex(str(?x), "^http://purl.obolibrary.org/obo/GO_"))
  FILTER(regex(str(?y), "^http://purl.obolibrary.org/obo/UBERON_"))
}
```

on http://rdf.geneontology.org/blazegraph

This will give all class axioms linking GO to UBERON.
