### ISSUE TITLE
GO term is a URL

### ISSUE THREAD

**Issue by mirandajarnot** [geneontology/helpdesk#483]
##Describe the issue/bug
We are loading the 3/28/2024 version of GO into the UMLS and found a GO term name that is a URL. 

## Expected behavior
Did not expect to find this, should be a term name.

## To Reproduce
This should be simple to find in the data -- the term name/URL is  "https://github.com/geneontology/go-ontology/issues/24127" and the GO code is GO:0085044. 

## Additional context

Add any other context about the issue that you feel may be important. E.g. browser version, time of day.

**Comment by pgaudet** [comment]
Thanks for reporting this! I have fixed this; it should be corrected in the next release. 

Just a precision: I see the URL as a term synonym, not a term name. 

Best wishes, Pascale
