### ISSUE TITLE
Cycle in the go-basic.obo graph

### ISSUE THREAD

**Issue by GuyTeichman** [geneontology/helpdesk#489]
## Describe the issue/bug

In the most recent version of the basic Gene Ontology graph (go-basic.obo, release 2024-06-10), it appears that a cycle has been introduced into the graph. 
In particular, the GO term GO:0045281 (succinate dehydrogenase complex) is pointing at GO:0045257 (succinate dehydrogenase complex (ubiquinone)
) ("part_of" relationship), while GO:0045257 is pointing back at GO:0045281 ("is_a" relationship). 
I believe that the "part_of" relationship was supposed to be deleted in one of the recent updates to the ontology, but was not deleted from the go-basic.obo file. 

## Expected behavior
The go-basic.obo graph should be guaranteed to have no cycles in it - any programs that attempt to propagate annotations using this ontology graph would run into infinite loops. 

## To Reproduce
Access the ontology through the permenant link:
https://current.geneontology.org/ontology/go-basic.obo
format-version: 1.2
data-version: releases/2024-06-10

## Screenshots

```
[Term]
id: GO:0045257
name: succinate dehydrogenase complex (ubiquinone)
namespace: cellular_component
def: "The enzyme that catalyzes the oxidation of succinate and ubiquinone to fumarate and ubiquinol; involved in aerobic respiration, repressed in anaerobic respiration." [GOC:kd, ISBN:0198547684]
is_a: GO:0045239 ! tricarboxylic acid cycle heteromeric enzyme complex
is_a: GO:0045281 ! succinate dehydrogenase complex

```

```
[Term]
id: GO:0045281
name: succinate dehydrogenase complex
namespace: cellular_component
def: "A multimeric complex which consists of flavoprotein (subunit A ; InterPro:IPR003952), iron-sulfur protein (subunit B) and membrane-bound cytochrome b560 (subunit C; InterPro:IPR000701). In some Archaea, the membrane-bound subunits (C or C and D) do not necessarily contain heme. Membrane-bound subunits can bind or react with quinones." [GOC:kd, InterPro:IPR000701]
is_a: GO:0098803 ! respiratory chain complex
is_a: GO:1990204 ! oxidoreductase complex
relationship: part_of GO:0045257 ! succinate dehydrogenase complex (ubiquinone)
relationship: part_of GO:0045273 ! respiratory chain complex II
```

**Comment by cmungall** [comment]
Also reported here:

- https://github.com/geneontology/go-ontology/issues/28164

**Comment by davidbio** [comment]
Just stumbled over the same problem.

**Comment by pgaudet** [comment]
Sorry about that! We are making a new release that should fix this, we'll post this here when it's finished.

**Comment by kltm** [comment]
@pgaudet Has this been cleared?

**Comment by pgaudet** [comment]
Both terms reported in the issue (https://github.com/geneontology/helpdesk/issues/489#issue-2358104177) have been obsoleted. Alex had reported a few more - @alexsign do you still get errors regarding this?

**Comment by davidbio** [comment]
So this has been "fixed" by obsoleting the terms?
Can we consider the latest version as "correct"?

**Comment by pgaudet** [comment]
@balhoff Do you have a way of testing this? 
@davidbio Do you still see that error?

**Comment by balhoff** [comment]
@pgaudet we have a check now that should fail the pipeline if this happens again.

**Comment by pgaudet** [comment]
Awesome!

**Comment by davidbio** [comment]
@pgaudet 
Honestly, I was waiting for this to be marked as RESOLVED before trying again.
