### ISSUE TITLE
GO snapshot is not updating

### ISSUE THREAD

**Issue by ValWood** [geneontology/helpdesk#493]
## Describe the issue/bug

Snapshot has not been updated since 17th June.
[http://snapshot.geneontology.org/summary.txt]

We use this for PomBase, and Canto and assume it is the most up-to-date. However QuickGO IS updating, so there must be another source that is ahead of the snapshot?

cc @kimrutherford

Thanks!

Val

## To Reproduce

Please include any information you can about: what, where, when, and why. Please include any URLs involved in the issue.

## Additional context

Add any other context about the issue that you feel may be important. E.g. browser version, time of day.

**Comment by kltm** [comment]
@ValWood While the `snapshot`s are attempted a few times a week, if there are issues (as are currently going on now) there may be a delay of a week or a bit between snapshots. There is no public sources ahead of these snapshots.

**Comment by ValWood** [comment]
but I am seeing the updates in QuickGO?

**Comment by kltm** [comment]
I think you might want to ask Alex what is changing on that end; there are other possible sources and some things may be not completed synced on the same schedules.

**Comment by suzialeksander** [comment]
noting that Snapshot was successful on 2024-07-02

**Comment by pgaudet** [comment]
Also, snapshots are now ran weekly. 

Alex loads the 'rolling ontology build' ; looks like there are frequent updates in QuickGO as well: 

<img width="420" alt="image" src="https://github.com/geneontology/helpdesk/assets/4782928/83ead539-98be-49b4-85e1-8f7e7bd57743">

I'll close this, I dont think there is any action needed.
