### ISSUE TITLE
Different annotation date for the same annotation

### ISSUE THREAD

**Issue by anphan0828** [geneontology/helpdesk#497]
**Please describe your question, idea, or concern.**
Dear GO team,

I have a question about the 'Date' field in GAF files. While looking through human GAF files (goa_human.gaf downloaded from GO Data Archive, https://release.geneontology.org/index.html) of June 2024, Dec 2022 and Oct 2021 releases, I realized that some protein binding (GO:0005515) annotations of some proteins are similar (same ProteinID, same GO term, same evidence, same PMID reference, same binding partner) but the 'Date' field is updated with every version. For example, 

(entry in most recent version 2024-06-17 shows annotation date of 20240406)
`UniProtKB       P61073  CXCR4   enables GO:0005515      PMID:24094005   IPI     UniProtKB:Q04900        F       C-X-C chemokine receptor type 4       CXCR4   protein taxon:9606      20240406        IntAct`
(entry in 2022-12-04 file shows annotation date of 20221112) 
`UniProtKB	P61073	CXCR4	enables	GO:0005515	PMID:24094005	IPI	UniProtKB:Q04900	F	C-X-C chemokine receptor type 4	CXCR4	protein	taxon:9606	20221112	IntAct`
(entry in 2021-10-26 file shows annotation date of 20210612)
`UniProtKB	P61073	CXCR4	enables	GO:0005515	PMID:24094005	IPI	UniProtKB:Q04900	F	C-X-C chemokine receptor type 4	CXCR4	protein	taxon:9606	20210612	IntAct`

I wonder why is the annotation date was updated in the new version if every other field is the same. Is this the case with only GO:0005515 protein binding annotations or can happen to other GO terms as well? Maybe there is a GO rule about updating the creation date that I did not know of. Not every GO creation date is updated with every new version. 

I appreciate your help. Thank you in advance.

**Comment by suzialeksander** [comment]
@anphan0828 Thanks for this question. There's no automatic check/change at GO that would update the date of these manual annotations, so I would read these as curators at IntAct are reviewing/confirming existing annotations as part of their workflow.

If these were computational annotations, the changing date would indicate the pipeline to generate those annotations was rerun.

@sandraorchard can you confirm?

**Comment by anphan0828** [comment]
Thank you, I took a deeper dive into this and found that annotations sourced from IntAct indeed all have the same annotation date (closest date to the GO version date) and the annotation dates get updated with every GO version. Furthermore, IntAct only annotates GO:0005515 and GO:0042802 (at least in Human) so I can filter these out quite easily if needed.

Thanks again for your help!
