### ISSUE TITLE
Not receiving daily 'summary for tickets' emails

### ISSUE THREAD

**Issue by sjm41** [geneontology/helpdesk#498]
Hi. About 3 weeks ago, I stopped receiving the daily 'summary for tickets' emails. I did have an 'out of office' reply disaster around that time, so maybe my email address got removed/blocked from the mailing list....

(Seth has confirmed that the emails are still going out, so this issue does seem specific to me.)

Steven

**Comment by kltm** [comment]
@suzialeksander Do you remember what the remediations were?

**Comment by suzialeksander** [comment]
Hi @sjm41, yes we had to disable delivery to your address. I just changed it back so if you don't get tomorrow's email just let me know!

**Comment by sjm41** [comment]
Thanks @suzialeksander !  All good now. Apologies for the hassle.
