### ISSUE TITLE
[[GO_REF:0000051] obsolete

### ISSUE THREAD

**Issue by ValWood** [geneontology/helpdesk#499]
## Describe the issue/bug

[[GO_REF:0000051] S. pombe keyword mapping](https://geneontology.org/GO_REF/0000051)

can be obsoleted, hasn't been used for over a decade, I think....

**Comment by pgaudet** [comment]
It's still around in AmiGO https://amigo.geneontology.org/amigo/gene_product/PomBase:SPAC4D7.04c

Is this not in your source file?

**Comment by ValWood** [comment]
Right I thought "GO_REF:0000051" was just the standard  GO Ref for NAS code.

All our NAS are  non traceable author statements .... reducing, but based on annotations, we expect to be able to ISO/IBA, too. 
What do groups usually  use for NAS? I'm happy to continue using this (most should disappear over the next 12 months or so) , but it isn't a keyword mapping.

**Comment by pgaudet** [comment]
I thought for NAS you needed to cite the paper/abstract that made the statement. 

https://wiki.geneontology.org/Non-traceable_Author_Statement_(NAS)

**Comment by ValWood** [comment]
I think it fits this (at least this is vague enough to encompass)

The NAS code is also used for making annotations from database entries when a curator reviews the annotations that result. Typically such annotations will refer to an unpublished reference describing what was done, either a reference with a GO_REF id or an internal reference from the specific annotating database.

 which is probably why I have a reference. It's just that the description of the reference isn't great for  to describe how it is used.
I'll  close this.
