### ISSUE TITLE
Which Gene ontology database tables contains NCBI sequence accession numbers or Entrez id 

### ISSUE THREAD

**Issue by mohitjha** [geneontology/helpdesk#5]
I am making a pipeline for GO analysis (starting from sequence). I dont want to use blast2GO. I have Gene ontology local database and i want to map blast output to gene ontology categories but i am not able to find which Gene ontology database tables contains NCBI sequence accession numbers or Entrez id so that to map the blast output to GO categories

**Comment by kltm** [comment]
@mohitjha 
You might want to take a look here:
 http://geneontology.org/page/lead-database-guide#dbtypes
and then check out the database archive at:
 http://archive.geneontology.org/
The schema, including which tables contain sequence information, can be found here:
 http://geneontology.org/page/lead-database-schema

The mysql database is fast approaching "legacy" status, in favor of downloads and a graph store. We are currently discussing the best way to make sequence information available as well.

**Comment by mohitjha** [comment]
all the table contains "id" field, which tables "id" is the ncbi sequence accession number?

**Comment by kltm** [comment]
I believe for what you are looking for, you probably want to join against the seq_dbxref table (http://geneontology.org/page/lead-database-schema#go-sequence.table.seq-dbxref). The following example may be of some use:
http://wiki.geneontology.org/index.php/Example_LEAD_Queries#Searching_by_sequence_dbxref
