### ISSUE TITLE
GO powerpoint presentations

### ISSUE THREAD

**Issue by iamdna** [geneontology/helpdesk#50]
Hello there,

A collection of old GO ppts were available on the wiki or the website. I can't locate them. Can you please point me to those?

Thanks,
Rama

**Comment by kltm** [comment]
It's possible that there are actually still in the old SVN. Anonymous SVN access information can be found here:
http://geneontology.org/page/svn-help

From there, I believe what you're looking for is in: `teaching_resources`.

**Comment by iamdna** [comment]
Thanks Seth. Hope all is well at Berkeley. I moved to Genentech recently (from Personalis).

Rama

**Comment by kltm** [comment]
Hey Rama!
All is good here; I hope your new digs are treating you well!
