### ISSUE TITLE
Daily snapshot not updated since 4th AUgust

### ISSUE THREAD

**Issue by ValWood** [geneontology/helpdesk#500]
see
https://snapshot.geneontology.org/metadata/date.txt

**Comment by kltm** [comment]
@ValWood We have passed the issues we were having and a new `snapshot` is out.

**Comment by pgaudet** [comment]
Hurray! 

<img width="769" alt="image" src="https://github.com/user-attachments/assets/14b80d07-67bd-4e38-b8a3-5c4842e25f4e">

**Comment by ValWood** [comment]
Excellent!

I guess an offical release will be soon?

**Comment by pgaudet** [comment]
This is the hope!!
