### ISSUE TITLE
GO Github account, but cannot login to Noctua?

### ISSUE THREAD

**Issue by Pauldenny** [geneontology/helpdesk#507]
## Describe the issue/bug

I have a GO Github account, but cannot login to Noctua using my Github credentials.

**Comment by Pauldenny** [comment]
@vanaukenk

**Comment by vanaukenk** [comment]
@Pauldenny - I've just updated your metadata in the users.yaml file and refreshed the Noctua users list.
Please try to login again and let me know how it goes.
Thanks.

**Comment by Pauldenny** [comment]
Hi Kimberley,
afraid still locked out

**Comment by kltm** [comment]
@vanaukenk Due to the lag that's there sometimes, you might want to do the "user add" cycle again.

**Comment by kltm** [comment]
@vanaukenk More than that though, @Pauldenny does not have an associated GitHub account in our metadata, which is needed.

**Comment by vanaukenk** [comment]
Okay, all should be right now.

@Pauldenny - please try again and let us know how it goes.  Thanks.

**Comment by Pauldenny** [comment]
Hi Kimberley @vanaukenk still not working... sorry it's becoming a pain!

**Comment by vanaukenk** [comment]
Hi Paul @Pauldenny  I'm very sorry you're still having trouble.

I've done another user refresh this morning, about an hour ago.

Can you please try once more to login?  

If you're still having trouble @kltm and I will have to look at this together.

**Comment by Pauldenny** [comment]
I'm in - thanks very much, @vanaukenk @kltm

**Comment by vanaukenk** [comment]
Thanks for your patience, @Pauldenny 
I'm glad to hear this is now working for you!
