### ISSUE TITLE
About statistics of available lncRNA annotations in current GOA

### ISSUE THREAD

**Issue by YangDing-github** [geneontology/helpdesk#51]
Hi,

Currently we need some statistics regarding the lncRNA annotations available through GO; specifically, we'd like to obtain a list of lncRNAs annotated on GO (from all possible species), along with their annotations.

I tried to search for some lncRNA (e.g., Xist, Hotair) and found some hits, but we don't know how to find all of them. I also tried to download the entire GOA dataset and find out whether I could extract all lncRNA records; while I saw a number of lncRNAs have in their full names "non protein-coding" there are some lncRNAs that cannot be detected as lncRNAs in this way (e.g. the  [Ftx transcript](http://amigo.geneontology.org/amigo/gene_product/RGD:1564124) from Rat.)

Could you please tell us how we could obtain such a list?

Thanks

**Comment by kltm** [comment]
@ukemi Would you perhaps have any ideas for this?

**Comment by ukemi** [comment]
I don't know how to do this for all species. You can search for mouse lncRNA-encoding genes at Mouse Genome Informatics using the 'Genes and Markers Query Form'. Retrieving those and then doing a batch query can at least provide a start.

**Comment by YangDing-github** [comment]
@ukemi Thanks for your suggestion. We will start from species popular in lncRNA studies and see what we can get.
