### ISSUE TITLE
searching AMIGO2 database with a list of UniProt identifiers?

### ISSUE THREAD

**Issue by Pauldenny** [geneontology/helpdesk#512]
**Please describe your question, idea, or concern.**
Would like to search dbase with a list of UniProt identifiers, but cannot see a way in the standard AMIGO2 website interface.
Is there any way to do this using an API, or similar query?

**Comment by pgaudet** [comment]
Hi @Pauldenny 
Try this link: 
https://amigo.geneontology.org/amigo/bulk_search/ontology

Thanks, Pascale

**Comment by Pauldenny** [comment]
Hi @pgaudet 
thanks for help, but either I'm doing something wrong or this is the wrong search page?
Before trying a long list of identifiers, I tried Q5S007 - a human Swiss-Prot entry, but got zero results
![image](https://github.com/user-attachments/assets/0f4db086-b514-4991-aeba-c12c8e230fc6)
Ideas?

**Comment by pgaudet** [comment]
Sorry - that seems to only work for GO term. 

@kltm Are there other tools to access annotations in bulk?

**Comment by kltm** [comment]
@Pauldenny @pgaudet 
I would note that the bulk search tool is still in "beta" and is not part of our official suite of tools at this point. As our API doesn't have much in the way of association access, the best supported way to approach this would be to download and parse the GAFs.

For an "unsupported" method, the correct bulk search would be https://amigo.geneontology.org/amigo/bulk_search/annotation . Remember: internal identifiers are not allowed, they _must_ have the namespace attached. So: `UniProtKB:Q5S007`.

**Comment by pgaudet** [comment]
Thanks for pointing out to the correct link @kltm ! 

@Pauldenny Does that work for you? 

Thanks, Pascale

**Comment by Pauldenny** [comment]
Yes, thanks, @kltm @pgaudet
