### ISSUE TITLE
TermGenie down?

### ISSUE THREAD

**Issue by janelomax** [geneontology/helpdesk#52]
Hi - I'm getting an error for:

go.termgenie.org

HTTP ERROR: 503

Problem accessing /go-termgenie/. Reason:

    Service Unavailable

**Comment by kltm** [comment]
@janelomax 

I'm tagging on @cmungall , but I believe we are no longer supporting TermGenie; I believe we have entirely switched over to the ROBOT suite of tools.

**Comment by cmungall** [comment]
https://github.com/geneontology/go-ontology/issues/13692

**Comment by janelomax** [comment]
Good to know! Link on http://geneontology.org/contributing-go-term needs fixing. Well, the whole page needs fixing really.
