### ISSUE TITLE
Different annotations in Gene Ontology

### ISSUE THREAD

**Issue by Rfriedmancolumbia** [geneontology/helpdesk#53]
Dear Gene Ontology Help Desk,

	I am not clear on the difference betweenthe links entitled

 Link to all direct and indirect annotations to canonical Wnt signaling pathway involved in osteoblast differentiation.

Linkto all genes and gene products associated to canonical Wnt signaling pathway involved in osteoblast differentiation. 
Should they not be identical and symmetrical for any GO TERM?

In particular, I am currently looking at

GO:0044339 canonical Wnt signaling pathway involved in osteoblast differentiation  for mouse.

For

Link to all direct and indirect annotations to canonical Wnt signaling pathway involved in osteoblast differentiation.

I get 
Tmem64
Tnn
Fzd1
Wnt3

It is symmetrical as expected.

For linkto all genes and gene products associated to canonical Wnt signaling pathway involved in osteoblast differentiation.

I also get
Tmem64
Tnn
Fzd1
Wnt3

as I would expect.

What is the differnece between the 2 listings.
Are they ever different?

I am further puzzled on the differnece between these entires and

Text search document selection 

256     Genes and gene products associated with GO terms.
487     Associations between GO terms and genes or gene products. 

What is the differecne between the text search documents and the listing
above?

Also should not the genes in two text terms be identical to one another?
why are they 256 for the first and 487 for the second?

For just mouse, under 
256     Genes and gene products associated with GO terms.

I get 17 terms.
Why are these differnet than the 4 terms in For linkto all genes and gene products associated to canonical Wnt signaling pathway involved in osteoblast differentiation.

For a Associations between GO terms and genes or gene products. I get 44 genes
for just mouse. Shouldn;t thes be the same 17 genes. as above?

Thanks and best wishes,
Rich
Richard A. Friedman, PhD
Associate Research Scientist,
Biomedical Informatics Shared Resource
Herbert Irving Comprehensive Cancer Center (HICCC)
Lecturer,
Department of Biomedical Informatics (DBMI)
Room 825
Irving Cancer Research Center
Columbia University Herbert and Florence Irving Medical Center
1130 St. Nicholas Ave
New York, NY 10032
(212)851-4765 (voice)
raf4@cumc.columbia.edu

http://www.columbia.edu/~raf4/index.html

“Will there still be "Classics Illustrated” by the time I have children? I cannot
imagine raising kids without "Classics Illustrated” .” -Rose Friedman, age 20

**Comment by kltm** [comment]
@Rfriedmancolumbia 

`Link to all direct and indirect annotations to canonical Wnt signaling pathway involved in osteoblast differentiation.`
will take you to a page that allows you to search through `annotation` documents. An annotation is a set of GO term, gene product, evidence, and metadata. There are many more annotations than gene products, as there may be more than one annotation per gene product (e.g. a gene product is annotated to a molecular function *and* a biological process).

`Link to all genes and gene products associated to canonical Wnt signaling pathway involved in osteoblast differentiation.`
will take you to a page that allows you to search through `gene product` documents. A gene product document is oriented around all the annotation a term associated with a single gene product.

`Text search document selection` is a search through all the different document classes (`annotation`, `gene product`, and `ontology class`) for the particular string you're using over all indexed text fields; the returned count is the number of matching documents.

**Comment by Rfriedmancolumbia** [comment]
Dear Kltm,


Thank you for your very clear explanation.


Best wishes,

Rich

________________________________
