### ISSUE TITLE
ontologies not loading from purls: something wrong with snapshot.geneontology.org?

### ISSUE THREAD

**Issue by tberardini** [geneontology/helpdesk#54]
From here:

http://geneontology.org/page/download-ontology
Example:
http://purl.obolibrary.org/obo/go/go-basic.obo
leads to
http://snapshot.geneontology.org/ontology/go-basic.obo
leads to
XML Parsing Error: syntax error
Location: http://snapshot.geneontology.org/ontology/go-basic.obo
Line Number 1, Column 1:format-version: 1.2
^

Trying another avenue:
http://snapshot.geneontology.org/ontology/extensions/go-plus.owl
results in 

This XML file does not appear to have any style information associated with it. The document tree is shown below.
      −<rdf:RDF xml:base="http://purl.obolibrary.org/obo/go/extensions/go-plus.owl">−<owl:Ontology rdf:about="http://purl.obolibrary.org/obo/go/extensions/go-plus.owl"><owl:versionIRI rdf:resource="http://purl.obolibrary.org/obo/go/releases/2017-09-18/extensions/go-plus.owl"/>
...

**Comment by kltm** [comment]
@tberardini As none of those are actually XML files, they will naturally not parse. I suspect what you're seeing here is just an expression of https://github.com/geneontology/pipeline/issues/8 .

**Comment by kltm** [comment]
Yes, that scared the Cheerios out of me too when I first saw it. More smoke than fire though, although suuuuper annoying.
