### ISSUE TITLE
GO evidence codes - download file?

### ISSUE THREAD

**Issue by julie-sullivan** [geneontology/helpdesk#55]
Hello wonderful GO people! 

http://geneontology.org/page/guide-go-evidence-codes

I would like a flat file with the GO evidence codes and their associated names. (Descriptions too would be great.) 

I can make this file myself of course but would be safer if used your up-to-date one. Does that exist? Sorry if this is obvious, I did look!

Thank you!!

**Comment by kltm** [comment]
@julie-sullivan 

Currently, we do not have a single page discussion of the evidence codes, just the page-wise documentation you found above.

Technically, under the hood, the GO uses ECO (http://evidenceontology.org/) , the three letter evidence codes are part of an historical development and treated as synonyms to terms within that ontology. @cmungall may have the best reference as to how we connect that information to the ECO.

If you have a specific use case, we may have other tools available for what you're trying to accomplish.

**Comment by julie-sullivan** [comment]
Thanks!!! That answers my question. :)
