### ISSUE TITLE
Cannot download x-metazoan-anatomy.owl

### ISSUE THREAD

**Issue by drseb** [geneontology/helpdesk#56]
Trying to load http://purl.obolibrary.org/obo/go/extensions/x-metazoan-anatomy.owl fails at the moment. It redirects to http://snapshot.geneontology.org/ontology/extensions/x-metazoan-anatomy.owl. 

Has this file been removed?

ping @cmungall

**Comment by cmungall** [comment]
These are all now rolled into go-plus. We're open to ideas about how to distribute the different slices and dices of this...

(I am in off-tracker conversation with seb so I will close this)
