### ISSUE TITLE
select species

### ISSUE THREAD

**Issue by ggiaever** [geneontology/helpdesk#57]
how can you search/browse without having to reselect an organism of choice each time a new page is loaded

**Comment by kltm** [comment]
@ggiaever I suspect that the issue that incorporates this is:

https://github.com/geneontology/amigo/issues/50

Essentially, AmiGO has no memory of the current search*, so navigating away from a page or using the back button will lose state.

A workaround for some of this is clicking the [bookmark] button over the results controls and clicking on the "this search" link--that will lock in your current search and selections to the current URL.
