### ISSUE TITLE
Ontology Issues

### ISSUE THREAD

**Issue by nstickney** [geneontology/helpdesk#58]
The latest go.obo file available from `purl` today has some errors. If this is the wrong place to post this, please let me know!
- There is overlap between two namespaces:
    - GO:0038071 (`molecular_function`) `part_of` GO:0071507 (`biological_process`)
- There is cycle in the `molecular_function` namespace:
    - **GO:0042623** `is_a` GO:0016887 `part_of` GO:0061860 `is_a` GO:0003677 `part_of` GO:0015616 `is_a` GO:0008094 `is_a` **GO:0042623**

**Comment by kltm** [comment]
@nstickney While this may not be a final home, this is a fine place to start.
@cmungall Would you have any ideas about this?

**Comment by kltm** [comment]
This issue was moved to geneontology/go-ontology#14508
