### ISSUE TITLE
EC2GO

### ISSUE THREAD

**Issue by rcaspi** [geneontology/helpdesk#6]
Hi,
I am a member of the enzyme commission, and I would like to find out more about who is doing the EC2GO mapping, how often the mapping file is updated, where do you get the latest EC numbers etc. Could you please put me in touch with the responsible person?

Thanks,
Ron Caspi

**Comment by kltm** [comment]
Maybe @cmungall @monicacecilia would have some idea about the best information here?

**Comment by cmungall** [comment]
@rcaspi, thanks for getting in touch. This is great timing as we are currently working on improving our EC2GO mappings. I will place this on the agenda for the ontology developers call tomorrow and someone will get back to you next week.

cc @ukemi @hdrabkin

**Comment by rcaspi** [comment]
Hi Chris,
      
      Thanks, that sounds great.
      
      I will be giving a short talk about EC curation at the BioCurator
      conference on Monday. Any chance you could give me a little more
      info about this mapping project that I could potentially mention
      in that talk?
      
      Ron
      
      On 3/23/2017 1:14 PM, Chris Mungall wrote:
    
    
      
      @rcaspi, thanks for getting in touch.
        This is great timing as we are currently working on improving
        our EC2GO mappings. I will place this on the agenda for the
        ontology developers call tomorrow and someone will get back to
        you next week.
      cc @ukemi @hdrabkin
      —
        You are receiving this because you were mentioned.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
          
          
        
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/geneontology/helpdesk","title":"geneontology/helpdesk","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/geneontology/helpdesk"}},"updates":{"snippets":[{"icon":"PERSON","message":"@cmungall in #6: @rcaspi, thanks for getting in touch. This is great timing as we are currently working on improving our EC2GO mappings. I will place this on the agenda for the ontology developers call tomorrow and someone will get back to you next week.\r\n\r\ncc @ukemi @hdrabkin"}],"action":{"name":"View Issue","url":"https://github.com/geneontology/helpdesk/issues/6#issuecomment-288846486"}}}

**Comment by cmungall** [comment]
Some general ideas:

 - we had a lot of redundant mappings, with an EC mapped to a broad GO term and a narrower one. We're looking to get rid of these but some issues came up
 - we're attempting to be more consistent about directionality of reaction in GO
 - historically we have mapped to EC after the fact, but @hdrabkin is working on a project where is prospectively adding ECs as he adds new batches of terms (this is for plant metacyc), cc @tberardini

**Comment by hdrabkin** [comment]
While adding terms, I check if EC is used as an xref already, and avoid using ".-" ec ids; 
The xrefs are used to generate the mapping file, and if a ".-" is used, then all the members of the ec class are mapped to the GO term, which is not the intended outcome.

**Comment by hdrabkin** [comment]
I should add that the mapping file (EC2GO) is refreshed monthly. Current version:  Generated on 2017-03-27T13:28Z from the ontology 'go' with data version: 'releases/2017-03-27'

**Comment by kltm** [comment]
This item is now two weeks open without action in the helpdesk. Is there a more permanent tracker item that this should be pointed at or moved to, or is this item closable?

**Comment by hdrabkin** [comment]
I spoke with Ron briefly. This is a large project; ; no simple fixes here.

**Comment by rcaspi** [comment]
My group will assemble a list of current EC entries that are missing from the EC2GO file, and provide it to Harold. We will take it from there.

**Comment by kltm** [comment]
Okay great. If there is a ticket to encapsulate this in one of the trackers, feel free to add it here. Otherwise, I'll close this out as a helpdesk ticket.

**Comment by hdrabkin** [comment]
Cross reference geneontology/go-ontology/#13432

**Comment by kltm** [comment]
geneontology/go-ontology#13432

**Comment by hdrabkin** [comment]
ah!
