### ISSUE TITLE
Term Genie is down?

### ISSUE THREAD

**Issue by alanruttenberg** [geneontology/helpdesk#60]
Links such as the one at 

http://geneontology.org/page/submitting-term-suggestions-go

In this case to the TermGenie Documentation Page, are broken, yielding:

    HTTP ERROR: 503
    Problem accessing /go-termgenie/help/index.html. Reason:
    Service Unavailable 
    Powered by Jetty://

**Comment by kltm** [comment]
@alanruttenberg 
I've updated the documentation on that page to reflect this: TermGenie has been EOLed (earlier this year) in favor of ROBOT (https://github.com/ontodev/robot).
For more information on the transition, you may wish to contact @cmungall .
