### ISSUE TITLE
different GO results with Gene Symbols and ENSEMBL input

### ISSUE THREAD

**Issue by jjobee** [geneontology/helpdesk#61]
I noticed that when I input the gene symbols or the ENSEMBL ids for the same list of genes, I get slightly different lists of GO terms.  I used the Term Enrichment Service on the AmiGO2 site, searching biological processes (mus musculus).  I would have expected the results to be exactly the same.  What is causing this and what should I do differently?

**Comment by jjobee** [comment]
I just noticed that the number of unmapped reads differs as well.

**Comment by kltm** [comment]
As this is to do with the PANTHER software suite, I'll ping @mugitty and @huaiyumi .

**Comment by jjobee** [comment]
Any thoughts?

**Comment by huaiyumi** [comment]
PANTHER uses the Reference Proteome data, which uses UniProt ID as the primary identifier, in the annotation gene set for the enrichment test. Gene symbol and ESEMBL IDs are converted to UniProt IDs using the idmapping file provided by Reference Proteome datasets. The differences you observed must result from their mapping.
