### ISSUE TITLE
How do I find version numbers for GO releases?

### ISSUE THREAD

**Issue by SocialAmbulator** [geneontology/helpdesk#62]
I am writing a paper citing GO as a source of information for a database which I downloaded. I was unable to see any version numbers on the download or anywhere else on the website so I didn't include it in the paper. Now one of the referees has come back at me on this. How do I find the info?

**Comment by kltm** [comment]
@SocialAmbulator 
If this was an actual MySQL database download that you used, you can find the information in the tabe `instance_data`.
For more information, please see:
http://geneontology.org/page/go-citation-policy#GO_Data

**Comment by SocialAmbulator** [comment]
Thanks @ktm I should have said this was the go-basic.obo.txt file that I downloaded. On inspection the first two lines are:
format-version: 1.2
data-version: releases/2017-06-04
I assume the format-version had to do with the file format, so I presume I just cite the date.

David

**Comment by kltm** [comment]
@SocialAmbulator 
Yes, that, plus the filename (`go-basic.obo`), should give somebody enough information to recreate the environment in their pipeline.

**Comment by SocialAmbulator** [comment]
Thanks
