### ISSUE TITLE
Trying to access to the GO database mirror at the EBI  - ERROR 2003 (HY000): Can't connect to MySQL server on 'mysql.ebi.ac.uk' (111)

### ISSUE THREAD

**Issue by HHugues** [geneontology/helpdesk#64]
Hi,

That's three days now that I can't access the GO database mirror at the EBI by using the following bash command line : 

`$ mysql -hmysql.ebi.ac.uk -ugo_select -pamigo -P4085 go_latest`
`ERROR 2003 (HY000): Can't connect to MySQL server on 'mysql.ebi.ac.uk' (111)`

(I tried it  on CentOS release 6.9  and Ubuntu 16-09)

Do you have information to share ? :)

Kind regards,
Hugues

**Comment by kltm** [comment]
@HHugues 
Unfortunately, we are in a bit of a transition period right now. There will be no further builds of the full database and as we wind down the EBI site may be suspending support for the full database mirror.
For more details on the transition, please see the discussion on this issue: #4
For querying, we are just completing our pipeline for the new SPARQL endpoint, and now have beta snapshots available at http://rdf.geneontology.org .
We will be updating the community as our new pipeline products come online.

Pinging @tonysawfordebi in the case this is not correct.

**Comment by tonysawfordebi** [comment]
That's correct.
We have switched off the mirror, but we can revive it if necessary. I wouldn't recommend that, however, as the data in it is now several months out of date.

**Comment by HHugues** [comment]
Thank you both for the quick answer !

@ktlm 
I will look into that.

@tonysawfordebi 
It's not necessary if this type of procedure is out of date .

Best wishes,
Hugues
