### ISSUE TITLE
GO Enrichment tool is timing out

### ISSUE THREAD

**Issue by kwatts59** [geneontology/helpdesk#65]
To GO Consortium,
As of today Oct 12, 2017, the GO Enrichment tool is timing out.
Even when I enter a single gene, the tool times out.
http://www.geneontology.org/page/go-enrichment-analysis
Ken

**Comment by kltm** [comment]
@kwatts59 
According to https://status.geneontology.org/ , we have had some outages in the last 24 hours. That said, it looks to be currently functioning. If it still does not work for you, we can dig further into the situation.
