### ISSUE TITLE
Ontology for Biomedical Investigations - OBI

### ISSUE THREAD

**Issue by UndressK** [geneontology/helpdesk#66]
Hi there!
It is great what you have done to easily download ontologies from the AmiGO ontology search. I've downloaded some but I was wondering whether you were planning to incorporate also the Ontology for Biomedical Investigations (OBI) or the Cell Line Ontology (CLO) in the custom download.
Thanks

**Comment by cmungall** [comment]
We don't have any plans to do this in the main public AmiGO - we only provide access to GO or to portions of other ontologies that are used to enhance GO annotations. For example, the cell type ontology (CL) is used to provide locational context, so it's possible to query for some cell types.

It is possible to run your own instance of amigo with whichever ontologies you like. You can open a request here: https://github.com/geneontology/amigo/issues if you would like assistance (we can only offer limited support on this, you would need some knowledge of installing things on unix-like systems).

For now, I would use an OBO Foundry sanctioned browser for your ontology. You can find links on individual OBO pages, e.g.
http://obofoundry.org/ontology/cl.html

**Comment by UndressK** [comment]
Hi Chris,

thanks for your message. I would ask for some assitance then.
If I got it right, the other ontologies that are not GO and you show in
AmiGO are not complete and I should download them directly from the OBO
foundry?

Thank you for your help

Andrés

**Comment by cmungall** [comment]
This is correct
