### ISSUE TITLE
gene ontology ids date of submission

### ISSUE THREAD

**Issue by scfbio** [geneontology/helpdesk#67]
I want to get the GO ids withe their date of submission.

**Comment by kltm** [comment]
@scfbio 
@cmungall may have other ideas, but I suspect what you want may be minable from the VCSs used for the ontology. That would be (more recently) geneontology/go-ontology and the legacy SNV http://geneontology.org/page/svn-help

**Comment by cmungall** [comment]
Its the created by field. I don't think it's loaded into solr.  Can be
parsed from ontology file or queued by sparql

**Comment by kltm** [comment]
@cmungall I read that as a creation date, rather than creator.
