### ISSUE TITLE
Permission for Noctua

### ISSUE THREAD

**Issue by WBjae** [geneontology/helpdesk#68]
Hello, I want to get a permission for the Noctua (Go-CAM).
I filled out and submitted the new user form already. 
Can anyone at helpdesk review and grant the permit for me?
Thanks.

**Comment by kltm** [comment]
@vanaukenk Would you confirm?

**Comment by vanaukenk** [comment]
@kltm - Yes, Jae is a new WB curator who will be working on GO-CAM models.

**Comment by kltm** [comment]
Fixing with https://github.com/geneontology/go-site/pull/449
