### ISSUE TITLE
Drill-down tree

### ISSUE THREAD

**Issue by corinabioinformatic** [geneontology/helpdesk#69]
Dear GeneOntology HelpDesk,

Not sure what does it mean the numbers at the drill-down web page:
[http://amigo.geneontology.org/amigo/dd_browse](url)
If I didn't missunderstand:
-955007 is the number of annotated genes across all the species.
-809627 is the number of biological processes annotations
-737764  is the number of cellular component annotations
-773697  is the number of molecular function annotations

But once I parse the 'go.owl.rdf' file the downloads page [http://purl.obolibrary.org/obo/go.owl](url) and extract all the classes, I get in total 49185 Gene ontology IDs (some of them deprecated. So I'm missing any variable to reach the numbers described above, right? 

May I ask how do you calculate it? 

Corina

**Comment by kltm** [comment]
@corinabioinformatic 

For the main part of our data, there is a distinction between GO classes, as found in the OWL file, and the annotation data: http://geneontology.org/page/download-annotations .

AmiGO mixes the ontology and annotation data to produce what you see: http://amigo.geneontology.org/amigo/load_details .
