### ISSUE TITLE
TermGenie

### ISSUE THREAD

**Issue by NancyCampbell** [geneontology/helpdesk#7]
Hi,
Is the TermGenie site still down? Is there an alternative?
Thanks
Nancy

**Comment by cmungall** [comment]
We need to rewire TermGenie to point to the GitHub repo instead of svn. 
I'm not sure when I'll get the chance to do this.

Top priority for the editors group is getting high priority TG tickets 
encoded as DOSDP YAML. Once this is done we'll unveil the TG 
replacement.

**Comment by NancyCampbell** [comment]
Thanks for the clarification. I will request terms on Gene ontology/go-ontology GitHub repository for now.
