### ISSUE TITLE
Old GAFs

### ISSUE THREAD

**Issue by Antonialock** [geneontology/helpdesk#73]
Hello,

I would like to know the whereabouts of archived GAFs (going back 10 or so years). I am only interested in human annotation so if filtered files exist that would be great.

Thanks!

**Comment by kltm** [comment]
@Antonialock You're best bet would probably be going and just getting the files from http://archive.geneontology.org/ , which go back in some form or another until 2002. You may also want to look at the legacy GO SVN anonymous access: http://geneontology.org/page/svn-help .

**Comment by Antonialock** [comment]
Thanks! I didn't find the link to the archive on the website
(http://geneontology.org/page/download-annotations)

**Comment by kltm** [comment]
Hmmm....yes. Still here on this old page though: http://geneontology.org/page/ftp-and-cvs-downloads
Likely is was removed from the menus during a refactor. We'll need to rewrite a bunch of this...
