### ISSUE TITLE
Gene ontology for Sorghum bicolor

### ISSUE THREAD

**Issue by belw27** [geneontology/helpdesk#74]
Hi! I am wondering what has happened to Sorghum bicolor? I have used this species previously on the GO and PANTHER websites but it has now disappeared?
thanks
Belinda

**Comment by kltm** [comment]
@cmungall @pgaudet 
Any ideas if this was dropped out or fell below a threshold?

**Comment by pgaudet** [comment]
I don't - @thomaspd  or @huaiyumi do you know ? 
Was the species removed from the Panther families?

**Comment by kltm** [comment]
@thomaspd @huaiyumi 
would you have any ideas about this issue?

**Comment by kltm** [comment]
@thomaspd @huaiyumi
would you have any ideas about this issue?

**Comment by belw27** [comment]
I have also found a feedback email address on the PANTHER website so hopefully they might come back with something.

**Comment by belw27** [comment]
I received an email back from PANTHER and have copied in below fyi. No explanation as to why however. Thanks for your help.
"We released a new version of PANTHER a month ago, and made a small adjustment to genomes in our database. We added 10 more genomes, but removed Sorghum. I am sorry about the inconvenience. We are looking into ways to support genomes that are not in our database. Meanwhile, you can refer to our Nature Protocol paper as how to analyze genomes that are not in our database."

**Comment by kltm** [comment]
@belw27 Great--thank you!
