### ISSUE TITLE
nr database accession number to go term

### ISSUE THREAD

**Issue by kltm** [geneontology/helpdesk#75]
_From @LujingF on November 17, 2017 7:16_

Hi, I'm looking for an annotation file which contains nr database accession number and go term, but I cannot find it. I got the blastx result, so I wanna use the accession number to find its go term. How I can download such annotation file? Many thanks.

_Copied from original issue: geneontology/go-annotation#1693_

**Comment by kltm** [comment]
Re-tagging @LujingF
@cmungall May have some further thoughts on this, but I do not believe that we provide any such annotation file. You may be interested in looking at the annotations download page at http://geneontology.org/page/download-annotations and considering a mapping script.

**Comment by cmungall** [comment]
You can download mappings from the nr numbers to uniprot and use that to look up GO assocations.

It sounds like what you are trying to do is exactly what tools such as blast2go already do - why not use that directly

Note that we do not generally recommend using blast as an annotation propagation method. Have you considered using interpro2go instead?
