### ISSUE TITLE
Ontology Engineering 

### ISSUE THREAD

**Issue by jaugusti** [geneontology/helpdesk#76]
Greetings, 

I am a master student at Universidade Federal de Santa Maria and my research is about bioinformatics, more specifically cancer and ontologies. I am studying ontology engineering and would like to know what is the methodolody used for the construction, formalization and validation of Gene Ontology (like: Ontology Development 101 [NOY and MCGUINESS], On-to-Knowledge and METHONTOLOGY, etc).

If you could suggest any source to ease my research. This is very important for me and for my work.

Thank you!

**Comment by kltm** [comment]
@cmungall I'm guessing that this is probably a question for you.

**Comment by kltm** [comment]
@cmungall Would you have any thoughts on this?

**Comment by cmungall** [comment]
I suggest you join the obo-discuss mail list and ask there. The methodology GO uses is largely shared across OBO. http://obofoundry.org/
