### ISSUE TITLE
go.obo download link doesn't work

### ISSUE THREAD

**Issue by huaiyumi** [geneontology/helpdesk#77]
On the download page (http://geneontology.org/page/download-ontology), the go.obo and go_basic.obo download links don't work.
http://snapshot.geneontology.org/ontology/go.obo

**Comment by kltm** [comment]
It actually works, we just have the wrong header. This causes some browsers to say there was an issue. If you look at the source or download it it should be fine.
https://github.com/geneontology/pipeline/issues/8

If this is not the issue, I'll reopen.

**Comment by kltm** [comment]
As well, you can "right-click" on a link and do a "Save as..." and the file should download just fine.
