### ISSUE TITLE
GO Annotation files from FlyBase etc have different number of annotated genes than GO Consortium - Which one to choose

### ISSUE THREAD

**Issue by NickJDnid16** [geneontology/helpdesk#8]
As the title notes, an example is that FlyBase contains ~1000 lethal knockout genes which are annotated with a lethal phenotype and a GO term. Whereas if I use the go_annotation file from GO Consortium, there is only ~500 which are annotated with a GO term.
Is FlyBase more liberal or is the annotation file from the Go Consortium older?

**Comment by kltm** [comment]
@NickJDnid16 

Would you be able to provide a couple of the annotations that were removed that you are concerned about? There may be different rationales in different cases.

Looking at the files, the current one provided by GO is based on the one currently offered on the FlyBase FTP site. The new header of the filtered file gives a good overview of the process:

```
 Note: The contents of this file may differ from that submitted to the
 GOC. The identifiers and syntax of the file have been checked, rows of
 data not meeting the standards set by the GOC have been removed. This
 file may also have annotations removed because the annotations for the
 listed Taxonomy identifier are only allowed in a file provided by
 another annotation project.  The original submitted file is available from:
  http://www.geneontology.org/gene-associations/submission/

 For information on which taxon are allowed in which files please see:
  http://www.geneontology.org/GO.annotation.shtml#script
```

Digging in a little bit more, I'm seeing `replaced_by` terms being updated and some removals, no doubt triggered by a filter script violation. Perhaps @cmungall can give some more insight about what the specific violations are?

**Comment by hattrill** [comment]
Hi Nick,

I see that you've opened an issue here on the differences in the GAF file. I believe we narrowed down the source of your problems to the phenotype file, which Gillian is now helping you with via FlyBase helpmail.
Would it be ok to close this ticket here?

Thanks, Helen

**Comment by NickJDnid16** [comment]
Hi Helen,
Sorry for a delay.
Yes I think that would be fine. Thank you.
