### ISSUE TITLE
Ontology download links don't work

### ISSUE THREAD

**Issue by huaiyumi** [geneontology/helpdesk#81]
The links to download go.obo and go_basic.obo are not working on the download page: http://geneontology.org/page/download-ontology

**Comment by kltm** [comment]
@huaiyumi Did you seen the answer given here:

https://github.com/geneontology/helpdesk/issues/77

**Comment by huaiyumi** [comment]
I remember submitting one yesterday, but I can't find it in the thread, neither did I receive any emails.

**Comment by kltm** [comment]
Not getting any emails may be due to how you have setup GitHub. Maybe there should be an SOP for users to set this up "right"? (also pinging @cmungall and @pgaudet for input there)

The original query was already closed at the link above: #77 .
