### ISSUE TITLE
Add a GO term for "cold-induced thermogenesis" and the associated mouse genes

### ISSUE THREAD

**Issue by dsptk2017** [geneontology/helpdesk#83]
I have curated a list of comprehensive genes  ( http://citgenedb.yubiolab.org) affecting cold-induced thermogenesis (CIT), which should be an "adaptive thermogenesis". 
Could you help add this term and the gene list to GO? The process (http://geneontology.org/page/contributing-go) is a  little confused to me. Should this be considered as "ontology" or "annotations" or both on the following webpage? Could you make the contribution process easy?

Let me introduce my criterion briefly.
 For a gene to be considered, my criterion is that some thermogenic phenotypes, such as body temperature, daily energy expenditure, and oxygen consumption, must be confirmed to be changed in vivo or ex vivo using an animal model treated with cold. There can be a variety of
animal models, such as knockout (including conditional knockout), or over-expression, or drug/antibody inhibition, as long as the gene is perturbed.

 For example, body temperature is changed by HDAC3 using conditional knock-out mice in cold condition.
 Histone deacetylase 3 prepares brown adipose tissue for acute thermogenic challenge.
https://www.ncbi.nlm.nih.gov/pubmed/28614293

 To be stringent, genes that have only been tested in vitro will not be considered and the treatment must be by cold exposure. The following paper about Celf1 only has in vitro study and does not have cold exposure. Thus, Celf1 is not considered according to our curation criteria.

 Dynamic transcriptome changes during adipose tissue energy expenditure
reveal critical roles for long noncoding RNA regulators.
https://www.ncbi.nlm.nih.gov/pubmed/28763438

**Comment by kltm** [comment]
@vanaukenk @ukemi 
What would be the best place for this request? Shall I bump it over to `go-ontology`?

**Comment by ukemi** [comment]
I think it should be two separate requests, one to request on the ontology tracker to request the term (we already have heat generation and homiothermy), so those might suffice. Alternatively we could add a separate term that is a child of both. For the new annotations, I think we should open a separate ticket on the annotation tracker. Do you agree @vanaukenk ?

**Comment by kltm** [comment]
@vanaukenk Would you have any follow-up for this question?

**Comment by dsptk2017** [comment]
Hi,
     Is there any progress about integrating our curation results into the Gene
ontology?

**Comment by hdrabkin** [comment]
Hi @dsptk2017 

1. I would think the  annotations be put into protein2go (@dsptk2017 may need to contact 
The annotations should conform to GAF2 specifications in a tab-delimited file
http://geneontology.org/page/submitting-go-annotations
Protein2GO and the GOA database and annotations please email goa@ebi.ac.uk
but we can assign this to a GOA representative 

 2. A term request should be submitted to the go/ontology tracker, and have minimally

  a. term name
 b. term definition and PMID reference 
 c. suggested is_a parent(s)

The term requestion should be submitted to the go/ontology tracker. @dsptk2017 submit there
The annotations: should be submitted to go/annotation tracker;  @dsptk2017 submit there.

**Comment by dsptk2017** [comment]
Hi, @hdrabkin 

I am a bit confused about your instructions.  
**1. I would think the annotations be put into protein2go (@dsptk2017 may need to contact
The annotations should conform to GAF2 specifications in a tab-delimited file
http://geneontology.org/page/submitting-go-annotations
Protein2GO and the GOA database and annotations please email goa@ebi.ac.uk
but we can assign this to a GOA representative**
  My questions are 1) what's protein2go database? 2) have you assigned this to a GOA representative?
**2. A term request should be submitted to the go/ontology tracker, and have minimally

a. term name
b. term definition and PMID reference
c. suggested is_a parent(s)

The term requestion should be submitted to the go/ontology tracker. @dsptk2017 submit there
The annotations: should be submitted to go/annotation tracker; @dsptk2017 submit there.**
My questions are 1) where should the annotations be submitted on the hell ? because you first said the annotations should be put into protein2go database.  But here  you said"The annotations: should be submitted to go/annotation tracker; @dsptk2017 submit there."  2) where is go/annotation tracker? Could you give me a link to there?

**Comment by dsptk2017** [comment]
@hdrabkin 
I don't receive your answer to my last questions proposed 10 days ago. Have you seen them? Expect your answers.

**Comment by hdrabkin** [comment]
I have been away for some time, and am still in the process of catch-up
I was perhaps suggesting that you contact GOA and be given a protein@go account and be assigned someone who would teach you how to use the tool and then you would enter them yourself. 
 the GOA db (using protein@go is the tool used to enter the annotatins) , and then they would become available to the GOC. 
The annotations themselves would not be submitted to the annotation tracker, as it is a system to track issus with existing annotations, etc. I was suggesting you submit this request in the annotation tracker so that the right people could start helping you.
(tracker is here: https://github.com/geneontology/go-annotation/issues)
For protein2GO access, please write to goa@ebi.ac.uk; they will discuss the best way to proceed.

**Comment by dsptk2017** [comment]
@hdrabkin 
I have contacted GOA, but they suggested me return here saying that there was nothing they can really do with getting these added since we are not Gene Ontology editors. 

There are two things that I want to clarify: 1)our curation work is already done and there are 142 genes enhancing/suppressing thermogenesis upon cold exposure. 2)  MGI have included our curation results as Mammalian Phenotype Ontology annotations. 3) we want to add a GO term of cold-induced thermogenesis, which is absent from present GO terms. 

Looking forward your feedback.

Best

**Comment by ukemi** [comment]
Hi @dsptk2017  and @hdrabkin .

We already have heat generation and homiothermy. Do those terms suffice? If not, we could add the separate terms. Can you give us advice about their placement in the ontology and how we can define them? Should they be children of the existing terms? I think we need to distinguish the two tasks here:

1. Adding terms to the ontology if needed.
2. Adding the annotations to the ontology to the appropriate terms with evidence, etc.

This ticket should cover the first of these tasks.

**Comment by dsptk2017** [comment]
Hi, @ukemi @hdrabkin 

No. the terms of heat generation and homeothermy do not suffice.  Cold-induced thermogenesis (CIT) should be a children term of the existing term "adaptive thermogenesis". In GO, adaptive thermogenesis has only one children term "diet-induced thermogenesis".  Cold-induced thermogenesis is another important type of adaptive thermogenesis, which is an endothermic thermoregulation process with a basic property of the ability to generate heat by increasing metabolism in response to cold ambient temperatures to maintain a stable core body temperature. As for the CIT genes, if the genes are perturbed, the thermogenic phenotypes, such as body temperature, energy expenditure, will be greatly changed under cold condition. 

If you have any question, contact me without hesitation.

Best

Su-Ping

**Comment by dsptk2017** [comment]
Hi,  @ukemi   I have answered all of your questions. What's the progress?

**Comment by dsptk2017** [comment]
@hdrabkin you added the CIT term. But how should the associated mouse genes curated by us be linked to the term?

**Comment by hdrabkin** [comment]
Usually, when there is a project done by a group, they would get training from GOA to use protein@go to enter their annotations. The group/user would get some sort of xref to indicate the annotations came from their project. Once approved, the annotations would become part of the GOA database,  MGI downloads the GOA mouse set, and incorporates them into the MGI db, as well as contributes them to the GOC (mouse annotations are the responsibility of MGI no matter where they come from).
You might look in Amigo for annotations for the mouse gene Angpt2, and look for the contributor DFLAT. . The people that did those using protein@go put them into GOA; we then pull them into our db, then we output them in a GAF and amigo displays the contributor as DFLAT. 
Sorry if the procedure seems complicated but it is the only way the annotations can get in and preserve that you would be the contributor.

**Comment by dsptk2017** [comment]
Ok. Thanks. I will do that.
