### ISSUE TITLE
GAF help page docs needed

### ISSUE THREAD

**Issue by pkarp111** [geneontology/helpdesk#84]
The following page should provide a description of the meaning of the lines in this file in the introduction.  As written it is missing the big picture for the reader...

 http://geneontology.org/page/go-annotation-file-format-20

**Comment by kltm** [comment]
@pkarp111 
Just to clarify, this document is intended for people interested in creating or parsing GAFs. Within the introduction, there is a link to more general documentation at http://www.geneontology.org/page/go-annotation-policies .

**Comment by pkarp111** [comment]
Yes, I'm aware of that.  Still, you want to describe not only the syntax 
of the file format but the
meaning of the lines within the file.  A few sentences would do it.

**Comment by cmungall** [comment]
Good point. We're doing a general overhaul of all docs in in January, but we should add the note in beforehand.

**Comment by suzialeksander** [comment]
Not sure where to raise this point, but if I'm on http://geneontology.org/page/go-annotation-file-format-20 & trying to look for information on column 16, the "See the documentation on _using the annotation extension column_ for details of practical usage" link is not accessible 
Link:
http://geneontology.org/GO.annotation.extension.shtml

Returns:
Access denied
You are not authorized to access this page. 


Thanks

**Comment by kltm** [comment]
@suzialeksander 
We'll probably move that somewhere else, but could you pop that into its own top level ticket?
I think we're currently looking at how to handle things like this, so it might be just a moment. (We've actually found a *lot* of "leaks" like this in the docs, so it's part of a larger problem.)

**Comment by suzialeksander** [comment]
An update: I think these outward-facing pages will be redesigned quite soon, and we will update this page with the "move".  Leaving this ticket open so we don't forget.

**Comment by suzialeksander** [comment]
@pkarp111 , there's been a very short sentence added to the GAF and GPI/GPAD pages, gleaned from the handbook.  Is this too short (we're honestly *trying* to keep the site concise and simple), or it it enough to show "the big picture"?
