### ISSUE TITLE
Wrong figure in documentation!

### ISSUE THREAD

**Issue by fidaner** [geneontology/helpdesk#85]
Hello,
On this page: http://www.geneontology.org/page/ontology-relations 
The figure just above the text "negative regulation of smoothened signaling pathway involved in ventral spinal cord patterning negatively regulates smoothened signaling pathway involved in ventral spinal cord patterning, ...." is wrong.

There's a copy & paste error in documentation. Will you correct and inform?

**Comment by kltm** [comment]
@vanaukenk @ukemi Would one of you be able to take a look at the ontology documentations?

**Comment by ukemi** [comment]
It looks like there was a cut and paste error in this document. However, we plan to completely revamp the relations documentation in mid-January to correct and expand it with respect to the new annotation models. regulates_o_'part of' -> regulates will no longer be a valid inference.
