### ISSUE TITLE
Amount of Experimentally validated GOAnnotations dramatically decreased

### ISSUE THREAD

**Issue by yotamfr** [geneontology/helpdesk#86]
Hello GO team!

I recently updated my local database (MongoDB) of GeneOntology Annotations by downloading goa_uniprot_all.gaf and discovered that the number of **Experimentally** validated annotations has unexpectedly and dramatically decreased from 829,532 to 67846.

As I hold a copy of the data on a another machine, I know this change has happened somewhere between the dates 23/09/2017 and 04/12/2017.

>>>BEFORE 23/09/2017 :
> db.goa_uniprot.count({'Evidence': {'$in': ["EXP", "IDA", "IPI", "IMP", "IGI", "IEP"]}, 'DB': 'UniProtKB'})
829532

>>>AFTER 04/12/2017 :
> db.goa_uniprot.count({'Evidence': {'$in': ["EXP", "IDA", "IPI", "IMP", "IGI", "IEP"]}, 'DB': 'UniProtKB'})
67846

Could you please explain to me what happened?

Best,
y

**Comment by kltm** [comment]
@yotamfr 
Would mind supplying the URLs where downloaded these files from?

**Comment by yotamfr** [comment]
Yes, 

The noiea file I downloaded from:
http://geneontology.org/gene-associations/goa_uniprot_all_noiea.gaf.gz

The goa_uniprot_all.gaf I downloaded from:
ftp://ftp.ebi.ac.uk/pub/databases/GO/goa/UNIPROT/goa_uniprot_all.gaf.gz

Both contain only 67846 annotations of experimental codes (as for Dec 9 2017).

**Comment by kltm** [comment]
@yotamfr 
To clarify, you are looking at a drop in the experimental annotations available in the ftp://ftp.ebi.ac.uk/pub/databases/GO/goa/UNIPROT/goa_uniprot_all.gaf.gz file?
If this is the case, it may be best to contact them directly about file changes: https://www.ebi.ac.uk/GOA/contactus .

**Comment by yotamfr** [comment]
Yes, this is the case. I sent them a message.
