### ISSUE TITLE
Reasoner won't initialize for go-plus

### ISSUE THREAD

**Issue by mdebellis** [geneontology/helpdesk#87]
I've downloaded the ontology at: http://purl.obolibrary.org/obo/go/extensions/go-plus.owl to my local machine. I'm trying to load it into the latest version of Protege (5.2.0). I'm using the Pellet reasoner. When I try to initialize the Reasoner it seems to just hang. I tried it just now re-setting my preferences so that every box in the Protege preference tab was unchecked except for  "Individual Inferences: Types". I went to Reasoner>Start reasoner and then walked away from my computer. That was about 45 minutes ago and the status in the lower right corner of Protege still says "Reasoner initialization in progress". I'm running on an iMac OSX 10.13.2 with 2.7 Ghz and 8 GB of memory.  Java Version 8 Update 151.

**Comment by kltm** [comment]
@mdebellis
Unfortunately, we don't work on Protege and typically do not offer desktop support. That said, we do have several people who work a lot with that software and the GO that might be able to help.
@cmungall @ukemi @vanaukenk Would you happen to have any tips or ideas for @mdebellis?

**Comment by cmungall** [comment]
You need to use an EL++ reasoner like Elk, Pellet won't complete for most mid sized bio-ontologies

**Comment by cmungall** [comment]
See also

Mungall, C. J., Dietze, H., & Osumi-Sutherland, D. (2014). Use of OWL within the Gene Ontology. In M. Keet & V. Tamma (Eds.), Proceedings of the 11th International Workshop on OWL: Experiences and Directions (OWLED 2014) (pp. 25–36). Riva del Garda, Italy, October 17-18, 2014. http://dx.doi.org/10.1101/010090
