### ISSUE TITLE
Visualization creator for GO graph - advanced option in not working

### ISSUE THREAD

**Issue by priscilag** [geneontology/helpdesk#88]
I have been trying to use the advanced format at visualization tool. But I'm getting a Bad Gateway (nginx/1.1.19). 

The simple tool is working.

Thanks for the attention.

**Comment by kltm** [comment]
@priscilag 
Could you paste in the input that you're attempting to use?
It may be that the input that you're attempting is larger than the tool was originally designed for (many years ago).

**Comment by priscilag** [comment]
Yeap, that was the problem. Now I know the tool support up to 54 terms. I
had 65.

Thanks!

**Comment by kltm** [comment]
@priscilag Apologies for the trouble. We're hoping to give that tool a lick of paint soon so that is can support more terms and other inputs.
