### ISSUE TITLE
Question about Gene Ontology

### ISSUE THREAD

**Issue by juniorresearcher** [geneontology/helpdesk#89]
Hi, 
I'm wondering what GO Class I should filter a list of proteins with in order to output only those that function as a cell surface receptor. What GO Class annotation (accession number/master class/children classes) should I use for this purpose?

**Comment by kltm** [comment]
@juniorresearcher 
Apologies--a response to this may be slow as the Holidays wrap up and people start warming up again.
It may be useful to give a bit more context about the analysis you're attempting, inputs, outputs, etc.

@ukemi @vanaukenk 
If either of you had any ideas, would you be able to follow up with this at your leisure?

**Comment by vanaukenk** [comment]
@juniorresearcher   Thanks for writing to the GO.

The most comprehensive list of cell surface receptors will probably come from a derived list of gene associations (i.e. annotations) found by querying several different GO terms.  

Using the AmiGO2 browser:

http://amigo.geneontology.org/amigo/search/ontology

you can identify a candidate set of cell surface receptors by querying on these two GO terms and taking the union of gene products annotated to both terms (or one of their descendants):

Molecular Function:
receptor activity ['GO:0004872']

Cellular Component:
plasma membrane ['GO:0005886']

You can also cast a potentially wider net by looking at the set of genes annotated to other Cellular Component terms, but not also receptor activity, such as : 

external side of plasma membrane  ['GO:0009897']
plasma membrane receptor complex ['GO:0098802']

or possibly even:

integral component of membrane ['GO:0016021']

although these queries, particularly the latter, will give you a broader set of gene products that you will likely need to prune (see below).

If desired, you can use the filter options on the left side of the page to filter the resulting annotations for such things as:

Organism (e.g. if you are interested in annotations for a particular organism) 
PANTHER family (e.g. if you are interested in particular types of cell surface receptors)
Evidence (e.g. if you are interested in only experimentally supported annotations)
etc.

Annotations can be downloaded by clicking on the Download link at the top of the annotations table.

Please let us know if you need any additional help or have questions about the output.
