### ISSUE TITLE
Update hyperlinks to QuickGO Graph Views

### ISSUE THREAD

**Issue by monicacecilia** [geneontology/helpdesk#91]
Hola Don @kltm!

I was trying to find an example image to use for a talk and came across a broken image icon in AmiGO. I think the links to QuickGO may need to be updated after the new site went live at EBI? This may be happening for all GO terms (I only tried two). 

To reproduce:
- Navigate to a GO term (e.g. http://amigo.geneontology.org/amigo/term/GO:0010928)
- Click on 'Graph Views' tab at the bottom.
- AmiGO is pointing to a QuickGO URL which actually resolves into the appropriate page at EBI, in this case http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0010928 but the graph is not being displayed in AmiGO.

Ten bucks say you're going to update the name I gave to this issue. :bowtie:

**Comment by monicacecilia** [comment]
Eek, forgot the screenshot. . .
 
![screen shot 2018-01-09 at 12 21 12 pm](https://user-images.githubusercontent.com/1714621/34741955-59eaf2c4-f539-11e7-9864-96559dd73e12.png)

**Comment by kltm** [comment]
@monicacecilia 
Thank you for reporting.
Actually, I generally do not alter tickets that come into the Helpdesk, so reporting users do not lose them. If it makes it to one of the trackers though...

**Comment by kltm** [comment]
Hm, digging into the QuickGO page a little bit, it seems that they no longer have/offer the image for download and/or caching as they used to. In fact, the image on the QuickGO site appears to just be a binary blob stuck in as the source.

@tonysawfordebi Would you happen to have any information on changes to the public products available from QuickGO?

**Comment by tonysawfordebi** [comment]
There is a new service that provides the ancestor chart data in exactly the same format as previously (PNG data):

https://www.ebi.ac.uk/QuickGO/services/ontology/go/terms/<go id>/chart'

for example:

    curl 'https://www.ebi.ac.uk/QuickGO/services/ontology/go/terms/GO:0006915/chart' > chart.png

You can generate a chart for multiple terms by supplying a list of GO IDs; for example:

    curl 'https://www.ebi.ac.uk/QuickGO/services/ontology/go/terms/GO:0006915,GO:0005515/chart' > chart.png

**Comment by kltm** [comment]
@tonysawfordebi Great--thank you for the information.

**Comment by kltm** [comment]
@monicacecilia The issue is now clarified and progress can be followed in the tracker here:
https://github.com/geneontology/amigo/issues/463

**Comment by monicacecilia** [comment]
woop woop!
