### ISSUE TITLE
Issue with human gaf file from GO Central

### ISSUE THREAD

**Issue by ggeorghiou** [geneontology/helpdesk#92]
Hi guys,

Not sure where this belongs but we just got an email from our internal helpdesk regarding the human gaf file not having the right number of annotations. The users email is here:

We noticed that this week when we downloaded and processed the files (goa_human.gaf.gz and goa_human_isoform.gaf.gz) from the Gene Ontology Consortium website (ftp://ftp.geneontology.org/pub/go/gene-associations/), the files are about 1/3 smaller than the previous ones. Is that right? Have you eliminated about a third of the human GO annotations or is it possible that there is a problem with the files? I know that you had a new release in December but the files on the GOC site are dated January 20th so we were not expecting the files to change that much. Any information you could give us would be greatly appreciated.

I checked our gaf files on our FTP site and we see that the published number of annotations (433,000 roughly) matches what is listed on the GO Consortium page but the number of annotations in the file is about 2/3 of that. Any ideas on what may be going on?

Best,

George

**Comment by cmungall** [comment]
We're investigating this right now, we'll be back with more info ASAP

**Comment by ggeorghiou** [comment]
Hi Chris, I'm tagging @tonysawfordebi in this.

**Comment by tonysawfordebi** [comment]
I haven't looked into this, but I'm guessing it might have something to do with https://github.com/geneontology/go-annotation/issues/1772

**Comment by tonysawfordebi** [comment]
I've just had a look at the numbers in our database, and the complete human annotation set for the last GOA release consists of 545,962 annotations, of which 159,201 are attributed to UniProt. so that lends weight to the hypothesis that all of the UniProt-attributed annotations were filtered out because of the problem with the metadata files.

**Comment by kltm** [comment]
Leaving as pointing to resolving geneontology/go-annotation#1772
