### ISSUE TITLE
'Access Denied': broken link for annotation extension info on GAF 2.0 page

### ISSUE THREAD

**Issue by suzialeksander** [geneontology/helpdesk#96]
On http://geneontology.org/page/go-annotation-file-format-20 & trying to look for information on column 16, the "See the documentation on _using the annotation extension column_ for details of practical usage" link is not accessible
Link:
http://geneontology.org/GO.annotation.extension.shtml

Returns:
Access denied
You are not authorized to access this page.

**Comment by kltm** [comment]
@pgaudet @vanaukenk 
Would we have anybody available to do a quick check through there to look at "dangling" documentation links?

**Comment by pgaudet** [comment]
@kltm 
Do you have a list ? I can look at it. 

Thanks, Pascale

**Comment by kltm** [comment]
Yes, this was the list supplied during the docathon meeting, titled "found pages" on 2018-01-24.

**Comment by pgaudet** [comment]
Removed link.
