### ISSUE TITLE
X. tropicalis database mismatch

### ISSUE THREAD

**Issue by levisna** [geneontology/helpdesk#98]
Hello,

I have only recently  begun using the geneontology/PANTHER system for gene ontology enrichment analysis. In my preliminary efforts to become familiar with the tool, I downloaded the entire uniprot dataset for Xenopus tropicalis. This dataset contains uniprot IDs and a variety of other information including gene ontology codes for roughly 36000 genes. However, when I use these uniprot IDs in the geneontology?PANTHER system, it only maps about 21000 of them leaving another ~15000 unmapped. Further, the reference for X. tropicalis has about 24000 IDs.

Finding this result, I then downloaded the X. trop IDs directly from Xenbase so that they were in a species-specific format. This set had about 21000 genes. When I ran it through the PANTHER system,  only ~7000 were mapped and another ~14000 were not.

I am confused as to why this would occur given that the GO terms have been assigned to each annotation in Uniprot. Can you provide any insight and/or advice? For example, where did the X. tropicalis reference gene list come from if neither uniprot nor xenbase matches it?

Thanks!

**Comment by suzialeksander** [comment]
@levisna 
Our apologies for the slow response. Could you possibly clarify the download location of the file that you're using.

@huaiyumi @thomaspd 
Would either of you know the right contact person to help work through this issue?

**Comment by suzialeksander** [comment]
@levisna, do you remember the URL you downloaded this file from? We would like to resolve this if there's still a problem.  Thanks.

**Comment by suzialeksander** [comment]
Closing due to lack of info.

**Comment by huaiyumi** [comment]
This is probably a reference proteome issue. Should let Maria know.
